<?php
/**
 * Banco de actividades · Nivel N8 (8.º · PAI 3 · Diseño)
 */

declare(strict_types=1);

return [

['codigo' => 'VCP-8-01', 'titulo' => 'La caja de herramientas: funciones bien diseñadas',
 'objeto' => 'la biblioteca de funciones',
 'resumen' => 'Convertir un programa largo y repetido en un conjunto de funciones con una sola responsabilidad cada una.',
 'descripcion' => '<p>El estudiante recibe un programa de doscientas líneas que funciona pero es imposible de mantener, y su tarea es refactorizarlo en funciones. No escribe nada nuevo: reorganiza. Es la primera experiencia de mantenimiento de código, una habilidad que las actividades de creación desde cero nunca enseñan.</p><p>El criterio de calidad es explícito: cada función debe caber en la pantalla, tener un nombre que diga que hace y no depender de variables globales. Al final, el estudiante agrega una función nueva al programa refactorizado y cronometra cuanto tardó comparado con el original.</p>',
 'pregunta' => '¿Que hace que un programa sea fácil o imposible de modificar seis meses después?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Pensador|Reflexivo', 'atl' => 'Organización|Pensamiento crítico',
 'objetivos' => 'Identificar responsabilidades separadas dentro de un programa|Extraer funciones con parámetros y retorno|Eliminar dependencias de variables globales|Medir el efecto de la refactorización en el tiempo de modificación',
 'entregables' => 'Programa original anotado con las responsabilidades marcadas|Versión refactorizada en funciones|Medición de tiempo al agregar una función nueva en ambas versiones',
 'lenguaje' => 'Python', 'dificultad' => 'intermedio', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "# Programa original: gestion de notas (sin funciones)\nnotas = []\nwhile True:\n    op = input(\"1 agregar 2 promedio 3 maximo 4 salir: \")\n    if op == \"1\":\n        notas.append(float(input(\"Nota: \")))\n    elif op == \"2\":\n        s = 0\n        for n in notas:\n            s += n\n        print(s / len(notas))\n    # ... y asi por doscientas lineas\n\n# TODO: reescribe usando agregar_nota, promedio, maximo, menu",
 'fases' => [
   ['indagar', 'Diagnosticar el código', 'Lee el programa entregado y marca con colores cada responsabilidad distinta que encuentres. Anota cuantas veces se repite el mismo cálculo y donde está el riesgo si cambia una regla.', 'Programa anotado con responsabilidades y conteo de repeticiones.', 45],
   ['desarrollar', 'Diseñar la firma de cada función', 'Para cada responsabilidad define nombre, parámetros y valor de retorno. Escríbelo como tabla antes de tocar el código. Verifica que ninguna función necesite variables globales.', 'Tabla de firmas de al menos seis funciones.', 45],
   ['crear', 'Refactorizar sin romper', 'Extrae una función a la vez y ejecuta el programa después de cada extracción. Si algo se rompe, deshaz esa extracción antes de continuar.', 'Versión refactorizada funcionando igual que la original.', 80],
   ['evaluar', 'Prueba de mantenimiento', 'Agrega la función nota mínima en las dos versiones y cronometra. Pide a un compañero que agregue otra función y cronométralo también. Concluye con datos.', 'Tabla de tiempos y conclusión sobre el valor de la refactorización.', 45],
 ],
 'recursos' => [
   ['codigo', 'notas_sin_funciones.py', 'Programa de partida para refactorizar.'],
   ['lectura', 'Una función, una responsabilidad', 'Guía con cinco señales de que una función hace demasiado.'],
 ]],

['codigo' => 'VCP-8-02', 'titulo' => 'Leer y escribir archivos: las notas del curso',
 'objeto' => 'el gestor de notas en archivo',
 'resumen' => 'Programa que lee un archivo CSV de notas, calcula estadísticas y escribe un informe, sin perder datos por el camino.',
 'descripcion' => '<p>Los datos dejan de vivir dentro del programa. El estudiante lee un CSV real de notas, lo procesa y escribe un informe en otro archivo. Aparecen los problemas verdaderos del manejo de datos: filas incompletas, comas dentro del texto, números escritos como texto, tildes que se ven mal.</p><p>El archivo de entrada tiene errores deliberados. El estudiante debe decidir qué hacer con cada uno y documentar su decisión, porque en el manejo de datos no existe una única respuesta correcta pero sí decisiones que deben justificarse.</p>',
 'pregunta' => '¿Que hago con un dato que está mal: lo borro, lo corrijo o lo dejo?',
 'contexto' => 'Equidad y desarrollo', 'concepto' => 'Sistemas',
 'perfil' => 'Íntegro|Pensador', 'atl' => 'Organización|Pensamiento crítico',
 'objetivos' => 'Abrir y cerrar archivos correctamente|Procesar CSV línea por línea|Detectar y documentar datos anómalos|Escribir un archivo de salida con formato definido',
 'entregables' => 'Archivo notas.py que lee, procesa y escribe|Informe generado|Registro de decisiones sobre los cinco datos anómalos encontrados',
 'lenguaje' => 'Python', 'dificultad' => 'intermedio', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "with open(\"notas.csv\", encoding=\"utf-8\") as f:\n    lineas = f.readlines()\n\nencabezado = lineas[0].strip().split(\",\")\nfor linea in lineas[1:]:\n    partes = linea.strip().split(\",\")\n    # TODO: valida que partes tenga la longitud correcta\n    # TODO: convierte la nota a float con manejo de error\n\n# TODO: escribe informe.txt con promedio, maximo y minimo por materia",
 'fases' => [
   ['indagar', 'Anatomía de un archivo de datos', 'Abre el CSV en un editor de texto y en una hoja de cálculo. Anota cinco diferencias entre lo que ves en cada uno. Identifica al menos cinco filas con problemas.', 'Lista de cinco anomalías con la fila exacta donde aparecen.', 45],
   ['desarrollar', 'Política de datos', 'Decide qué hará tu programa con cada tipo de anomalía: fila incompleta, nota fuera de rango, nombre vacío, nota como texto, duplicado. Justifica cada decisión.', 'Tabla de política de datos con cinco reglas justificadas.', 45],
   ['crear', 'Leer, procesar, escribir', 'Programa la lectura con validación, el cálculo de estadísticas por materia y la escritura del informe. Muestra en pantalla cuantas filas se descartaron y por que.', 'Archivo notas.py y el informe generado.', 80],
   ['evaluar', 'Verificar contra hoja de cálculo', 'Calcula los mismos promedios en una hoja de cálculo y compara. Si difieren, encuentra la causa: casi siempre es una fila que uno de los dos incluyó y el otro no.', 'Comparación de resultados y explicación de las diferencias.', 45],
 ],
 'recursos' => [
   ['dataset', 'notas_curso.csv', 'Archivo con 120 filas y errores deliberados.'],
   ['plantilla', 'Registro de decisiones sobre datos', 'Anomalía, decisión, justificación, filas afectadas.'],
 ]],

['codigo' => 'VCP-8-03', 'titulo' => 'Estación meteorológica del colegio',
 'objeto' => 'la estación meteorológica',
 'resumen' => 'Proyecto insignia de 8.º: registrar, analizar y comunicar los datos de temperatura y humedad del colegio durante tres semanas.',
 'descripcion' => '<p>El estudiante toma o recibe mediciones diarias de temperatura, humedad y lluvia durante tres semanas, construye el programa que las almacena y analiza, y produce un boletín semanal para la comunidad escolar. Si el colegio cuenta con sensores, se conectan; si no, se usan mediciones manuales o datos abiertos del IDEAM.</p><p>Es el proyecto que conecta Diseño con Ciencias e Individuos y Sociedades. El producto no es el programa: es el boletín. El programa es la herramienta que lo hace posible, y esa distinción cambia la forma en que el estudiante juzga su propio trabajo.</p>',
 'pregunta' => '¿Que puedo afirmar con certeza sobre el clima de mi colegio con tres semanas de datos?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Relaciones',
 'perfil' => 'Indagador|Informado e instruido|Buen comunicador', 'atl' => 'Alfabetización informacional|Organización|Comunicación',
 'objetivos' => 'Diseñar un protocolo de medición reproducible|Almacenar series temporales en archivo|Calcular medias móviles y detectar valores atípicos|Comunicar conclusiones sin sobreinterpretar los datos',
 'entregables' => 'Protocolo de medición|Base de datos de tres semanas|Archivo estacion.py con análisis|Tres boletines semanales publicados|Bitácora del ciclo de diseño',
 'lenguaje' => 'Python', 'dificultad' => 'intermedio', 'sesiones' => 7, 'horas' => 7.0, 'ia' => 1,
 'codigo_inicial' => "import csv\nfrom datetime import date\n\ndef registrar(fecha, temp, hum, lluvia):\n    with open(\"clima.csv\", \"a\", newline=\"\", encoding=\"utf-8\") as f:\n        csv.writer(f).writerow([fecha, temp, hum, lluvia])\n\n# TODO: cargar() que devuelva la lista de registros\n# TODO: promedio_semanal(), maximo(), minimo()\n# TODO: detectar_atipicos() con el criterio que definas",
 'fases' => [
   ['indagar', 'Como se mide bien el clima', 'Investiga como se toma una medición meteorológica válida: hora, ubicación, altura, sombra. Compara dos fuentes y redacta el planteamiento del problema: quien necesita este boletín y para que.', 'Protocolo de medición con fuentes y planteamiento del problema.', 60],
   ['desarrollar', 'Diseño del registro y del boletín', 'Define la estructura del archivo de datos, la frecuencia de medición y el contenido exacto del boletín semanal. Escribe seis especificaciones medibles, una sobre la puntualidad del registro.', 'Estructura de datos, boceto del boletín y seis especificaciones.', 60],
   ['crear', 'Registrar tres semanas y analizar', 'Toma las mediciones a diario según tu protocolo. Programa la carga, las estadísticas semanales y la detección de valores atípicos. Genera un boletín cada viernes.', 'Datos de tres semanas, estacion.py funcionando y tres boletines.', 180],
   ['evaluar', 'Que puedo afirmar y que no', 'Revisa cada afirmación de tus boletines y marca si tus datos la respaldan. Corrige las que no. Pide a un docente de Ciencias que revise una conclusión y registra su comentario.', 'Revisión de afirmaciones, correcciones y comentario del docente de Ciencias.', 60],
 ],
 'recursos' => [
   ['plantilla', 'Protocolo de medición meteorológica', 'Formato con hora, ubicación, instrumento y responsable.'],
   ['dataset', 'Datos abiertos de clima', 'Serie de referencia para comparar con las mediciones propias.'],
   ['plantilla', 'Boletín semanal de una página', 'Estructura: resumen, gráfica, tres datos, una conclusión.'],
 ]],

['codigo' => 'VCP-8-04', 'titulo' => 'Gráficas que cuentan la historia de los datos',
 'objeto' => 'el conjunto de gráficas',
 'resumen' => 'Elegir el tipo de gráfica adecuado para cada pregunta y detectar gráficas que engañan.',
 'descripcion' => '<p>El estudiante aprende matplotlib, pero el contenido central no es la biblioteca: es la decisión sobre qué gráfica corresponde a qué pregunta. Barras para comparar categorías, líneas para ver evolución, dispersión para relacionar dos variables.</p><p>La segunda mitad de la actividad es un ejercicio de alfabetización mediática: el estudiante construye deliberadamente una gráfica engañosa con sus propios datos —eje truncado, escala manipulada— y explica cómo detectarla. Nadie olvida ese truco después de haberlo fabricado.</p>',
 'pregunta' => '¿Puede una gráfica correcta en sus números mentir en su mensaje?',
 'contexto' => 'Globalización y sustentabilidad', 'concepto' => 'Comunicación',
 'perfil' => 'Pensador|Íntegro', 'atl' => 'Alfabetización mediática|Pensamiento crítico',
 'objetivos' => 'Elegir el tipo de gráfica según la pregunta|Rotular ejes, unidades y fuente|Construir y desarmar una gráfica engañosa|Exportar imágenes para un informe',
 'entregables' => 'Tres gráficas correctas con rótulos completos|Una gráfica engañosa y su versión honesta|Explicación de la manipulación usada',
 'lenguaje' => 'Python (matplotlib)', 'dificultad' => 'intermedio', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "import matplotlib.pyplot as plt\n\nmaterias = [\"Mat\", \"Esp\", \"Cien\", \"Tec\"]\npromedios = [3.8, 4.1, 3.5, 4.4]\n\nplt.bar(materias, promedios)\nplt.ylabel(\"Promedio\")\n# TODO: agrega titulo y fuente\n# TODO: guarda la figura como png\nplt.show()",
 'fases' => [
   ['indagar', 'Gráficas en la prensa', 'Busca tres gráficas publicadas en medios. Para cada una determina qué pregunta responde y si el tipo elegido es el adecuado. Encuentra al menos una con eje manipulado.', 'Análisis de tres gráficas con el hallazgo de la manipulación.', 45],
   ['desarrollar', 'Una pregunta, una gráfica', 'Formula tres preguntas sobre tus propios datos y decide qué tipo de gráfica responde cada una. Justifica por qué descartaste los otros tipos.', 'Tabla de tres preguntas, gráfica elegida y justificación.', 40],
   ['crear', 'Construir las gráficas', 'Programa las tres gráficas con títulos, rótulos de ejes, unidades y fuente. Luego construye deliberadamente una versión engañosa de una de ellas.', 'Cuatro imágenes generadas por código.', 75],
   ['evaluar', 'Prueba de lectura', 'Muestra la gráfica engañosa a tres personas y pregúntales qué concluyen. Luego muéstrales la honesta. Registra el cambio de interpretación y explica la técnica usada.', 'Registro de tres lecturas y explicación de la manipulación.', 45],
 ],
 'recursos' => [
   ['lectura', 'Qué gráfica para qué pregunta', 'Tabla de decisión de una página.'],
   ['lectura', 'Cinco formas de mentir con gráficas', 'Eje truncado, escalas dobles, áreas, selección de periodo, orden.'],
 ]],

['codigo' => 'VCP-8-05', 'titulo' => 'Sistema de préstamo de la biblioteca',
 'objeto' => 'el sistema de préstamos',
 'resumen' => 'Aplicación de consola que registra préstamos y devoluciones con reglas de negocio reales y validación estricta.',
 'descripcion' => '<p>El estudiante implementa un sistema con reglas verdaderas: máximo dos libros por estudiante, catorce días de plazo, no se presta a quien tiene un libro vencido. Cada regla obliga a una validación, y cada validación obliga a decidir qué mensaje ve el usuario.</p><p>La actividad exige un conjunto de casos de prueba escrito antes del código, incluidos los casos límite: el estudiante que pide el tercer libro, el que devuelve un libro que no tenía, la fecha del día exacto del vencimiento.</p>',
 'pregunta' => '¿Cómo traduzco las reglas de una institución en condiciones que un programa pueda comprobar?',
 'contexto' => 'Equidad y desarrollo', 'concepto' => 'Sistemas',
 'perfil' => 'Íntegro|Pensador', 'atl' => 'Organización|Pensamiento crítico',
 'objetivos' => 'Traducir reglas de negocio en validaciones|Trabajar con fechas y plazos|Escribir casos de prueba antes del código|Persistir el estado en archivo',
 'entregables' => 'Tabla de casos de prueba escrita antes de programar|Archivo biblioteca.py con las cuatro reglas|Resultado de ejecutar todos los casos de prueba',
 'lenguaje' => 'Python', 'dificultad' => 'intermedio', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "from datetime import date, timedelta\n\nPLAZO_DIAS = 14\nMAX_LIBROS = 2\n\nprestamos = []  # {\"estudiante\": .., \"libro\": .., \"vence\": date}\n\ndef puede_prestar(estudiante):\n    # TODO: menos de MAX_LIBROS y ninguno vencido\n    pass\n\n# TODO: prestar(), devolver(), listar_vencidos()",
 'fases' => [
   ['indagar', 'Las reglas verdaderas', 'Entrevista a quien administra la biblioteca. Averigua las reglas exactas, incluidas las excepciones que aplican en la práctica pero no están escritas.', 'Documento de reglas con al menos dos excepciones no escritas.', 45],
   ['desarrollar', 'Casos de prueba primero', 'Escribe doce casos de prueba antes de programar: cuatro normales, cuatro de error y cuatro límite. Cada caso indica entrada, resultado esperado y regla que comprueba.', 'Tabla de doce casos de prueba.', 50],
   ['crear', 'Programar contra los casos', 'Implementa el sistema y ejecuta tus doce casos después de cada función terminada. Guarda los préstamos en archivo para que sobrevivan al cierre del programa.', 'Archivo biblioteca.py con persistencia y los doce casos pasando.', 90],
   ['evaluar', 'Prueba con la bibliotecaria', 'Muestra el sistema a la persona encargada y pídele que intente registrar un caso raro de su experiencia. Anota qué no contemplaste y clasifícalo como error o como decisión consciente.', 'Registro de la prueba y lista de casos no contemplados.', 50],
 ],
 'recursos' => [
   ['plantilla', 'Tabla de casos de prueba', 'Caso, entrada, esperado, obtenido, regla.'],
   ['lectura', 'Fechas y plazos en Python', 'date, timedelta y comparaciones.'],
 ]],

['codigo' => 'VCP-8-06', 'titulo' => 'Depuración: el programa que no funciona',
 'objeto' => 'el programa depurado',
 'resumen' => 'Encontrar y documentar siete errores plantados en un programa ajeno, usando un método sistemático en vez de adivinar.',
 'descripcion' => '<p>Se entrega un programa con siete errores de tipos distintos: sintaxis, nombre mal escrito, índice fuera de rango, división por cero, condición invertida, ciclo infinito y error lógico silencioso. El estudiante debe encontrarlos con método: leer el mensaje de error completo, aislar, reproducir, corregir y verificar.</p><p>El error lógico silencioso es el que enseña más: el programa no falla, simplemente da un resultado incorrecto. Solo lo encuentra quien compara con un cálculo manual, y por eso la actividad exige verificación externa.</p>',
 'pregunta' => '¿Qué hago cuando el programa no falla pero el resultado está mal?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Lógica',
 'perfil' => 'Pensador|Reflexivo', 'atl' => 'Pensamiento crítico|Autogestión',
 'objetivos' => 'Leer e interpretar mensajes de error|Aislar un error reduciendo el programa|Distinguir error de ejecución y error lógico|Documentar cada corrección con su causa',
 'entregables' => 'Bitácora de los siete errores con causa y corrección|Programa corregido y funcionando|Explicación del error lógico silencioso',
 'lenguaje' => 'Python', 'dificultad' => 'intermedio', 'sesiones' => 3, 'horas' => 3.0, 'ia' => 0,
 'codigo_inicial' => "# Programa con errores plantados: estadisticas de un curso\ndef promedio(notas):\n    suma = 0\n    for i in range(len(notas) + 1):\n        suma += notas[i]\n    return suma / len(notas)\n\ndef aprobados(notas, minimo):\n    total = 0\n    for n in notas:\n        if n < minimo:\n            total += 1\n    return total\n\n# ... cinco errores mas en el archivo entregado",
 'fases' => [
   ['indagar', 'Anatomía de un mensaje de error', 'Provoca a propósito cinco errores distintos en un programa mínimo. Copia el mensaje completo de cada uno y explica qué información da cada línea del mensaje.', 'Ficha de cinco errores con la interpretación de su mensaje.', 45],
   ['desarrollar', 'El método de depuración', 'Escribe tu procedimiento de cinco pasos para enfrentar un error. Debe incluir cómo aislar el problema y cómo verificar que la corrección funcionó.', 'Procedimiento escrito de cinco pasos.', 35],
   ['crear', 'Cazar los siete errores', 'Aplica tu método al programa entregado. Por cada error registra: línea, síntoma, causa real, corrección y cómo verificaste. No corrijas dos errores a la vez.', 'Bitácora de siete errores y programa corregido.', 75],
   ['evaluar', 'El que no da error', 'Verifica los resultados del programa corregido contra un cálculo manual con cinco notas. Si no coinciden, queda un error lógico. Explica por qué ese tipo de error es el más peligroso.', 'Verificación manual y explicación del error silencioso.', 45],
 ],
 'recursos' => [
   ['codigo', 'estadisticas_con_errores.py', 'Programa de partida con siete errores plantados.'],
   ['plantilla', 'Bitácora de depuración', 'Línea, síntoma, causa, corrección, verificación.'],
 ]],

['codigo' => 'VCP-8-07', 'titulo' => 'Manejo de errores y casos de prueba',
 'objeto' => 'el programa a prueba de errores',
 'resumen' => 'Anticipar lo que el usuario hará mal y responder con un mensaje útil en lugar de un mensaje de error.',
 'descripcion' => '<p>El estudiante toma un programa propio y lo hace resistente: try y except donde el usuario puede equivocarse, validación de rangos, mensajes que dicen qué hacer y no solo qué pasó. Aparece la distinción entre un error del programa y un error del usuario.</p><p>La prueba final es dura y divertida: dos compañeros intentan romper el programa durante cinco minutos. Cada rotura se documenta. El objetivo declarado de la actividad es que el programa sobreviva a un usuario hostil.</p>',
 'pregunta' => '¿Es culpa del usuario que mi programa falle cuando escribe algo inesperado?',
 'contexto' => 'Identidades y relaciones', 'concepto' => 'Sistemas',
 'perfil' => 'Solidario|Reflexivo', 'atl' => 'Pensamiento crítico|Colaboración',
 'objetivos' => 'Usar try y except con excepciones específicas|Validar rangos y formatos de entrada|Redactar mensajes de error accionables|Documentar un conjunto de pruebas de robustez',
 'entregables' => 'Programa endurecido con al menos seis validaciones|Registro de la prueba de rotura de cinco minutos|Tabla de mensajes de error antes y después',
 'lenguaje' => 'Python', 'dificultad' => 'intermedio', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "def pedir_entero(mensaje, minimo, maximo):\n    while True:\n        try:\n            v = int(input(mensaje))\n        except ValueError:\n            print(\"Escribe un numero entero, por ejemplo 12.\")\n            continue\n        # TODO: valida el rango y explica que rango se espera\n        return v",
 'fases' => [
   ['indagar', 'Qué escriben los usuarios reales', 'Da tu programa a tres personas sin instrucciones y anota literalmente todo lo que escribieron. Clasifica cada entrada inesperada por tipo.', 'Registro literal de entradas y su clasificación.', 45],
   ['desarrollar', 'Diseñar los mensajes', 'Para cada entrada inesperada redacta el mensaje que debería aparecer. Un buen mensaje dice qué pasó, por qué y qué hacer. Compáralo con el mensaje que da Python.', 'Tabla de seis mensajes propios frente al mensaje del lenguaje.', 45],
   ['crear', 'Endurecer el programa', 'Implementa las validaciones con excepciones específicas, nunca con except genérico. Cada validación debe tener su mensaje diseñado en la fase anterior.', 'Programa endurecido con seis validaciones activas.', 75],
   ['evaluar', 'Cinco minutos para romperlo', 'Dos compañeros intentan romper tu programa durante cinco minutos cada uno. Documenta cada rotura, corrige y vuelve a probar. Anota cuántas roturas sobrevivieron.', 'Registro de la prueba de rotura y correcciones aplicadas.', 45],
 ],
 'recursos' => [
   ['lectura', 'Excepciones específicas y por qué evitar except desnudo', 'Guía breve con ejemplos.'],
   ['plantilla', 'Registro de prueba de rotura', 'Entrada, resultado, corrección.'],
 ]],

['codigo' => 'VCP-8-08', 'titulo' => 'Analizador de textos literarios',
 'objeto' => 'el analizador de textos',
 'resumen' => 'Contar palabras, medir riqueza léxica y comparar dos obras, conectando Tecnología con Lengua y Literatura.',
 'descripcion' => '<p>El estudiante procesa dos textos completos de dominio público, cuenta frecuencias, calcula la riqueza léxica (palabras distintas sobre palabras totales) y compara los dos autores. Aparece la limpieza de texto: minúsculas, signos, tildes, palabras vacías.</p><p>El resultado se lleva a la clase de Lengua y se contrasta con la interpretación literaria. Con frecuencia los números confirman una intuición del docente de Literatura; a veces la contradicen, y esa contradicción es el mejor material de discusión que la actividad puede producir.</p>',
 'pregunta' => '¿Qué puede decir un conteo de palabras sobre un texto que la lectura no dice, y qué no puede decir nunca?',
 'contexto' => 'Expresión personal y cultural', 'concepto' => 'Relaciones',
 'perfil' => 'Indagador|Informado e instruido', 'atl' => 'Transferencia|Pensamiento crítico',
 'objetivos' => 'Normalizar texto para su análisis|Contar frecuencias con diccionarios|Calcular indicadores de riqueza léxica|Contrastar resultados cuantitativos con interpretación cualitativa',
 'entregables' => 'Archivo analizador.py|Tabla comparativa de dos obras|Comentario del docente de Lengua sobre los resultados',
 'lenguaje' => 'Python', 'dificultad' => 'intermedio', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "import unicodedata\n\nVACIAS = {\"el\", \"la\", \"de\", \"que\", \"y\", \"a\", \"en\", \"un\", \"por\", \"con\"}\n\ndef normalizar(texto):\n    texto = texto.lower()\n    # TODO: quita signos de puntuacion\n    # TODO: decide si quitas tildes y justifica la decision\n    return texto\n\n# TODO: frecuencias(texto), riqueza_lexica(texto), top(n)",
 'fases' => [
   ['indagar', 'Qué mide y qué no mide un conteo', 'Lee un fragmento de cada obra y escribe tu impresión antes de programar nada. Anota tres afirmaciones que crees que los números confirmarán.', 'Impresión de lectura y tres hipótesis a comprobar.', 45],
   ['desarrollar', 'Decisiones de normalización', 'Decide y justifica: quitar tildes o no, unir singular y plural o no, incluir palabras vacías o no. Cada decisión cambia el resultado, así que debe quedar registrada.', 'Documento de cuatro decisiones de normalización justificadas.', 45],
   ['crear', 'Programar el análisis', 'Implementa la normalización, el conteo, la riqueza léxica y el top de veinte palabras. Ejecuta sobre las dos obras y guarda los resultados.', 'Archivo analizador.py y resultados de las dos obras.', 85],
   ['evaluar', 'Contraste con la clase de Lengua', 'Presenta la tabla comparativa a tu docente de Lengua. Anota qué confirmó, qué contradijo tu hipótesis y qué te advirtió que los números no pueden mostrar.', 'Tabla comparativa y comentario registrado del docente.', 55],
 ],
 'recursos' => [
   ['dataset', 'Dos obras de dominio público', 'Textos completos en utf-8 listos para procesar.'],
   ['lectura', 'Palabras vacías y normalización', 'Por qué el resultado cambia según lo que se descarte.'],
 ]],

['codigo' => 'VCP-8-09', 'titulo' => 'Agente que resume noticias y verifica fuentes',
 'objeto' => 'el agente verificador',
 'resumen' => 'Construir un agente que resuma una noticia y, sobre todo, que declare qué no puede verificar.',
 'descripcion' => '<p>El estudiante configura un agente que resume noticias en tres frases y añade obligatoriamente una lista de afirmaciones que no pudo verificar. Luego contrasta ese resumen con la noticia original y cuenta cuántas afirmaciones del resumen aparecen realmente en la fuente.</p><p>La actividad expone el mecanismo de la desinformación asistida: un resumen fluido y convincente puede contener afirmaciones que la fuente nunca hizo. El estudiante mide esa tasa con sus propios datos, en lugar de recibirla como advertencia.</p>',
 'pregunta' => '¿Cómo distingo lo que el resumen dice de lo que la fuente realmente dijo?',
 'contexto' => 'Globalización y sustentabilidad', 'concepto' => 'Comunicación',
 'perfil' => 'Íntegro|Pensador|De mentalidad abierta', 'atl' => 'Alfabetización mediática|Pensamiento crítico',
 'objetivos' => 'Definir instrucciones que obliguen a declarar incertidumbre|Contrastar afirmación por afirmación con la fuente|Medir la tasa de afirmaciones no respaldadas|Declarar el uso de IA con evidencia adjunta',
 'entregables' => 'Ficha del agente con la regla de incertidumbre|Cinco noticias resumidas y contrastadas|Tabla con la tasa de afirmaciones no respaldadas',
 'lenguaje' => 'Lenguaje natural', 'dificultad' => 'intermedio', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "# Instruccion del agente (texto, no codigo)\n# 1. Resume la noticia en exactamente tres frases.\n# 2. Lista las afirmaciones que NO puedes verificar con el texto dado.\n# 3. Si el texto no menciona un dato, escribe: 'la fuente no lo indica'.\n# 4. Nunca agregues contexto que no este en la fuente.",
 'fases' => [
   ['indagar', 'Qué es una afirmación verificable', 'Toma una noticia y subraya cada afirmación. Clasifícalas en hecho comprobable, opinión y dato sin fuente. Cuenta cuántas hay de cada tipo.', 'Noticia anotada con la clasificación y el conteo.', 45],
   ['desarrollar', 'Instrucciones que obligan a dudar', 'Redacta la ficha del agente incluyendo la regla de declarar lo no verificable y la frase exacta que debe usar cuando falte un dato.', 'Ficha del agente con cuatro reglas y la frase obligatoria.', 40],
   ['crear', 'Resumir cinco noticias', 'Aplica el agente a cinco noticias. Guarda la fuente y el resumen. Marca en cada resumen las afirmaciones que puedes localizar literalmente en la fuente.', 'Cinco fuentes con sus resúmenes y las afirmaciones marcadas.', 70],
   ['evaluar', 'Medir la tasa de invención', 'Calcula el porcentaje de afirmaciones no respaldadas por noticia. Ajusta la ficha del agente y repite con dos noticias. Compara las dos tasas y concluye.', 'Tabla de tasas antes y después del ajuste, con conclusión.', 50],
 ],
 'recursos' => [
   ['plantilla', 'Matriz de contraste afirmación-fuente', 'Afirmación, aparece en la fuente, literal o inferida.'],
   ['lectura', 'Declaración de uso de IA', 'Formato de declaración exigido en las entregas del colegio.'],
 ]],

['codigo' => 'VCP-8-10', 'titulo' => 'Panel web con los datos del colegio',
 'objeto' => 'el panel web de datos',
 'resumen' => 'Publicar los datos analizados en una página que los carga desde un archivo JSON y los muestra sin recargar.',
 'descripcion' => '<p>El estudiante exporta sus datos a JSON desde Python y construye una página web que los carga con fetch y los presenta en tablas y una gráfica sencilla dibujada con HTML y CSS. Es el primer puente entre el análisis y la publicación.</p><p>El requisito clave es que la página siga siendo comprensible si los datos no cargan: un mensaje claro en vez de una pantalla en blanco. Esa exigencia introduce el concepto de degradación elegante, que se retomará en 10.º con accesibilidad.</p>',
 'pregunta' => '¿Cómo entrego mis resultados para que cualquiera los consulte sin instalar nada?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Comunicación',
 'perfil' => 'Buen comunicador|Pensador', 'atl' => 'Comunicación|Transferencia',
 'objetivos' => 'Exportar datos a JSON desde Python|Cargar datos con fetch en el navegador|Construir tablas dinámicas con JavaScript|Manejar el caso de error de carga',
 'entregables' => 'Archivo datos.json generado desde Python|Página panel.html con tabla y gráfica|Demostración del comportamiento cuando el JSON no carga',
 'lenguaje' => 'Python, JavaScript, HTML', 'dificultad' => 'avanzado', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "// panel.js\nfetch(\"datos.json\")\n  .then(function (r) { return r.json(); })\n  .then(function (datos) {\n    // TODO: construye las filas de la tabla\n  })\n  .catch(function () {\n    // TODO: muestra un mensaje claro al usuario\n  });",
 'fases' => [
   ['indagar', 'Paneles que se entienden solos', 'Analiza dos paneles de datos públicos. Anota cuánto tardaste en responder una pregunta concreta con cada uno y qué elemento te ayudó más.', 'Análisis de dos paneles con tiempo de respuesta medido.', 45],
   ['desarrollar', 'Estructura del JSON y de la página', 'Diseña la estructura del JSON (qué claves, qué tipos) y el boceto de la página. Define qué se muestra si el archivo no carga.', 'Esquema del JSON, boceto de la página y plan de error.', 45],
   ['crear', 'Exportar, cargar y mostrar', 'Genera el JSON desde tu programa de Python. Construye la página con la tabla y una gráfica de barras hecha con divs. Implementa el mensaje de error.', 'datos.json, panel.html y panel.js funcionando.', 95],
   ['evaluar', 'Prueba de degradación', 'Renombra el archivo JSON y comprueba qué ve el usuario. Pide a dos personas que respondan una pregunta usando tu panel y cronometra. Ajusta lo que las haya demorado.', 'Captura del comportamiento sin datos y registro de dos pruebas de uso.', 55],
 ],
 'recursos' => [
   ['lectura', 'JSON y fetch en cinco minutos', 'Guía con el manejo del error incluido.'],
   ['plantilla', 'Gráfica de barras con CSS', 'Fragmento reutilizable sin bibliotecas.'],
 ]],

];
