<?php
/**
 * Banco de actividades · Nivel N12 (12.º · DP 2 · Informática NS, ITGS y Monografía)
 */

declare(strict_types=1);

return [

['codigo' => 'VCP-12-01', 'titulo' => 'Diseño de la solución: diagramas y registro de desarrollo',
 'objeto' => 'el diseño de la solución final',
 'resumen' => 'Producir la descripción general de la solución que exige el criterio B: diagramas, estructuras de datos y registro acordado con el cliente.',
 'descripcion' => '<p>El estudiante consolida el diseño de su evaluación interna: diagrama de estructura del sistema, diagramas de flujo de los procesos principales, definición de las estructuras de datos y el prototipo de la interfaz, todo revisado por el cliente.</p><p>El registro de desarrollo se inicia aquí y no al final. La actividad exige que la primera entrada del registro sea anterior a la primera línea de código de la versión definitiva, porque un registro reconstruido a posteriori es detectable y no cumple el criterio.</p>',
 'pregunta' => '¿Puede otra persona entender mi solución completa sin que yo se la explique?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Buen comunicador|Reflexivo|Íntegro', 'atl' => 'Organización|Comunicación',
 'objetivos' => 'Producir diagramas de estructura y de flujo|Definir estructuras de datos con justificación|Acordar el registro de desarrollo con el cliente|Establecer la trazabilidad entre diseño y criterios de éxito',
 'entregables' => 'Diagrama de estructura del sistema|Diagramas de flujo de los tres procesos principales|Definición de estructuras de datos|Registro de desarrollo iniciado y firmado',
 'lenguaje' => 'Documentación', 'dificultad' => 'avanzado', 'sesiones' => 5, 'horas' => 6.0, 'ia' => 1,
 'codigo_inicial' => "// Entrada del registro de desarrollo\n// Fecha | Actividad realizada | Decision tomada | Justificacion | Evidencia\n// La primera entrada debe ser anterior a la primera linea de codigo definitivo.",
 'fases' => [
   ['indagar', 'Revisar el diseño previo con el cliente', 'Presenta al cliente el diseño elaborado en 11.º. Registra cada cambio que solicite y verifica que los criterios de éxito siguen vigentes.', 'Acta de revisión con los cambios solicitados y criterios confirmados.', 60],
   ['desarrollar', 'Producir la documentación de diseño', 'Elabora el diagrama de estructura, los diagramas de flujo de los tres procesos principales y la definición de las estructuras de datos con la justificación de cada elección.', 'Los cuatro documentos de diseño completos.', 120],
   ['crear', 'Prototipo de interfaz y registro', 'Construye el prototipo de todas las pantallas principales y ábrelo con el cliente. Inicia el registro de desarrollo con las primeras cinco entradas fechadas.', 'Prototipo revisado por el cliente y registro con cinco entradas.', 100],
   ['evaluar', 'Prueba de comprensión por terceros', 'Entrega el paquete de diseño a un compañero que no conozca el proyecto y pídele que explique el flujo principal. Corrige todo lo que no logró explicar.', 'Registro de la prueba de comprensión y diseño corregido.', 55],
 ],
 'recursos' => [
   ['plantilla', 'Registro de desarrollo', 'Formato exigido con fecha, decisión, justificación y evidencia.'],
   ['plantilla', 'Diagrama de estructura del sistema', 'Formato con componentes y responsabilidades.'],
 ]],

['codigo' => 'VCP-12-02', 'titulo' => 'Desarrollo: técnicas complejas y su justificación',
 'objeto' => 'el producto de la evaluación interna',
 'resumen' => 'Construir el producto empleando técnicas que merezcan explicación, y documentar por qué cada una fue la elección correcta.',
 'descripcion' => '<p>El criterio C premia la complejidad justificada, no la extensión. El estudiante identifica las tres o cuatro técnicas que sostienen su solución —una estructura de datos no trivial, un algoritmo propio, una interacción con un servicio externo— y las desarrolla con documentación que explique su funcionamiento.</p><p>La actividad incluye una revisión intermedia donde el estudiante debe defender oralmente por qué cada técnica es necesaria. Las técnicas que no resisten esa defensa se eliminan del producto, porque la complejidad decorativa perjudica la evaluación.</p>',
 'pregunta' => '¿Esta técnica está aquí porque el problema la exige o porque quiero aparentar complejidad?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Pensador|Íntegro|Audaz', 'atl' => 'Pensamiento crítico|Autogestión',
 'objetivos' => 'Seleccionar técnicas apropiadas al problema|Implementar algoritmos y estructuras no triviales|Documentar el funcionamiento con fragmentos de código|Justificar cada decisión técnica frente a alternativas',
 'entregables' => 'Producto con al menos tres técnicas documentadas|Explicación técnica de cada una con su fragmento de código|Registro de desarrollo actualizado',
 'lenguaje' => 'Java, Python o PHP', 'dificultad' => 'avanzado', 'sesiones' => 8, 'horas' => 10.0, 'ia' => 1,
 'codigo_inicial' => "// Ficha de tecnica (una por cada tecnica documentada)\n// Nombre de la tecnica:\n// Problema que resuelve:\n// Alternativas consideradas y por que se descartaron:\n// Fragmento de codigo representativo:\n// Como se comprueba que funciona:",
 'fases' => [
   ['indagar', 'Identificar las técnicas necesarias', 'Analiza los criterios de éxito y determina qué parte del problema exige una técnica no trivial. Investiga al menos dos alternativas para cada una.', 'Análisis con tres técnicas identificadas y dos alternativas por técnica.', 70],
   ['desarrollar', 'Justificar antes de implementar', 'Redacta la ficha de cada técnica con su justificación frente a las alternativas. Somete las fichas a revisión del docente antes de programar.', 'Tres fichas de técnica revisadas y aprobadas.', 60],
   ['crear', 'Implementar el producto', 'Desarrolla la solución completa. Documenta cada técnica con su fragmento representativo y actualiza el registro de desarrollo en cada sesión de trabajo.', 'Producto funcional con las técnicas documentadas y registro al día.', 260],
   ['evaluar', 'Defensa de la complejidad', 'Defiende oralmente cada técnica ante el docente: por qué era necesaria y qué pasaría sin ella. Elimina o simplifica lo que no resista la defensa.', 'Acta de la defensa y ajustes aplicados al producto.', 60],
 ],
 'recursos' => [
   ['plantilla', 'Ficha de técnica empleada', 'Problema, alternativas, justificación, evidencia.'],
   ['lectura', 'Qué cuenta como técnica compleja', 'Ejemplos de los descriptores altos del criterio C.'],
 ]],

['codigo' => 'VCP-12-03', 'titulo' => 'Pruebas, casos límite y depuración sistemática',
 'objeto' => 'el plan de pruebas del producto',
 'resumen' => 'Diseñar un plan de pruebas que cubra los casos normales, los de error y los límites, y ejecutarlo con evidencia.',
 'descripcion' => '<p>El estudiante construye un plan de pruebas derivado directamente de sus criterios de éxito, con casos normales, casos de error y casos límite. Cada caso indica entrada, resultado esperado, resultado obtenido y evidencia.</p><p>La exigencia distintiva es la prueba con datos hostiles: entradas vacías, valores extremos, caracteres especiales, operaciones simultáneas. Los estudiantes descubren que la mayoría de sus fallos aparecen en el límite, no en el centro.</p>',
 'pregunta' => '¿Qué entrada rompería mi programa y por qué no la he probado todavía?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Íntegro|Reflexivo', 'atl' => 'Organización|Pensamiento crítico',
 'objetivos' => 'Derivar casos de prueba de los criterios de éxito|Diseñar casos límite y de error|Ejecutar y registrar con evidencia|Depurar de forma sistemática y documentada',
 'entregables' => 'Plan con al menos veinticinco casos de prueba|Registro de ejecución con evidencia|Bitácora de los cinco fallos más graves y su corrección',
 'lenguaje' => 'Java, Python o PHP', 'dificultad' => 'avanzado', 'sesiones' => 5, 'horas' => 6.0, 'ia' => 1,
 'codigo_inicial' => "// Caso de prueba\n// ID | Criterio de exito que verifica | Entrada | Esperado | Obtenido | Evidencia\n// Tipos obligatorios: normal, error, limite\n// Limites tipicos: vacio, cero, negativo, maximo, un caracter, texto muy largo",
 'fases' => [
   ['indagar', 'Dónde fallan los programas', 'Revisa el historial de errores de tu propio proyecto y clasifícalos por tipo. Determina qué proporción apareció en casos límite frente a casos normales.', 'Clasificación del historial de errores con la proporción calculada.', 45],
   ['desarrollar', 'Diseñar el plan de pruebas', 'Deriva de cada criterio de éxito al menos tres casos: uno normal, uno de error y uno límite. Define la evidencia que recogerás de cada ejecución.', 'Plan con veinticinco casos trazados a los criterios de éxito.', 70],
   ['crear', 'Ejecutar y depurar', 'Ejecuta todos los casos y registra el resultado con evidencia. Por cada fallo aplica el método de depuración: reproducir, aislar, corregir, verificar y volver a ejecutar todo el plan.', 'Registro completo de ejecución y bitácora de depuración.', 120],
   ['evaluar', 'Prueba hostil por un tercero', 'Un compañero intenta romper tu producto durante quince minutos con entradas que tú no previste. Documenta cada rotura y decide cuáles corriges antes de la entrega.', 'Registro de la prueba hostil y decisiones de corrección justificadas.', 60],
 ],
 'recursos' => [
   ['plantilla', 'Plan de pruebas trazado a criterios', 'Formato con tipo de caso y evidencia.'],
   ['lectura', 'Casos límite: catálogo de sospechosos habituales', 'Quince entradas que rompen la mayoría de programas.'],
 ]],

['codigo' => 'VCP-12-04', 'titulo' => 'Optimización y complejidad del producto final',
 'objeto' => 'la optimización del producto',
 'resumen' => 'Encontrar el cuello de botella real con mediciones, optimizarlo y demostrar la mejora sin romper la funcionalidad.',
 'descripcion' => '<p>El estudiante mide el rendimiento de su producto con datos de tamaño realista, identifica el cuello de botella verdadero —que casi nunca es el que suponía— y aplica una optimización justificada. Toda mejora debe demostrarse con mediciones antes y después.</p><p>La regla profesional se aplica sin excepciones: no se optimiza sin medir, y toda optimización debe pasar el plan de pruebas completo. Una mejora que rompe un caso de prueba se revierte.</p>',
 'pregunta' => '¿Dónde está realmente el problema de rendimiento, y cómo lo demuestro?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Relaciones',
 'perfil' => 'Pensador|Íntegro', 'atl' => 'Pensamiento crítico|Reflexión',
 'objetivos' => 'Medir el rendimiento con datos realistas|Identificar el cuello de botella con evidencia|Aplicar una optimización justificada|Verificar que la funcionalidad se conserva',
 'entregables' => 'Mediciones antes de optimizar|Análisis del cuello de botella|Optimización aplicada con mediciones posteriores|Plan de pruebas ejecutado nuevamente',
 'lenguaje' => 'Java, Python o PHP', 'dificultad' => 'avanzado', 'sesiones' => 4, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "// Protocolo de medicion\n// 1. Genera datos de tamano realista (n = 100, 1000, 10000)\n// 2. Mide cada operacion principal por separado, cinco repeticiones\n// 3. Identifica la operacion que domina el tiempo total\n// 4. Optimiza solo esa\n// 5. Vuelve a medir y ejecuta el plan de pruebas completo",
 'fases' => [
   ['indagar', 'Predecir y luego medir', 'Predice por escrito cuál será la operación más lenta de tu producto. Después mide todas las operaciones principales con datos de tres tamaños.', 'Predicción escrita y tabla de mediciones de todas las operaciones.', 55],
   ['desarrollar', 'Analizar el cuello de botella', 'Determina con los datos cuál operación domina el tiempo total. Analiza su complejidad y propone dos optimizaciones posibles con su costo estimado.', 'Análisis del cuello de botella y dos propuestas de optimización.', 50],
   ['crear', 'Optimizar y verificar', 'Aplica la optimización elegida. Vuelve a medir con los tres tamaños y ejecuta el plan de pruebas completo para comprobar que nada se rompió.', 'Optimización aplicada, mediciones posteriores y plan de pruebas superado.', 100],
   ['evaluar', 'Cuantificar la mejora', 'Compara las mediciones antes y después, calcula el porcentaje de mejora y evalúa si compensó la complejidad añadida al código. Contrasta con tu predicción inicial.', 'Informe de mejora con la evaluación del costo en complejidad.', 55],
 ],
 'recursos' => [
   ['lectura', 'Medir antes de optimizar', 'Por qué la intuición sobre rendimiento suele fallar.'],
 ]],

['codigo' => 'VCP-12-05', 'titulo' => 'Documentación técnica y video del producto',
 'objeto' => 'la documentación y el video',
 'resumen' => 'Producir el video de demostración del criterio D y la documentación técnica que acompaña la entrega.',
 'descripcion' => '<p>El video no es una presentación: es la prueba de que el producto funciona. El estudiante planifica un guion que recorre cada criterio de éxito, graba la demostración sin cortes engañosos y la acompaña de la documentación técnica.</p><p>El error habitual es grabar el producto en su mejor día. La actividad exige mostrar también el manejo de errores: qué ocurre cuando el usuario se equivoca, porque eso demuestra funcionalidad completa mejor que cualquier recorrido perfecto.</p>',
 'pregunta' => '¿Cómo demuestro en siete minutos que mi solución hace lo que prometí?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Comunicación',
 'perfil' => 'Buen comunicador|Íntegro', 'atl' => 'Comunicación|Organización',
 'objetivos' => 'Planificar un guion trazado a los criterios de éxito|Grabar una demostración honesta y completa|Documentar la instalación y el uso|Mostrar el comportamiento ante errores del usuario',
 'entregables' => 'Guion del video trazado a los criterios|Video de demostración|Documentación técnica y manual de usuario',
 'lenguaje' => 'Documentación', 'dificultad' => 'avanzado', 'sesiones' => 4, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "// Guion del video\n// 00:00 Contexto y cliente (30 s)\n// 00:30 Criterio de exito 1: como se demuestra\n// ...\n// Ultimos 60 s: manejo de errores del usuario\n// Regla: sin cortes que oculten esperas o fallos",
 'fases' => [
   ['indagar', 'Qué hace bueno a un video de demostración', 'Analiza dos videos de demostración de software. Anota qué te convenció y qué te generó sospecha, en particular los cortes y las omisiones.', 'Análisis de dos videos con los criterios de credibilidad.', 40],
   ['desarrollar', 'Escribir el guion trazado', 'Escribe el guion con tiempos, asegurando que cada criterio de éxito tenga su momento de demostración. Reserva el último minuto para el manejo de errores.', 'Guion con tiempos y trazabilidad a todos los criterios.', 50],
   ['crear', 'Grabar y documentar', 'Graba la demostración siguiendo el guion, sin cortes que oculten esperas o fallos. Redacta la documentación técnica y el manual de usuario.', 'Video terminado y documentación completa.', 100],
   ['evaluar', 'Revisión por el cliente', 'Muestra el video al cliente y pregúntale si reconoce su necesidad resuelta. Registra sus observaciones y corrige el video o la documentación si algo no quedó demostrado.', 'Observaciones del cliente y versión final corregida.', 50],
 ],
 'recursos' => [
   ['plantilla', 'Guion de video trazado a criterios', 'Formato con tiempos y criterio demostrado.'],
   ['plantilla', 'Estructura de documentación técnica', 'Instalación, configuración, uso, solución de problemas.'],
 ]],

['codigo' => 'VCP-12-06', 'titulo' => 'Evaluación final y recomendaciones de mejora',
 'objeto' => 'la evaluación de la solución',
 'resumen' => 'Evaluar la solución contra cada criterio de éxito con evidencia del cliente y proponer mejoras realistas y justificadas.',
 'descripcion' => '<p>El estudiante recoge retroalimentación estructurada del cliente después de un periodo de uso real, evalúa cada criterio de éxito con evidencia y redacta las recomendaciones de mejora que exige el criterio E.</p><p>La honestidad se evalúa: un informe que declara todos los criterios cumplidos sin evidencia obtiene menos que uno que reconoce un incumplimiento y lo analiza bien. La actividad entrena explícitamente esa lectura crítica del propio trabajo.</p>',
 'pregunta' => '¿Qué no logré, por qué, y qué haría distinto si empezara de nuevo?',
 'contexto' => 'Equidad y desarrollo', 'concepto' => 'Relaciones',
 'perfil' => 'Reflexivo|Íntegro|De mentalidad abierta', 'atl' => 'Reflexión|Pensamiento crítico',
 'objetivos' => 'Diseñar un instrumento de retroalimentación del cliente|Evaluar cada criterio de éxito con evidencia|Reconocer y analizar los incumplimientos|Proponer mejoras viables y justificadas',
 'entregables' => 'Instrumento de retroalimentación aplicado|Evaluación de todos los criterios con evidencia|Tres recomendaciones de mejora justificadas',
 'lenguaje' => 'Documentación', 'dificultad' => 'avanzado', 'sesiones' => 4, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "// Evaluacion por criterio\n// Criterio de exito | Evidencia | Cumplido / Parcial / No cumplido | Analisis\n// Las mejoras propuestas deben ser: viables, especificas y justificadas\n// con la retroalimentacion recogida, no con opiniones propias.",
 'fases' => [
   ['indagar', 'Recoger retroalimentación estructurada', 'Diseña y aplica un instrumento al cliente después de un periodo de uso real. Incluye preguntas sobre lo que no funcionó, no solo sobre la satisfacción.', 'Instrumento aplicado con las respuestas registradas.', 60],
   ['desarrollar', 'Evaluar criterio por criterio', 'Evalúa cada criterio de éxito como cumplido, parcial o no cumplido, citando la evidencia concreta que sustenta cada juicio.', 'Tabla de evaluación completa con evidencia por criterio.', 60],
   ['crear', 'Analizar los incumplimientos', 'Para cada criterio no cumplido o parcial, analiza la causa: decisión de diseño, límite técnico, tiempo o alcance mal estimado. Sé específico.', 'Análisis de causas de cada incumplimiento.', 70],
   ['evaluar', 'Recomendaciones de mejora', 'Redacta tres recomendaciones de mejora derivadas de la retroalimentación del cliente y del análisis de causas. Cada una debe indicar qué resolvería y qué costaría.', 'Tres recomendaciones justificadas con su costo estimado.', 60],
 ],
 'recursos' => [
   ['plantilla', 'Instrumento de retroalimentación del cliente', 'Preguntas que revelan problemas reales.'],
   ['plantilla', 'Tabla de evaluación de criterios', 'Criterio, evidencia, juicio, análisis.'],
 ]],

['codigo' => 'VCP-12-07', 'titulo' => 'ITGS: estudio de caso de impacto social',
 'objeto' => 'el estudio de caso de impacto',
 'resumen' => 'Analizar un caso real de tecnología en la sociedad identificando partes interesadas, impactos y soluciones posibles.',
 'descripcion' => '<p>El estudiante analiza un caso real —vigilancia en el espacio público, algoritmos de contratación, automatización de un servicio— con el marco de ITGS: partes interesadas, escenario social, impactos positivos y negativos, y soluciones planteadas.</p><p>La exigencia es equilibrio: el análisis debe presentar la perspectiva de al menos tres partes interesadas con intereses en conflicto, incluida la de quien defiende la tecnología. Un análisis unilateral no cumple, por convincente que sea.</p>',
 'pregunta' => '¿Quién gana, quién pierde y quién decide cuando se introduce una tecnología?',
 'contexto' => 'Globalización y sustentabilidad', 'concepto' => 'Relaciones',
 'perfil' => 'De mentalidad abierta|Informado e instruido|Solidario', 'atl' => 'Pensamiento crítico|Alfabetización informacional|Comunicación',
 'objetivos' => 'Identificar partes interesadas y sus intereses en conflicto|Analizar impactos positivos y negativos con evidencia|Evaluar soluciones propuestas y sus límites|Sostener un análisis equilibrado con fuentes diversas',
 'entregables' => 'Análisis del caso con al menos seis fuentes|Mapa de tres partes interesadas con sus intereses|Evaluación de dos soluciones propuestas',
 'lenguaje' => 'Documentación', 'dificultad' => 'avanzado', 'sesiones' => 5, 'horas' => 6.0, 'ia' => 1,
 'codigo_inicial' => "// Marco de analisis ITGS\n// 1. Escenario y sistema de TI involucrado\n// 2. Partes interesadas y sus intereses (minimo tres, en conflicto)\n// 3. Impactos: sociales, eticos, economicos, ambientales\n// 4. Soluciones propuestas y sus limitaciones\n// 5. Evaluacion equilibrada con evidencia",
 'fases' => [
   ['indagar', 'Reunir fuentes diversas', 'Selecciona el caso y reúne seis fuentes que incluyan al menos una favorable a la tecnología y una crítica. Evalúa la credibilidad y el interés de cada fuente.', 'Seis fuentes evaluadas con su posición y credibilidad.', 70],
   ['desarrollar', 'Mapa de partes interesadas', 'Identifica tres partes interesadas con intereses en conflicto. Para cada una determina qué gana, qué pierde y qué poder de decisión tiene.', 'Mapa de partes interesadas con intereses y poder.', 60],
   ['crear', 'Redactar el análisis', 'Escribe el análisis siguiendo el marco: sistema, partes interesadas, impactos por categoría y soluciones propuestas. Toda afirmación con su fuente.', 'Análisis completo con las fuentes citadas correctamente.', 110],
   ['evaluar', 'Prueba de equilibrio', 'Pide a un compañero que identifique tu posición leyendo solo el análisis. Si la detecta fácilmente, revisa dónde perdiste el equilibrio y corrige.', 'Registro de la prueba de equilibrio y correcciones aplicadas.', 55],
 ],
 'recursos' => [
   ['plantilla', 'Marco de análisis ITGS', 'Estructura de cinco secciones con preguntas guía.'],
   ['plantilla', 'Evaluación de credibilidad de fuentes', 'Autoría, interés, evidencia, fecha.'],
 ]],

['codigo' => 'VCP-12-08', 'titulo' => 'Concurrencia y sistemas distribuidos',
 'objeto' => 'el programa concurrente',
 'resumen' => 'Programar tareas concurrentes, provocar una condición de carrera y resolverla con sincronización.',
 'descripcion' => '<p>Contenido de Nivel Superior. El estudiante escribe un programa con varios hilos que comparten un recurso, provoca deliberadamente una condición de carrera y comprueba que el resultado varía entre ejecuciones aunque el código no cambie.</p><p>Después aplica sincronización y verifica que el resultado se vuelve determinista, midiendo el costo en rendimiento. La actividad cierra con el problema de los interbloqueos: el estudiante provoca uno y explica las cuatro condiciones que lo hacen posible.</p>',
 'pregunta' => '¿Por qué el mismo programa da resultados distintos cada vez que lo ejecuto?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Pensador|Indagador', 'atl' => 'Pensamiento crítico|Transferencia',
 'objetivos' => 'Crear y coordinar hilos de ejecución|Provocar y explicar una condición de carrera|Aplicar sincronización y medir su costo|Identificar las condiciones de un interbloqueo',
 'entregables' => 'Programa con condición de carrera demostrada en veinte ejecuciones|Versión sincronizada con resultado determinista|Análisis del interbloqueo provocado',
 'lenguaje' => 'Java', 'dificultad' => 'avanzado', 'sesiones' => 5, 'horas' => 6.0, 'ia' => 1,
 'codigo_inicial' => "public class Contador {\n    private int valor = 0;\n\n    public void incrementar() {\n        valor++;   // no es atomico: leer, sumar, escribir\n    }\n\n    public int getValor() { return valor; }\n}\n\n// TODO: lanza 10 hilos que incrementen 1000 veces cada uno\n// TODO: ejecuta 20 veces y registra los resultados\n// TODO: sincroniza y vuelve a medir",
 'fases' => [
   ['indagar', 'Fallos de concurrencia reales', 'Investiga un fallo documentado causado por una condición de carrera. Determina qué recurso se compartía y qué consecuencia tuvo.', 'Estudio de un caso con el mecanismo técnico identificado.', 50],
   ['desarrollar', 'Diseñar el experimento', 'Diseña el programa que provocará la condición de carrera y el protocolo de medición: cuántos hilos, cuántas repeticiones, qué resultado esperarías si todo fuera correcto.', 'Diseño del experimento con el resultado teórico esperado.', 45],
   ['crear', 'Provocar, sincronizar y medir', 'Ejecuta la versión sin sincronizar veinte veces y registra los resultados. Aplica sincronización, repite y mide el costo en tiempo de las dos versiones.', 'Cuarenta ejecuciones registradas y comparación de rendimiento.', 105],
   ['evaluar', 'Provocar un interbloqueo', 'Escribe deliberadamente un interbloqueo con dos recursos y dos hilos. Explica las cuatro condiciones necesarias y cómo romper una de ellas.', 'Interbloqueo reproducible y explicación de las cuatro condiciones.', 60],
 ],
 'recursos' => [
   ['lectura', 'Condiciones de carrera e interbloqueos', 'Las cuatro condiciones de Coffman con ejemplos.'],
 ]],

['codigo' => 'VCP-12-09', 'titulo' => 'Monografía de Informática: pregunta y metodología',
 'objeto' => 'la monografía de Informática',
 'resumen' => 'Formular una pregunta de investigación acotada y defendible, y diseñar la metodología que permite responderla.',
 'descripcion' => '<p>La monografía se gana o se pierde en la pregunta. El estudiante formula una pregunta de investigación con alcance viable, la contrasta con la disponibilidad de fuentes y diseña la metodología: qué comparará, con qué criterios y con qué evidencia.</p><p>La actividad exige descartar por escrito al menos dos preguntas anteriores explicando por qué no funcionaban: demasiado amplias, sin fuentes suficientes o sin posibilidad de análisis propio. Ese descarte documentado es parte de la evaluación.</p>',
 'pregunta' => '¿Es esta una pregunta que puedo responder con evidencia en cuatro mil palabras?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Relaciones',
 'perfil' => 'Indagador|Pensador|Íntegro', 'atl' => 'Alfabetización informacional|Autogestión|Pensamiento crítico',
 'objetivos' => 'Formular una pregunta de investigación acotada|Evaluar la viabilidad según las fuentes disponibles|Diseñar una metodología de comparación con criterios|Planificar la investigación con hitos verificables',
 'entregables' => 'Dos preguntas descartadas con su justificación|Pregunta definitiva y su justificación|Metodología con criterios de comparación|Plan de trabajo con hitos y bibliografía inicial de diez fuentes',
 'lenguaje' => 'Documentación', 'dificultad' => 'avanzado', 'sesiones' => 5, 'horas' => 6.0, 'ia' => 1,
 'codigo_inicial' => "// Prueba de viabilidad de la pregunta\n// 1. Puedo responderla con evidencia? Que evidencia exactamente?\n// 2. Existen al menos ocho fuentes solidas?\n// 3. Hay analisis propio o solo resumen de lo que otros dicen?\n// 4. Cabe en 4000 palabras sin quedar superficial?\n// Si alguna respuesta es no, la pregunta se descarta.",
 'fases' => [
   ['indagar', 'Explorar y descartar', 'Formula tres preguntas candidatas y aplica la prueba de viabilidad a cada una. Descarta dos documentando exactamente por qué fallaron.', 'Tres preguntas evaluadas y dos descartes justificados.', 70],
   ['desarrollar', 'Acotar y diseñar la metodología', 'Refina la pregunta definitiva. Define qué compararás, con qué criterios y qué evidencia recogerás. La metodología debe permitir análisis propio, no solo revisión bibliográfica.', 'Pregunta definitiva y metodología con criterios explícitos.', 70],
   ['crear', 'Bibliografía inicial y plan', 'Reúne diez fuentes evaluadas por credibilidad y pertinencia. Elabora el plan de trabajo con hitos verificables hasta la entrega final.', 'Bibliografía de diez fuentes evaluadas y cronograma con hitos.', 90],
   ['evaluar', 'Defensa de la pregunta', 'Presenta la pregunta y la metodología al supervisor. Registra sus objeciones y ajusta. Verifica que la pregunta sigue siendo respondible tras los ajustes.', 'Acta de la reunión de supervisión y pregunta ajustada.', 50],
 ],
 'recursos' => [
   ['plantilla', 'Prueba de viabilidad de la pregunta', 'Cuatro comprobaciones antes de comprometerse.'],
   ['plantilla', 'Registro de reuniones de supervisión', 'Formato exigido para la monografía.'],
 ]],

['codigo' => 'VCP-12-10', 'titulo' => 'Portafolio final y sustentación',
 'objeto' => 'el portafolio de egreso',
 'resumen' => 'Proyecto insignia de 12.º: reunir la trayectoria completa de siete años en un portafolio y sustentarla ante un panel.',
 'descripcion' => '<p>El estudiante reúne su trayectoria desde 6.º: los proyectos que marcaron cada nivel, la evolución de su código y de su forma de documentar, y las decisiones que cambiaron su manera de trabajar. El portafolio no es una galería: es un argumento sobre su propio aprendizaje.</p><p>La sustentación ante un panel —docentes y, si es posible, alguien externo— exige defender una tesis sobre el propio desarrollo con evidencia del portafolio. Es el cierre del plan de aula y la mejor preparación para una entrevista universitaria.</p>',
 'pregunta' => '¿Qué sé hacer hoy que no sabía en sexto, y qué evidencia lo demuestra?',
 'contexto' => 'Identidades y relaciones', 'concepto' => 'Comunicación',
 'perfil' => 'Reflexivo|Buen comunicador|Íntegro|Equilibrado', 'atl' => 'Reflexión|Comunicación|Organización',
 'objetivos' => 'Seleccionar evidencia significativa de siete años|Argumentar una tesis sobre el propio desarrollo|Comunicar trabajo técnico a una audiencia mixta|Responder preguntas con evidencia y honestidad',
 'entregables' => 'Portafolio digital con al menos ocho piezas comentadas|Tesis sobre el propio desarrollo|Sustentación de quince minutos ante un panel',
 'lenguaje' => 'Elegido por el estudiante', 'dificultad' => 'avanzado', 'sesiones' => 6, 'horas' => 8.0, 'ia' => 1,
 'codigo_inicial' => "// Ficha de pieza del portafolio\n// Proyecto y ano:\n// Que sabia hacer antes de este proyecto:\n// Que aprendi a hacer con el:\n// Que haria distinto hoy y por que:\n// Evidencia que lo demuestra (codigo, bitacora, evaluacion):",
 'fases' => [
   ['indagar', 'Revisar la trayectoria completa', 'Recorre tus proyectos desde 6.º. Selecciona ocho piezas que muestren un cambio real en tu forma de trabajar, no necesariamente las mejores notas.', 'Selección de ocho piezas con la justificación de cada elección.', 80],
   ['desarrollar', 'Formular la tesis', 'Escribe en una frase qué cambió en ti como diseñador de soluciones. Verifica que cada una de las ocho piezas aporte evidencia a esa tesis; sustituye las que no lo hagan.', 'Tesis formulada y mapa de evidencia por pieza.', 60],
   ['crear', 'Construir el portafolio', 'Publica el portafolio con las ocho piezas comentadas. Cada comentario responde qué sabías antes, qué aprendiste y qué harías distinto hoy.', 'Portafolio publicado con las ocho fichas completas.', 130],
   ['evaluar', 'Sustentación ante el panel', 'Defiende tu tesis ante el panel durante quince minutos con preguntas. Registra las preguntas que no supiste responder y qué te revelan sobre tus vacíos.', 'Sustentación realizada y reflexión sobre las preguntas del panel.', 70],
 ],
 'recursos' => [
   ['plantilla', 'Ficha de pieza de portafolio', 'Antes, aprendizaje, mirada actual, evidencia.'],
   ['plantilla', 'Rúbrica de sustentación', 'Claridad, evidencia, profundidad técnica, respuesta a preguntas.'],
 ]],

];
