<?php
/**
 * Banco de actividades · Nivel N7 (7.º · PAI 2 · Diseño)
 */

declare(strict_types=1);

return [

['codigo' => 'VCP-7-01', 'titulo' => 'Encuesta del descanso: recoger y contar datos',
 'objeto' => 'el analizador de la encuesta',
 'resumen' => 'Diseñar una encuesta corta, aplicarla al curso y programar el conteo automático de las respuestas.',
 'descripcion' => '<p>El estudiante diseña cinco preguntas de opción múltiple sobre el uso del descanso, las aplica a veinte compañeros y programa un contador que produce el resumen. La actividad enseña que los datos no son números que caen del cielo: alguien los define, alguien los recoge y en ese proceso se cometen errores.</p><p>Al comparar los resultados de dos estudiantes que preguntaron lo mismo con palabras distintas, el curso descubre que la redacción de una pregunta cambia la respuesta. Es la primera lección de alfabetización mediática del nivel.</p>',
 'pregunta' => '¿Los datos hablan por si solos, o dependen de como pregunté?',
 'contexto' => 'Identidades y relaciones', 'concepto' => 'Relaciones',
 'perfil' => 'Indagador|Íntegro', 'atl' => 'Alfabetización informacional|Pensamiento crítico',
 'objetivos' => 'Diseñar preguntas cerradas sin sesgo|Guardar respuestas en listas|Contar ocurrencias con un ciclo|Presentar un resumen legible de los resultados',
 'entregables' => 'Cuestionario de cinco preguntas|Archivo encuesta.py con el conteo|Resumen de resultados y una conclusión sobre el sesgo de una pregunta',
 'lenguaje' => 'Python', 'dificultad' => 'inicial', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "respuestas = [\"futbol\", \"charlar\", \"celular\", \"futbol\", \"leer\"]\n\nconteo = {}\nfor r in respuestas:\n    # TODO: suma uno al conteo de r\n    pass\n\n# TODO: imprime cada opcion con su cantidad y su porcentaje",
 'fases' => [
   ['indagar', 'Preguntas que condicionan la respuesta', 'Compara dos versiones de la misma pregunta, una neutra y una que sugiere la respuesta. Aplica cada versión a cinco personas distintas y compara los resultados.', 'Las dos versiones, los resultados y una explicación de la diferencia.', 45],
   ['desarrollar', 'Diseñar el cuestionario', 'Redacta cinco preguntas cerradas con opciones que no se superpongan y que cubran todos los casos. Define como registrarás las respuestas para poder contarlas.', 'Cuestionario de cinco preguntas y formato de registro.', 45],
   ['crear', 'Programar el conteo', 'Carga las respuestas en listas y programa el conteo con un diccionario. Calcula el porcentaje de cada opción y muestra el resumen ordenado de mayor a menor.', 'Archivo encuesta.py con conteo y porcentajes de veinte respuestas reales.', 70],
   ['evaluar', 'Contrastar con el conteo manual', 'Cuenta a mano dos preguntas y compara con el resultado del programa. Si hay diferencia, encuentra la causa. Escribe que decisión de diseño de la encuesta cambiarías.', 'Verificación manual de dos preguntas y conclusión sobre el diseño.', 40],
 ],
 'recursos' => [
   ['plantilla', 'Formato de encuesta y registro', 'Hoja de recolección lista para el aula.'],
   ['lectura', 'Preguntas cerradas sin sesgo', 'Cinco reglas para redactar opciones.'],
 ]],

['codigo' => 'VCP-7-02', 'titulo' => 'Temporizador de hábitos saludables',
 'objeto' => 'el temporizador de hábitos',
 'resumen' => 'Programa que mide intervalos de estudio y descanso, avisa al usuario y registra las sesiones cumplidas.',
 'descripcion' => '<p>El estudiante construye un temporizador tipo pomodoro adaptado a su propia rutina de estudio: define los intervalos, programa la cuenta regresiva con <code>while</code> y <code>time.sleep</code>, y guarda el registro de las sesiones completadas.</p><p>El componente de indagación es real: antes de programar, el estudiante mide durante tres días cuanto tiempo estudia seguido sin distraerse. Los intervalos del temporizador se justifican con esos datos, no con lo que dice internet.</p>',
 'pregunta' => '¿Puede un programa ayudarme a cambiar un hábito, o solo me recuerda que no lo cumplo?',
 'contexto' => 'Identidades y relaciones', 'concepto' => 'Sistemas',
 'perfil' => 'Equilibrado|Reflexivo', 'atl' => 'Autogestión|Reflexión',
 'objetivos' => 'Usar ciclos con temporización|Formatear tiempo en minutos y segundos|Guardar un registro acumulado|Justificar decisiones de diseño con datos propios',
 'entregables' => 'Registro de tres días de medición|Archivo temporizador.py funcionando|Informe de una semana de uso con conclusión',
 'lenguaje' => 'Python', 'dificultad' => 'inicial', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "import time\n\ndef cuenta_regresiva(minutos):\n    segundos = minutos * 60\n    while segundos > 0:\n        m = segundos // 60\n        s = segundos % 60\n        print(f\"{m:02d}:{s:02d}\", end=\"\\r\")\n        time.sleep(1)\n        segundos -= 1\n    print(\"Tiempo cumplido\")\n\n# TODO: alterna estudio y descanso\n# TODO: guarda cuantas sesiones completaste",
 'fases' => [
   ['indagar', 'Medir mi atención real', 'Durante tres días anota cuanto tiempo estudias seguido antes de distraerte. Registra la hora, la materia y el motivo de la interrupción.', 'Tabla de tres días con al menos nueve registros.', 50],
   ['desarrollar', 'Elegir los intervalos con datos', 'A partir de tus mediciones, decide la duración del bloque de estudio y del descanso. Justifica cada número con tus datos. Define que mensaje mostrará el programa en cada cambio.', 'Justificación de los intervalos y guión de mensajes.', 40],
   ['crear', 'Programar el temporizador', 'Implementa la cuenta regresiva, la alternancia estudio-descanso y el conteo de sesiones. Guarda el total del día en un archivo de texto.', 'Archivo temporizador.py con registro persistente.', 75],
   ['evaluar', 'Una semana de uso', 'Usa tu temporizador durante cinco días. Compara el tiempo efectivo de estudio con el de la semana anterior. Explica si el programa cambió tu hábito o solo lo midió.', 'Informe de cinco días con comparación y conclusión honesta.', 45],
 ],
 'recursos' => [
   ['plantilla', 'Registro de atención de tres días', 'Formato de hora, materia, duración, interrupción.'],
   ['lectura', 'El módulo time en Python', 'Uso de sleep y formato de tiempo.'],
 ]],

['codigo' => 'VCP-7-03', 'titulo' => 'Juego de memoria con símbolos',
 'objeto' => 'el juego de memoria',
 'resumen' => 'Juego de parejas que mezcla una lista, oculta las cartas y compara selecciones del jugador.',
 'descripcion' => '<p>Un tablero de dieciséis cartas con ocho parejas. El estudiante practica el manejo de listas, el mezclado aleatorio, la comparación de elementos y el control del estado del juego (que está descubierto y que no).</p><p>La dificultad real no es el azar sino mantener dos listas sincronizadas: la del contenido y la de lo que el jugador ve. Resolver esa sincronización es la primera experiencia de manejo de estado del plan de estudios.</p>',
 'pregunta' => '¿Como recuerda un programa lo que ya pasó en la partida?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Pensador|Audaz', 'atl' => 'Pensamiento crítico|Organización',
 'objetivos' => 'Mezclar y recorrer listas|Mantener el estado visible del juego|Comparar selecciones y validar entradas|Contar intentos y aciertos',
 'entregables' => 'Archivo memoria.py jugable|Diagrama de las dos listas y su sincronización|Registro de cinco partidas con intentos promedio',
 'lenguaje' => 'Python', 'dificultad' => 'intermedio', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "import random\n\nsimbolos = [\"A\", \"B\", \"C\", \"D\", \"E\", \"F\", \"G\", \"H\"] * 2\nrandom.shuffle(simbolos)\nvisible = [\"*\"] * len(simbolos)\n\ndef mostrar():\n    for i in range(0, len(visible), 4):\n        print(\" \".join(visible[i:i+4]))\n\n# TODO: pide dos posiciones, descubrelas y compara\n# TODO: si no coinciden, vuelve a ocultarlas",
 'fases' => [
   ['indagar', 'Reglas y dificultad', 'Juega una versión física del juego de memoria. Anota cuantos intentos necesitaste y que hace que un tablero sea demasiado fácil o demasiado difícil.', 'Reglas escritas y análisis de dificultad con datos de tres partidas.', 40],
   ['desarrollar', 'Las dos listas', 'Dibuja el tablero como dos listas paralelas: contenido real y lo que ve el jugador. Explica que operación cambia cada lista y cuando.', 'Diagrama de las dos listas con tres momentos de la partida.', 45],
   ['crear', 'Programar el juego', 'Implementa mezclar, mostrar, pedir dos posiciones, comparar y actualizar. Valida que el jugador no elija una carta ya descubierta ni una posición inexistente.', 'Archivo memoria.py jugable con validaciones.', 80],
   ['evaluar', 'Ajustar la dificultad', 'Prueba con tres jugadores y registra sus intentos. Decide con esos datos si el tablero debe tener más o menos parejas y aplica el cambio.', 'Registro de cinco partidas y ajuste justificado del tablero.', 45],
 ],
 'recursos' => [
   ['lectura', 'random.shuffle y listas paralelas', 'Guía con el error de mezclar solo una de las dos listas.'],
 ]],

['codigo' => 'VCP-7-04', 'titulo' => 'Cifrado César: mensajes secretos',
 'objeto' => 'el cifrador César',
 'resumen' => 'Cifrar y descifrar mensajes desplazando letras, y comprobar por experimentación por que ese cifrado es débil.',
 'descripcion' => '<p>El estudiante programa el cifrado César, lo usa para intercambiar mensajes con un compañero y después intenta romper el mensaje de otra pareja sin conocer la clave. Descubre que con veintiséis intentos cualquiera lo rompe, y esa es la conclusión buscada.</p><p>La actividad introduce el manejo de cadenas carácter por carácter, el uso de <code>ord</code> y <code>chr</code>, y la aritmética modular, con una motivación que ningún ejercicio abstracto consigue: el mensaje secreto de un amigo.</p>',
 'pregunta' => '¿Que hace que un secreto sea realmente difícil de descubrir?',
 'contexto' => 'Orientación en el espacio y el tiempo', 'concepto' => 'Sistemas',
 'perfil' => 'Indagador|Pensador', 'atl' => 'Pensamiento crítico|Transferencia',
 'objetivos' => 'Recorrer cadenas carácter por carácter|Convertir entre carácter y código numérico|Aplicar aritmética modular|Evaluar la seguridad de un método por fuerza bruta',
 'entregables' => 'Archivo cesar.py con cifrar y descifrar|Mensaje intercambiado y descifrado|Informe de ruptura por fuerza bruta de un mensaje ajeno',
 'lenguaje' => 'Python', 'dificultad' => 'intermedio', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "def cifrar(texto, clave):\n    salida = \"\"\n    for letra in texto.upper():\n        if letra.isalpha():\n            pos = ord(letra) - ord(\"A\")\n            # TODO: desplaza pos con la clave usando modulo 26\n            salida += chr(pos + ord(\"A\"))\n        else:\n            salida += letra\n    return salida\n\n# TODO: escribe descifrar(texto, clave)",
 'fases' => [
   ['indagar', 'Historia de los mensajes cifrados', 'Investiga dos métodos históricos de cifrado y explica en que contexto se usaron y por que dejaron de ser seguros. Cita las fuentes.', 'Ficha de dos métodos históricos con fuentes citadas.', 45],
   ['desarrollar', 'El algoritmo en papel', 'Cifra a mano la palabra ALEMAN con clave 3. Escribe el algoritmo paso a paso incluyendo que hacer cuando la letra pasa de la Z, y que hacer con espacios y signos.', 'Cifrado manual y algoritmo escrito con los casos especiales.', 40],
   ['crear', 'Programar cifrar y descifrar', 'Implementa las dos funciones. Comprueba que descifrar(cifrar(texto, k), k) devuelve el texto original para al menos cinco frases distintas.', 'Archivo cesar.py con la comprobación de ida y vuelta documentada.', 70],
   ['evaluar', 'Romperlo por fuerza bruta', 'Consigue el mensaje cifrado de otra pareja sin la clave. Escribe un ciclo que pruebe las 26 claves y muestre los resultados. Explica cuanto tardaste y que significa eso sobre la seguridad del método.', 'Programa de fuerza bruta, mensaje descifrado y conclusión sobre la seguridad.', 45],
 ],
 'recursos' => [
   ['lectura', 'ord, chr y el operador módulo', 'Guía con ejemplos de la vuelta del alfabeto.'],
 ]],

['codigo' => 'VCP-7-05', 'titulo' => 'Simulador de dados y probabilidad',
 'objeto' => 'el simulador de dados',
 'resumen' => 'Simular miles de lanzamientos, comparar el resultado con la probabilidad teórica y presentarlo como gráfico de texto.',
 'descripcion' => '<p>El estudiante lanza dos dados diez veces a mano, anota la suma y compara con lo que predice la teoría. La muestra es tan pequeña que no coincide. Entonces programa la simulación y repite diez mil veces: el histograma se acerca a la campana esperada.</p><p>La actividad conecta directamente con Matemáticas y da al estudiante una herramienta que usará el resto del bachillerato: cuando el cálculo es difícil, simula. El producto final incluye un histograma dibujado con caracteres.</p>',
 'pregunta' => '¿Por que diez lanzamientos no me dicen la verdad y diez mil si?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Relaciones',
 'perfil' => 'Indagador|Pensador', 'atl' => 'Pensamiento crítico|Transferencia',
 'objetivos' => 'Simular experimentos aleatorios|Acumular frecuencias en un diccionario|Comparar frecuencia observada y probabilidad teórica|Dibujar un histograma de texto',
 'entregables' => 'Registro de diez lanzamientos manuales|Archivo dados.py con simulación e histograma|Comparación entre 100, 1.000 y 10.000 lanzamientos',
 'lenguaje' => 'Python', 'dificultad' => 'intermedio', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "import random\n\ndef simular(n):\n    conteo = {}\n    for i in range(n):\n        suma = random.randint(1, 6) + random.randint(1, 6)\n        conteo[suma] = conteo.get(suma, 0) + 1\n    return conteo\n\n# TODO: dibuja el histograma con caracteres\n# TODO: compara 100, 1000 y 10000 lanzamientos",
 'fases' => [
   ['indagar', 'Lanzar a mano y predecir', 'Lanza dos dados diez veces y anota la suma. Antes de mirar los resultados, predice cual suma será la más frecuente y explica por que. Compara predicción y resultado.', 'Registro de diez lanzamientos, predicción y comparación.', 40],
   ['desarrollar', 'Diseñar la simulación', 'Escribe que hará el programa en cada repetición y como acumulará el resultado. Diseña el histograma: cuantos caracteres por unidad, que escala usarás.', 'Pseudocódigo de la simulación y diseño del histograma.', 40],
   ['crear', 'Programar y escalar', 'Implementa la simulación y el histograma. Ejecuta con 100, 1.000 y 10.000 lanzamientos guardando cada salida.', 'Archivo dados.py y tres salidas guardadas.', 70],
   ['evaluar', 'Observado contra teórico', 'Calcula la probabilidad teórica de cada suma (casos favorables sobre 36) y compárala con tus tres simulaciones. Explica que pasa cuando n crece.', 'Tabla comparativa y conclusión sobre el tamaño de la muestra.', 50],
 ],
 'recursos' => [
   ['dataset', 'Tabla de probabilidades de dos dados', 'Los 36 resultados posibles y su suma.'],
 ]],

['codigo' => 'VCP-7-06', 'titulo' => 'Ecoreto: huella de carbono del colegio',
 'objeto' => 'la calculadora de huella',
 'resumen' => 'Calculadora que estima la huella de carbono del transporte escolar y propone escenarios de reducción.',
 'descripcion' => '<p>El estudiante recoge datos reales de como llegan al colegio veinte compañeros, aplica factores de emisión publicados y calcula la huella semanal del grupo. Luego simula escenarios: si cinco personas cambiaran de carro particular a transporte compartido, cuanto se reduce.</p><p>Es una actividad de Globalización y sustentabilidad con una exigencia clara: toda cifra debe tener fuente. Los resultados se presentan al consejo estudiantil, lo que obliga a comunicar con precisión y sin exageraciones.</p>',
 'pregunta' => '¿Que cambio pequeño en mi comunidad produce el mayor efecto medible?',
 'contexto' => 'Globalización y sustentabilidad', 'concepto' => 'Relaciones',
 'perfil' => 'Informado e instruido|Solidario', 'atl' => 'Alfabetización informacional|Pensamiento crítico',
 'objetivos' => 'Recoger datos primarios con un instrumento propio|Aplicar factores de conversión citando la fuente|Modelar escenarios alternativos|Comunicar resultados con honestidad estadística',
 'entregables' => 'Datos de veinte compañeros|Archivo huella.py con cálculo y escenarios|Presentación de una página para el consejo estudiantil',
 'lenguaje' => 'Python', 'dificultad' => 'intermedio', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "# Factores en kg CO2 por kilometro y persona (cita tu fuente)\nFACTORES = {\"carro\": 0.19, \"bus\": 0.08, \"bici\": 0.0, \"pie\": 0.0, \"moto\": 0.10}\n\ndef huella(medio, km, dias):\n    # TODO: retorna la huella semanal\n    pass\n\n# TODO: recorre los datos del grupo y suma\n# TODO: simula el escenario de cambio de medio",
 'fases' => [
   ['indagar', 'De donde salen los factores', 'Busca dos fuentes con factores de emisión por medio de transporte. Compáralas y explica por que difieren. Decide cual usarás y justifica.', 'Comparación de dos fuentes y decisión justificada.', 50],
   ['desarrollar', 'Instrumento de recolección', 'Diseña el formulario que aplicarás a veinte compañeros: medio, distancia aproximada, días por semana. Define como manejarás las respuestas incompletas.', 'Formulario y regla para datos faltantes.', 45],
   ['crear', 'Calcular y simular escenarios', 'Programa el cálculo de la huella individual y grupal, y al menos dos escenarios de reducción. Cada escenario debe indicar cuantas personas cambian y cuanto se reduce.', 'Archivo huella.py con el total real y dos escenarios.', 85],
   ['evaluar', 'Presentar sin exagerar', 'Prepara una página de resultados y preséntala a dos personas. Pídeles que señalen cualquier afirmación que no puedas respaldar con tus datos. Corrige lo señalado.', 'Presentación final con las correcciones y las fuentes visibles.', 50],
 ],
 'recursos' => [
   ['dataset', 'Factores de emisión de transporte', 'Tabla de referencia con fuentes citadas.'],
   ['plantilla', 'Formulario de movilidad escolar', 'Instrumento de recolección de datos.'],
 ]],

['codigo' => 'VCP-7-07', 'titulo' => 'Diccionario de términos de tecnología',
 'objeto' => 'el diccionario de términos',
 'resumen' => 'Programa que guarda pares término-definición, busca por palabra clave y permite ampliar el diccionario del curso.',
 'descripcion' => '<p>El estudiante construye un diccionario colaborativo con los términos técnicos del año. La estructura elegida —el diccionario de Python— se justifica comparándola con la lista: buscar en una lista obliga a recorrerla; en un diccionario la clave lleva directo al dato.</p><p>El producto se fusiona con el de los compañeros para formar el glosario del curso, lo que obliga a acordar un formato común. Esa negociación es contenido de la actividad, no un accidente.</p>',
 'pregunta' => '¿Que estructura de datos me conviene según lo que necesito hacer con la información?',
 'contexto' => 'Orientación en el espacio y el tiempo', 'concepto' => 'Sistemas',
 'perfil' => 'Informado e instruido|Buen comunicador', 'atl' => 'Organización|Colaboración',
 'objetivos' => 'Usar diccionarios con claves y valores|Buscar, agregar y actualizar entradas|Guardar y cargar datos en un archivo|Acordar un formato común de intercambio',
 'entregables' => 'Archivo glosario.py con búsqueda y adición|Veinte términos propios en formato acordado|Glosario del curso fusionado',
 'lenguaje' => 'Python', 'dificultad' => 'intermedio', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "glosario = {\n    \"algoritmo\": \"Secuencia finita de pasos que resuelve un problema.\",\n}\n\ndef buscar(termino):\n    # TODO: devuelve la definicion o un mensaje de no encontrado\n    pass\n\n# TODO: agregar(termino, definicion)\n# TODO: guardar y cargar desde archivo",
 'fases' => [
   ['indagar', 'Lista contra diccionario', 'Escribe un programa que busque un término en una lista de cien elementos contando las comparaciones, y otro que lo busque en un diccionario. Compara.', 'Los dos programas y el conteo de comparaciones.', 45],
   ['desarrollar', 'Acordar el formato del curso', 'Con dos compañeros define el formato exacto de cada entrada: nombre de la clave en minúsculas, longitud máxima de la definición, si se incluye ejemplo. Escribe el acuerdo.', 'Documento de acuerdo de formato firmado por los tres.', 40],
   ['crear', 'Programar el glosario', 'Implementa buscar, agregar, actualizar y guardar en archivo. Carga tus veinte términos respetando el formato acordado.', 'Archivo glosario.py con veinte términos guardados.', 75],
   ['evaluar', 'Fusionar y detectar conflictos', 'Une tu glosario con el de tus dos compañeros. Registra cuantos términos estaban duplicados con definiciones distintas y como resolvieron cada conflicto.', 'Glosario fusionado y registro de conflictos resueltos.', 45],
 ],
 'recursos' => [
   ['lectura', 'Diccionarios en Python', 'Claves, valores, get y recorrido.'],
 ]],

['codigo' => 'VCP-7-08', 'titulo' => 'Videojuego de plataformas: proyecto del año',
 'objeto' => 'el videojuego de plataformas',
 'resumen' => 'Proyecto insignia de 7.º: un juego 2D con gravedad, colisiones, enemigos y dos niveles diseñados por el estudiante.',
 'descripcion' => '<p>El estudiante construye un juego de plataformas con la biblioteca pygame: personaje que salta con gravedad, plataformas sólidas, un objetivo por nivel y al menos un enemigo o peligro. El proyecto exige planificación real porque no cabe en una sesión.</p><p>La entrega incluye una prueba de juego con cinco personas y un ajuste de dificultad basado en sus datos, no en la intuición del autor. Muchos estudiantes descubren aquí que su juego es imposible para todos menos para ellos.</p>',
 'pregunta' => '¿Como sé si mi juego es difícil o simplemente injusto?',
 'contexto' => 'Expresión personal y cultural', 'concepto' => 'Sistemas',
 'perfil' => 'Audaz|Reflexivo|Pensador', 'atl' => 'Autogestión|Organización|Pensamiento creativo',
 'objetivos' => 'Programar un bucle de juego con estado|Implementar gravedad y detección de colisiones|Separar el diseño de niveles del motor|Ajustar la dificultad con datos de jugadores reales',
 'entregables' => 'Dos niveles diseñados y programados|Archivo juego.py ejecutable|Datos de prueba con cinco jugadores|Bitácora completa del ciclo de diseño',
 'lenguaje' => 'Python (pygame)', 'dificultad' => 'avanzado', 'sesiones' => 7, 'horas' => 7.0, 'ia' => 1,
 'codigo_inicial' => "import pygame\n\npygame.init()\npantalla = pygame.display.set_mode((640, 360))\nreloj = pygame.time.Clock()\n\njugador = pygame.Rect(50, 200, 24, 32)\nvel_y = 0\nGRAVEDAD = 0.6\n\n# TODO: lista de plataformas como Rect\n# TODO: bucle principal con eventos, fisica y dibujo",
 'fases' => [
   ['indagar', 'Que hace justo a un juego', 'Juega tres plataformas 2D. Mide cuantos intentos necesitas para pasar el primer nivel de cada uno. Anota que te pareció injusto y por que.', 'Análisis de tres juegos con datos de intentos y criterios de justicia.', 55],
   ['desarrollar', 'Diseño de niveles y especificaciones', 'Dibuja los dos niveles en cuadrícula indicando plataformas, peligros y meta. Escribe siete especificaciones medibles, incluida una sobre el tiempo esperado para terminar el nivel 1.', 'Dos niveles dibujados y siete especificaciones medibles.', 65],
   ['crear', 'Construir el motor y los niveles', 'Programa por etapas: dibujar, mover, gravedad, colisión con plataformas, meta, segundo nivel, enemigo. Registra en la bitácora cada etapa con la fecha y el problema resuelto.', 'Archivo juego.py con dos niveles jugables y bitácora de siete entradas.', 180],
   ['evaluar', 'Prueba de juego con cinco personas', 'Cinco personas juegan sin instrucciones. Cronometra el nivel 1 y cuenta sus muertes. Compara con tu especificación de tiempo y ajusta la dificultad con esos datos.', 'Tabla de cinco jugadores, comparación con la especificación y ajuste aplicado.', 60],
 ],
 'recursos' => [
   ['plantilla', 'Cuadrícula de diseño de nivel 2D', 'Hoja imprimible de 20x11 celdas.'],
   ['lectura', 'Colisiones con rectángulos', 'Guía de pygame.Rect y detección de choques.'],
   ['plantilla', 'Registro de prueba de juego', 'Formato: jugador, tiempo nivel 1, muertes, comentario.'],
 ]],

['codigo' => 'VCP-7-09', 'titulo' => 'Agente conversacional de la biblioteca',
 'objeto' => 'el agente de biblioteca',
 'resumen' => 'Agente basado en reglas que orienta sobre el catálogo, con alcance definido y respuesta explícita ante lo que no sabe.',
 'descripcion' => '<p>El estudiante construye un agente que responde preguntas frecuentes de la biblioteca escolar. Empieza con reglas propias en Python (coincidencia de palabras clave) y luego compara ese comportamiento con el de un modelo de lenguaje configurado con las mismas reglas.</p><p>La comparación es el corazón de la actividad: el agente por reglas nunca inventa pero es rígido; el modelo es flexible pero puede inventar. El estudiante documenta un caso de cada tipo y propone como combinar ambos.</p>',
 'pregunta' => '¿Es mejor un ayudante que solo responde lo que sabe o uno que siempre responde algo?',
 'contexto' => 'Identidades y relaciones', 'concepto' => 'Comunicación',
 'perfil' => 'Íntegro|Reflexivo|Pensador', 'atl' => 'Alfabetización mediática|Pensamiento crítico',
 'objetivos' => 'Programar coincidencia por palabras clave|Definir el alcance de un agente y su respuesta ante lo desconocido|Comparar un sistema por reglas con un modelo de lenguaje|Documentar el uso de IA de forma trazable',
 'entregables' => 'Archivo agente.py con al menos diez reglas|Ficha de alcance y prohibiciones|Informe comparativo con un caso de rigidez y un caso de invención',
 'lenguaje' => 'Python', 'dificultad' => 'intermedio', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "REGLAS = {\n    (\"horario\", \"hora\", \"abre\"): \"La biblioteca abre de 7:00 a 16:00.\",\n    (\"prestamo\", \"prestar\", \"llevar\"): \"Puedes llevar hasta dos libros por dos semanas.\",\n}\n\ndef responder(pregunta):\n    p = pregunta.lower()\n    for claves, respuesta in REGLAS.items():\n        if any(c in p for c in claves):\n            return respuesta\n    return \"No tengo esa informacion. Pregunta en el mostrador.\"",
 'fases' => [
   ['indagar', 'Preguntas reales de la biblioteca', 'Consulta a la persona encargada cuales son las quince preguntas más frecuentes. Clasifícalas por tema y marca cuales tienen una respuesta única y cuales dependen del caso.', 'Listado de quince preguntas clasificadas.', 45],
   ['desarrollar', 'Alcance y reglas', 'Escribe la ficha del agente: propósito, que responde, que deriva a un humano, que nunca responde. Traduce diez preguntas a reglas de palabras clave.', 'Ficha de alcance y tabla de diez reglas.', 45],
   ['crear', 'Programar y luego comparar', 'Implementa el agente por reglas y pruébalo con quince preguntas. Después configura un modelo de lenguaje con la misma ficha y hazle las mismas quince preguntas.', 'Archivo agente.py y las dos series de quince respuestas guardadas.', 75],
   ['evaluar', 'Rigidez contra invención', 'Identifica un caso donde el agente por reglas falló por rígido y uno donde el modelo inventó información falsa. Propone una regla que combine lo mejor de ambos.', 'Informe comparativo con los dos casos documentados y la propuesta.', 45],
 ],
 'recursos' => [
   ['plantilla', 'Ficha de alcance de agente', 'Propósito, responde, deriva, nunca responde.'],
   ['lectura', 'Cuando un modelo inventa', 'Qué es una alucinación y como detectarla.'],
 ]],

['codigo' => 'VCP-7-10', 'titulo' => 'Página web de mi proyecto',
 'objeto' => 'la página web del proyecto',
 'resumen' => 'Primera página en HTML y CSS: estructura semántica, estilos propios y publicación del proyecto del año.',
 'descripcion' => '<p>El estudiante publica su videojuego o su mejor proyecto en una página web hecha a mano. Aprende que HTML describe el significado del contenido y CSS su apariencia, y que separar ambos es lo que permite cambiar el diseño sin tocar el texto.</p><p>La página debe funcionar en el celular y superar una revisión de accesibilidad básica: textos alternativos en las imágenes, contraste suficiente y jerarquía de encabezados correcta. Es la primera vez que el curso mide accesibilidad.</p>',
 'pregunta' => '¿Como presento mi trabajo para que cualquier persona, con cualquier dispositivo, pueda entenderlo?',
 'contexto' => 'Expresión personal y cultural', 'concepto' => 'Comunicación',
 'perfil' => 'Buen comunicador|Solidario', 'atl' => 'Comunicación|Alfabetización mediática',
 'objetivos' => 'Escribir HTML semántico|Aplicar estilos con CSS externo|Adaptar el diseño a pantallas pequeñas|Aplicar tres reglas básicas de accesibilidad',
 'entregables' => 'Archivos index.html y estilos.css|Captura en móvil y en escritorio|Lista de verificación de accesibilidad con tres puntos comprobados',
 'lenguaje' => 'HTML y CSS', 'dificultad' => 'inicial', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "<!DOCTYPE html>\n<html lang=\"es\">\n<head>\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<title>Mi proyecto</title>\n<link rel=\"stylesheet\" href=\"estilos.css\">\n</head>\n<body>\n<header><h1>Nombre del proyecto</h1></header>\n<main>\n  <!-- TODO: seccion de descripcion -->\n  <!-- TODO: seccion de capturas con alt -->\n</main>\n</body>\n</html>",
 'fases' => [
   ['indagar', 'Como presentan otros su trabajo', 'Analiza tres páginas de proyectos escolares o portafolios. Anota que información aparece siempre, en que orden, y que te costó encontrar.', 'Análisis de tres páginas con la estructura común identificada.', 40],
   ['desarrollar', 'Estructura y boceto', 'Dibuja el boceto de tu página para pantalla grande y para celular. Define las secciones y la jerarquía de encabezados (un solo h1).', 'Dos bocetos y el esquema de encabezados.', 40],
   ['crear', 'Escribir HTML y CSS', 'Escribe el HTML semántico primero, sin ningún estilo. Después crea estilos.css y dale identidad. Comprueba que la página sigue entendiéndose si desactivas el CSS.', 'index.html y estilos.css funcionando en los dos tamaños.', 80],
   ['evaluar', 'Revisión de accesibilidad', 'Comprueba tres puntos: toda imagen tiene alt, el contraste de texto es suficiente, los encabezados están en orden. Pide a un compañero que navegue solo con el teclado y anota los problemas.', 'Lista de verificación completada y correcciones aplicadas.', 45],
 ],
 'recursos' => [
   ['plantilla', 'Lista de verificación de accesibilidad', 'Diez puntos comprobables sin herramientas.'],
   ['lectura', 'HTML semántico en diez etiquetas', 'header, main, section, article, figure y las demás.'],
 ]],

];
