<?php
/**
 * Banco de ampliación · Niveles N11 y N12 (Programa del Diploma)
 *
 * Mismos cuatro ejes, con el rigor del Diploma: los productos se documentan
 * como evidencia y se evalúan con la rúbrica A–E de la evaluación interna.
 */

declare(strict_types=1);

return [

// ============================================================ 11.º · DP 1 ===
'N11' => [

['codigo' => 'VCP-11-13', 'titulo' => 'Proyecto Python: motor de recomendación explicable',
 'objeto' => 'el motor de recomendación',
 'resumen' => 'Construir un recomendador que además de acertar explique por qué recomendó cada cosa.',
 'descripcion' => '<p>El estudiante implementa un recomendador por similitud sobre un catálogo propio —libros de la biblioteca, actividades, electivas— y le añade lo que casi ningún sistema comercial ofrece: la razón de cada recomendación en lenguaje natural.</p><p>El requisito de explicabilidad obliga a elegir técnicas que se puedan justificar y descarta las cajas negras. El estudiante compara además su recomendador con la elección de una persona experta y analiza dónde y por qué difieren.</p>',
 'pregunta' => '¿Sirve de algo un sistema que acierta si nadie puede saber por qué acertó?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Relaciones',
 'perfil' => 'Pensador|Íntegro|Indagador', 'atl' => 'Pensamiento crítico|Transferencia',
 'objetivos' => 'Implementar similitud entre elementos con una métrica justificada|Generar explicaciones trazables de cada recomendación|Evaluar con métricas y con juicio experto|Analizar las diferencias entre ambos',
 'entregables' => 'Catálogo de al menos cuarenta elementos|Motor con explicación por recomendación|Evaluación con métrica y con una persona experta|Análisis de las discrepancias',
 'lenguaje' => 'Python', 'dificultad' => 'avanzado', 'sesiones' => 6, 'horas' => 6.0, 'ia' => 1,
 'codigo_inicial' => "def similitud(a, b):\n    # TODO: elige y justifica la metrica (Jaccard, coseno, ponderada)\n    return 0.0\n\ndef recomendar(elemento, catalogo, n=5):\n    # TODO: devuelve [(elemento, puntaje, EXPLICACION)]\n    # La explicacion debe nombrar los atributos concretos que la producen.\n    return []",
 'fases' => [
   ['indagar', 'Qué hace parecidas a dos cosas', 'Toma diez pares de tu catálogo y decide a mano cuáles se parecen. Extrae qué atributos usaste tú: esa es la base de tu métrica.', 'Diez pares valorados y los atributos que explican tu criterio.', 55],
   ['desarrollar', 'Métrica y explicación', 'Elige la métrica de similitud y justifícala frente a otras dos. Define la plantilla de explicación y qué debe nombrar siempre.', 'Métrica justificada y plantilla de explicación definida.', 55],
   ['crear', 'Implementar con explicación', 'Programa el motor sobre un catálogo de cuarenta elementos. Cada recomendación debe salir con su razón trazable a los datos.', 'Motor funcionando con explicaciones sobre el catálogo real.', 100],
   ['evaluar', 'Contra un experto', 'Pide a una persona experta (bibliotecaria, docente) sus cinco recomendaciones para tres casos. Compara con las tuyas y analiza cada diferencia.', 'Comparación de tres casos y análisis de las discrepancias.', 55],
 ],
 'recursos' => [
   ['lectura', 'Métricas de similitud', 'Jaccard, coseno y cuándo conviene cada una.'],
   ['lectura', 'Sistemas explicables', 'Por qué la explicación es un requisito y no un adorno.'],
 ]],

['codigo' => 'VCP-11-14', 'titulo' => 'Robótica: navegación con mapa y planificación de ruta',
 'objeto' => 'el planificador de ruta',
 'resumen' => 'Implementar búsqueda de camino en una cuadrícula con obstáculos y comparar dos algoritmos con datos.',
 'descripcion' => '<p>El estudiante representa el espacio como un grafo, implementa dos algoritmos de búsqueda de camino y los compara: nodos explorados, longitud de la ruta y tiempo. Después lleva la ruta a un robot real o a un simulador y observa qué se rompe al pasar del mapa al mundo.</p><p>El contenido conecta directamente con estructuras de datos y complejidad del programa: colas, grafos y el coste de cada algoritmo se estudian aquí con un producto que se mueve.</p>',
 'pregunta' => '¿Por qué la ruta más corta en el mapa no es siempre la mejor en el suelo?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Pensador|Indagador|Audaz', 'atl' => 'Pensamiento crítico|Transferencia',
 'objetivos' => 'Representar un espacio físico como grafo|Implementar dos algoritmos de búsqueda de camino|Comparar con métricas objetivas|Contrastar la simulación con la ejecución real',
 'entregables' => 'Mapa en cuadrícula con obstáculos|Los dos algoritmos implementados|Tabla comparativa en cinco escenarios|Registro de la ejecución física y sus desviaciones',
 'lenguaje' => 'Python', 'dificultad' => 'avanzado', 'sesiones' => 6, 'horas' => 7.0, 'ia' => 1,
 'codigo_inicial' => "MAPA = [\n    \"..........\",\n    \".####.....\",\n    \".....###..\",\n    \"..#.......\",\n]\n\ndef vecinos(mapa, celda):\n    # TODO: celdas transitables adyacentes\n    return []\n\n# TODO: anchura (BFS) y una busqueda informada\n# Mide en cada una: nodos explorados, longitud de ruta y tiempo",
 'fases' => [
   ['indagar', 'Del espacio al grafo', 'Mide un espacio real del colegio y conviértelo en cuadrícula. Decide el tamaño de celda y justifica por qué ese y no otro.', 'Mapa del espacio real en cuadrícula con la justificación del tamaño de celda.', 55],
   ['desarrollar', 'Diseñar la comparación', 'Especifica los dos algoritmos y las métricas. Diseña cinco escenarios de dificultad creciente y predice qué ganará en cada uno.', 'Especificación, cinco escenarios y las predicciones escritas.', 55],
   ['crear', 'Implementar y medir', 'Programa ambos algoritmos y ejecútalos en los cinco escenarios registrando las tres métricas.', 'Ambos algoritmos y la tabla de quince mediciones.', 100],
   ['evaluar', 'Del mapa al suelo', 'Lleva la mejor ruta al robot o al simulador físico. Registra las desviaciones y explica de dónde vienen: derrape, holgura, discretización.', 'Registro de la ejecución física y análisis de las desviaciones.', 60],
 ],
 'recursos' => [
   ['lectura', 'Búsqueda de caminos en cuadrículas', 'BFS y búsqueda informada con su coste.'],
   ['codigo', 'simulador_navegacion.py', 'Cuadrícula con obstáculos y visualización de la ruta.'],
 ]],

['codigo' => 'VCP-11-15', 'titulo' => 'Criptografía moderna: por qué funciona la clave pública',
 'objeto' => 'la demostración de clave pública',
 'resumen' => 'Implementar un intercambio de claves y explicar con números pequeños por qué es seguro.',
 'descripcion' => '<p>El estudiante implementa con números pequeños un intercambio de claves de tipo Diffie-Hellman y demuestra por qué un observador que ve todo el tráfico no puede deducir el secreto compartido. Después mide cuánto cuesta romperlo por fuerza bruta según crece el módulo.</p><p>Es el cierre natural del cifrado César de 7.º: de un método que se rompe en veintiséis intentos a uno cuya seguridad se sostiene en un coste computacional que se puede medir. Conecta con complejidad y con la sociedad digital: sin esto no hay banca ni mensajería privada.</p>',
 'pregunta' => '¿Cómo pueden dos personas acordar un secreto hablando delante de todo el mundo?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Pensador|Indagador|Íntegro', 'atl' => 'Pensamiento crítico|Transferencia',
 'objetivos' => 'Implementar aritmética modular y exponenciación|Demostrar la propiedad del secreto compartido|Medir el coste de romperlo por fuerza bruta|Relacionar coste computacional con seguridad práctica',
 'entregables' => 'Implementación del intercambio con números pequeños|Demostración con el registro de lo que ve un observador|Medición del coste de ruptura con módulos crecientes|Explicación de una página para no especialistas',
 'lenguaje' => 'Python', 'dificultad' => 'avanzado', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "P, G = 23, 5      # publicos: los ve todo el mundo\n\ndef publica(secreto, g=G, p=P):\n    return pow(g, secreto, p)\n\ndef compartido(publica_del_otro, mi_secreto, p=P):\n    return pow(publica_del_otro, mi_secreto, p)\n\n# TODO: comprueba que ambos llegan al mismo numero\n# TODO: rompelo por fuerza bruta y mide el tiempo con p cada vez mayor",
 'fases' => [
   ['indagar', 'El problema del canal abierto', 'Explica con un ejemplo cotidiano por qué dos personas no pueden acordar una contraseña gritando en una plaza. Busca cómo se resolvió históricamente.', 'Planteamiento del problema y su contexto histórico con fuentes.', 45],
   ['desarrollar', 'La aritmética que lo hace posible', 'Estudia la exponenciación modular y comprueba a mano, con números de dos cifras, que el intercambio produce el mismo secreto por los dos lados.', 'Comprobación manual documentada paso a paso.', 50],
   ['crear', 'Implementar y romper', 'Programa el intercambio y el ataque por fuerza bruta. Mide el tiempo de ruptura con módulos crecientes y grafica el crecimiento.', 'Implementación, ataque y gráfica del coste según el tamaño del módulo.', 90],
   ['evaluar', 'Explicárselo a alguien', 'Escribe una página explicando por qué es seguro, sin fórmulas. Pruébala con un compañero de otra asignatura y corrige lo que no entendió.', 'Explicación de una página validada con un lector no especialista.', 50],
 ],
 'recursos' => [
   ['lectura', 'Exponenciación modular', 'pow con tres argumentos y por qué es eficiente.'],
 ]],

['codigo' => 'VCP-11-16', 'titulo' => 'IA en el aula: diseñar y medir una intervención',
 'objeto' => 'la intervención pedagógica con IA',
 'resumen' => 'Diseñar una intervención con IA para una dificultad concreta de aprendizaje y medir su efecto con rigor.',
 'descripcion' => '<p>El estudiante identifica con un docente una dificultad concreta y recurrente de una asignatura, diseña una intervención con IA para atacarla y la evalúa con una medida previa y otra posterior. No se trata de «usar IA»: se trata de resolver un problema pedagógico identificado.</p><p>El rigor exige declarar lo que un experimento de aula no puede demostrar: sin asignación al azar y con pocos participantes, hay que hablar de indicios y no de pruebas. Reconocerlo con precisión forma parte de la calificación.</p>',
 'pregunta' => '¿Qué se necesita para afirmar que una herramienta mejoró el aprendizaje?',
 'contexto' => 'Identidades y relaciones', 'concepto' => 'Relaciones',
 'perfil' => 'Indagador|Íntegro|Reflexivo|Solidario', 'atl' => 'Pensamiento crítico|Colaboración|Reflexión',
 'objetivos' => 'Identificar una dificultad pedagógica con evidencia|Diseñar una intervención acotada y reproducible|Medir antes y después con el mismo instrumento|Declarar con precisión los límites de la inferencia',
 'entregables' => 'Diagnóstico de la dificultad con evidencia del docente|Diseño de la intervención y del instrumento de medida|Datos previos y posteriores|Informe con conclusiones y límites',
 'lenguaje' => 'Documentación', 'dificultad' => 'avanzado', 'sesiones' => 6, 'horas' => 7.0, 'ia' => 1,
 'codigo_inicial' => "// Diseno de la intervencion\n// Dificultad concreta (no \"les cuesta matematicas\"):\n// Evidencia de que existe:\n// Intervencion: que, cuanto tiempo, con quien\n// Instrumento de medida (el MISMO antes y despues):\n// Que NO podre concluir con este diseno:",
 'fases' => [
   ['indagar', 'Una dificultad concreta', 'Con un docente, identifica una dificultad específica y recurrente. Consigue evidencia de que existe: resultados, errores repetidos, su observación.', 'Diagnóstico con evidencia documental del docente.', 60],
   ['desarrollar', 'Diseñar intervención y medida', 'Diseña la intervención con IA y el instrumento de medida. Declara de antemano qué resultado consideraría una mejora.', 'Diseño completo con el criterio de mejora fijado por anticipado.', 60],
   ['crear', 'Aplicar y registrar', 'Mide antes, aplica la intervención durante el periodo acordado registrando todo, y vuelve a medir con el mismo instrumento.', 'Datos previos, registro de la aplicación y datos posteriores.', 110],
   ['evaluar', 'Qué puedo y qué no puedo afirmar', 'Analiza los resultados y redacta el informe separando lo que los datos sostienen de lo que sería una extrapolación.', 'Informe con conclusiones, límites declarados y recomendación al docente.', 60],
 ],
 'recursos' => [
   ['plantilla', 'Diseño de intervención educativa', 'Dificultad, intervención, medida, límites.'],
   ['lectura', 'Antes y después no es causa y efecto', 'Amenazas a la validez en un estudio de aula.'],
 ]],

['codigo' => 'VCP-11-17', 'titulo' => 'Gobernanza de internet: quién manda en la red',
 'objeto' => 'el análisis de gobernanza',
 'resumen' => 'Rastrear quién decide sobre una capa concreta de internet y qué pasa cuando esa decisión afecta a un país.',
 'descripcion' => '<p>Internet no tiene dueño, pero sí tiene quien decide: los nombres de dominio, los protocolos, los cables submarinos, las tiendas de aplicaciones. El estudiante elige una capa y rastrea quién toma las decisiones, con qué legitimidad y a quién rinde cuentas.</p><p>El caso de estudio es un episodio real donde esa decisión afectó a un país o a un colectivo. La conclusión debe presentar al menos tres posiciones legítimas en conflicto, no una denuncia.</p>',
 'pregunta' => '¿Quién decide las reglas de la red que usamos todos y ante quién responde?',
 'contexto' => 'Globalización y sustentabilidad', 'concepto' => 'Sistemas',
 'perfil' => 'Informado e instruido|De mentalidad abierta|Pensador', 'atl' => 'Alfabetización informacional|Pensamiento crítico|Comunicación',
 'objetivos' => 'Identificar los actores de una capa de internet|Analizar legitimidad y rendición de cuentas|Estudiar un caso real con fuentes diversas|Presentar posiciones en conflicto con equilibrio',
 'entregables' => 'Mapa de actores de la capa elegida|Seis fuentes evaluadas por posición y credibilidad|Estudio de un caso real|Análisis con tres posiciones contrastadas',
 'lenguaje' => 'Investigación', 'dificultad' => 'avanzado', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "// Mapa de actores\n// Capa elegida (nombres de dominio / protocolos / infraestructura / tiendas):\n// | Actor | Que decide | De donde viene su autoridad | Ante quien responde |\n//\n// Caso real: que paso, a quien afecto y como se resolvio.",
 'fases' => [
   ['indagar', 'Mapear la capa', 'Elige una capa y averigua qué organizaciones deciden sobre ella, cómo se formaron y quién las financia.', 'Mapa de al menos cuatro actores con su origen y financiación.', 55],
   ['desarrollar', 'Elegir el caso', 'Localiza un episodio real donde una decisión de esa capa afectó a un país o colectivo. Reúne seis fuentes con posiciones distintas.', 'Caso elegido y seis fuentes evaluadas.', 50],
   ['crear', 'Reconstruir el caso', 'Reconstruye qué pasó, quién decidió, con qué argumentos y qué consecuencias tuvo. Documenta la cronología con fuentes.', 'Reconstrucción del caso con cronología y fuentes citadas.', 85],
   ['evaluar', 'Tres posiciones legítimas', 'Presenta el caso desde tres posiciones distintas, todas defendibles. Pide a un compañero que identifique tu opinión: si la detecta, revisa el equilibrio.', 'Análisis con tres posiciones y registro de la prueba de equilibrio.', 55],
 ],
 'recursos' => [
   ['lectura', 'Actores de la gobernanza de internet', 'Quién es quién y cómo se toman las decisiones.'],
 ]],

['codigo' => 'VCP-11-18', 'titulo' => 'Robótica: control proporcional y ajuste con datos',
 'objeto' => 'el controlador proporcional',
 'resumen' => 'Sustituir el control de todo o nada por uno proporcional y demostrar la mejora con mediciones.',
 'descripcion' => '<p>El control de encendido y apagado hace que todo oscile: el seguidor zigzaguea, el termostato se pasa. El estudiante implementa un control proporcional, donde la corrección es proporcional al error, y demuestra la mejora midiendo la oscilación antes y después.</p><p>El ajuste de la constante se hace con datos y con método, no probando al azar: se registra el comportamiento con tres valores y se elige con criterio. Es la primera experiencia de sintonización de un sistema de control.</p>',
 'pregunta' => '¿Por qué corregir con toda la fuerza siempre es peor que corregir según cuánto me desvié?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Relaciones',
 'perfil' => 'Pensador|Indagador|Reflexivo', 'atl' => 'Pensamiento crítico|Transferencia',
 'objetivos' => 'Distinguir control discreto de control proporcional|Implementar una corrección proporcional al error|Medir oscilación y error en régimen|Sintonizar una constante con criterio y datos',
 'entregables' => 'Las dos versiones del controlador|Mediciones de oscilación en ambas|Registro del ajuste con tres valores de la constante|Justificación del valor elegido',
 'lenguaje' => 'Python', 'dificultad' => 'avanzado', 'sesiones' => 5, 'horas' => 6.0, 'ia' => 1,
 'codigo_inicial' => "# Todo o nada\n# correccion = MAXIMO if error > 0 else -MAXIMO\n\nKP = 0.5   # TODO: justifica este valor con mediciones\n\ndef control_proporcional(objetivo, medido, kp=KP):\n    error = objetivo - medido\n    correccion = kp * error\n    # TODO: limita la correccion al rango del actuador\n    return correccion",
 'fases' => [
   ['indagar', 'Medir la oscilación', 'Implementa el control de todo o nada y registra cincuenta lecturas. Mide cuánto oscila alrededor del objetivo.', 'Versión de todo o nada y medición de su oscilación.', 50],
   ['desarrollar', 'El modelo proporcional', 'Explica por escrito por qué corregir proporcionalmente al error reduce la oscilación. Define cómo medirás la mejora.', 'Explicación del modelo y las métricas de comparación definidas.', 50],
   ['crear', 'Implementar y sintonizar', 'Programa el control proporcional y prueba con tres valores de la constante, registrando cincuenta lecturas con cada uno.', 'Controlador implementado y las tres series de mediciones.', 95],
   ['evaluar', 'Elegir con criterio', 'Compara las cuatro series (todo o nada y las tres constantes). Elige el valor y justifica la elección con las métricas, no con la impresión.', 'Comparación de las cuatro series y justificación del valor elegido.', 55],
 ],
 'recursos' => [
   ['lectura', 'Del todo o nada al proporcional', 'Error, ganancia y saturación del actuador.'],
 ]],

['codigo' => 'VCP-11-19', 'titulo' => 'Proyecto Python: simulación de un sistema social',
 'objeto' => 'la simulación basada en agentes',
 'resumen' => 'Simular con agentes un fenómeno social y comprobar hasta dónde llegan las conclusiones de un modelo.',
 'descripcion' => '<p>El estudiante modela con agentes un fenómeno social sencillo —difusión de un rumor, formación de grupos, propagación de una moda— y observa cómo reglas individuales muy simples producen patrones colectivos que nadie programó.</p><p>La lección central es epistemológica: una simulación no demuestra cómo funciona la sociedad, muestra qué patrones podrían producir esas reglas. El estudiante debe formular explícitamente qué concluye y qué no, y conecta directamente con Teoría del Conocimiento.</p>',
 'pregunta' => '¿Qué me enseña sobre el mundo real un modelo que yo mismo inventé?',
 'contexto' => 'Globalización y sustentabilidad', 'concepto' => 'Sistemas',
 'perfil' => 'Indagador|Pensador|Íntegro', 'atl' => 'Pensamiento crítico|Transferencia|Reflexión',
 'objetivos' => 'Modelar agentes con reglas locales simples|Observar propiedades emergentes|Analizar la sensibilidad a los parámetros|Delimitar qué conclusiones permite un modelo',
 'entregables' => 'Simulación con al menos cien agentes|Documentación de reglas y supuestos|Análisis de sensibilidad de dos parámetros|Reflexión sobre el alcance epistemológico del modelo',
 'lenguaje' => 'Python', 'dificultad' => 'avanzado', 'sesiones' => 6, 'horas' => 6.0, 'ia' => 1,
 'codigo_inicial' => "import random\n\nclass Agente:\n    def __init__(self, id):\n        self.id = id\n        self.estado = \"neutral\"\n\n    def interactuar(self, otro, prob):\n        # TODO: regla local simple: que pasa cuando dos agentes se encuentran\n        pass\n\n# TODO: simula N pasos y registra la proporcion de cada estado\n# TODO: repite variando la probabilidad y el numero de contactos",
 'fases' => [
   ['indagar', 'El fenómeno y su literatura', 'Elige el fenómeno y busca dos fuentes que lo describan. Extrae qué reglas individuales proponen como explicación.', 'Fenómeno elegido con dos fuentes y las reglas que proponen.', 50],
   ['desarrollar', 'Reglas y supuestos', 'Define las reglas de interacción y declara todos los supuestos: cuántos contactos, con qué probabilidad, si hay memoria. Predice el patrón colectivo.', 'Especificación de reglas y supuestos, con la predicción escrita.', 50],
   ['crear', 'Simular y observar', 'Implementa con al menos cien agentes. Ejecuta varias veces y grafica la evolución. Repite variando dos parámetros.', 'Simulación funcionando y gráficas del análisis de sensibilidad.', 100],
   ['evaluar', 'Qué demuestra y qué no', 'Compara el patrón obtenido con tu predicción y con la literatura. Redacta qué concluyes y, sobre todo, qué no puedes concluir.', 'Análisis comparado y reflexión epistemológica de una página.', 60],
 ],
 'recursos' => [
   ['lectura', 'Modelos basados en agentes', 'Reglas locales, emergencia y sus límites explicativos.'],
 ]],
],

// ============================================================ 12.º · DP 2 ===
'N12' => [

['codigo' => 'VCP-12-13', 'titulo' => 'Proyecto Python: canal de datos de punta a punta',
 'objeto' => 'el canal de datos',
 'resumen' => 'Construir un proceso automatizado que extrae, transforma, valida y publica datos, con control de calidad.',
 'descripcion' => '<p>El estudiante construye un proceso completo que se ejecuta solo: obtiene datos de una fuente, los transforma, los valida contra reglas explícitas y publica el resultado. Si la validación falla, el proceso se detiene y avisa en vez de publicar datos malos.</p><p>La diferencia con un script es la robustez: registro de cada ejecución, reintentos, idempotencia y control de calidad. Se prueba con datos deliberadamente corruptos para comprobar que el proceso los rechaza.</p>',
 'pregunta' => '¿Qué separa un script que funciona hoy de un proceso en el que se puede confiar?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Pensador|Íntegro|Reflexivo', 'atl' => 'Organización|Pensamiento crítico',
 'objetivos' => 'Separar extracción, transformación y publicación|Definir reglas de validación explícitas|Registrar cada ejecución de forma auditable|Comprobar la robustez con datos corruptos',
 'entregables' => 'Proceso con las tres etapas separadas|Reglas de validación documentadas|Registro de al menos diez ejecuciones|Prueba con cinco tipos de datos corruptos',
 'lenguaje' => 'Python', 'dificultad' => 'avanzado', 'sesiones' => 6, 'horas' => 7.0, 'ia' => 1,
 'codigo_inicial' => "# Reglas de validacion (si alguna falla, NO se publica)\nREGLAS = [\n    (\"sin filas vacias\", lambda d: all(f.get(\"id\") for f in d)),\n    # TODO: rango de valores, fechas coherentes, sin duplicados, volumen esperado\n]\n\ndef ejecutar():\n    datos = extraer()\n    datos = transformar(datos)\n    fallos = [n for n, r in REGLAS if not r(datos)]\n    if fallos:\n        registrar(\"ABORTADO\", fallos)\n        return False\n    publicar(datos)\n    return True",
 'fases' => [
   ['indagar', 'Qué puede salir mal', 'Enumera diez formas en que un proceso de datos puede fallar en silencio y publicar algo incorrecto. Ordénalas por gravedad.', 'Diez modos de fallo ordenados por gravedad.', 55],
   ['desarrollar', 'Reglas y arquitectura', 'Diseña las tres etapas y define las reglas de validación que atrapan los fallos más graves. Especifica qué se registra en cada ejecución.', 'Arquitectura documentada y reglas de validación especificadas.', 55],
   ['crear', 'Implementar con registro', 'Programa el proceso completo con registro auditable, reintentos y parada segura. Ejecútalo al menos diez veces con datos reales.', 'Proceso funcionando y registro de diez ejecuciones.', 110],
   ['evaluar', 'Romperlo a propósito', 'Inyecta cinco tipos de datos corruptos y comprueba que el proceso los rechaza y avisa. Documenta cada caso y corrige lo que pase inadvertido.', 'Cinco pruebas de corrupción documentadas y correcciones aplicadas.', 60],
 ],
 'recursos' => [
   ['lectura', 'Validación y parada segura', 'Por qué es mejor no publicar que publicar mal.'],
 ]],

['codigo' => 'VCP-12-14', 'titulo' => 'ITGS: regular la inteligencia artificial',
 'objeto' => 'el análisis regulatorio',
 'resumen' => 'Comparar dos marcos regulatorios de IA y evaluar cómo afectarían a un caso concreto colombiano.',
 'descripcion' => '<p>El estudiante compara dos enfoques regulatorios de la inteligencia artificial —por ejemplo, la clasificación por riesgo europea frente a marcos sectoriales— y evalúa qué implicaría cada uno para un caso concreto del país: un sistema de admisión escolar, de crédito o de salud.</p><p>El ejercicio no busca declarar un marco ganador, sino identificar qué protege cada uno, qué cuesta y a quién beneficia. Es análisis de política pública con base técnica, exactamente lo que ITGS pide en su nivel más alto.</p>',
 'pregunta' => '¿Se puede regular una tecnología sin frenarla ni dejarla sin control?',
 'contexto' => 'Equidad y desarrollo', 'concepto' => 'Sistemas',
 'perfil' => 'Informado e instruido|De mentalidad abierta|Pensador|Íntegro', 'atl' => 'Alfabetización informacional|Pensamiento crítico|Comunicación',
 'objetivos' => 'Comparar dos marcos regulatorios con criterios explícitos|Aplicar cada marco a un caso local concreto|Identificar costos, protecciones y beneficiarios|Formular una recomendación fundamentada',
 'entregables' => 'Comparación de los dos marcos con criterios|Caso colombiano documentado|Análisis de qué exigiría cada marco al caso|Recomendación con sus contrapartidas',
 'lenguaje' => 'Documentación', 'dificultad' => 'avanzado', 'sesiones' => 6, 'horas' => 6.0, 'ia' => 1,
 'codigo_inicial' => "// Comparacion de marcos\n// | Criterio | Marco A | Marco B |\n// | Que clasifica como alto riesgo |  |  |\n// | Que exige antes de desplegar    |  |  |\n// | Quien vigila                     |  |  |\n// | Que pasa si se incumple          |  |  |\n// | Costo para una organizacion pequena |  |  |\n//\n// Aplicado al caso colombiano elegido: que cambiaria con cada uno.",
 'fases' => [
   ['indagar', 'Los dos marcos', 'Estudia dos enfoques regulatorios con fuentes primarias. Extrae qué clasifican como alto riesgo y qué exigen antes del despliegue.', 'Fichas de los dos marcos con fuentes primarias citadas.', 60],
   ['desarrollar', 'El caso local', 'Elige un sistema de IA en uso o proyectado en Colombia. Documenta qué decide, sobre quién y con qué supervisión actual.', 'Caso documentado con fuentes y su situación regulatoria presente.', 55],
   ['crear', 'Aplicar cada marco', 'Analiza qué exigiría cada marco a ese sistema concreto: evaluaciones, transparencia, recurso del afectado, sanciones. Estima el costo.', 'Análisis comparado aplicado al caso con la estimación de costos.', 95],
   ['evaluar', 'Recomendar con contrapartidas', 'Formula una recomendación para el caso colombiano declarando qué se gana y qué se sacrifica. Sométela a la crítica de un compañero.', 'Recomendación con contrapartidas y registro de la crítica recibida.', 55],
 ],
 'recursos' => [
   ['lectura', 'Enfoques regulatorios de la IA', 'Clasificación por riesgo frente a regulación sectorial.'],
   ['plantilla', 'Matriz de comparación regulatoria', 'Criterios, marcos y aplicación al caso.'],
 ]],

['codigo' => 'VCP-12-15', 'titulo' => 'Robótica: sistema completo con documentación de ingeniería',
 'objeto' => 'el sistema robótico documentado',
 'resumen' => 'Integrar sensores, actuadores y control en un sistema completo, documentado como lo haría un ingeniero.',
 'descripcion' => '<p>Proyecto de cierre de robótica: el estudiante integra al menos dos sensores y dos actuadores en un sistema que resuelve una tarea completa, y lo documenta con el nivel de un expediente de ingeniería: requisitos, diagrama de bloques, esquema de conexiones, lógica de control, plan de pruebas y manual.</p><p>La prueba definitiva es la reproducibilidad: otro equipo debe poder reconstruir el sistema únicamente con la documentación. Lo que no esté documentado, no existe.</p>',
 'pregunta' => '¿Podría otra persona reconstruir mi sistema solo con lo que escribí?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Pensador|Buen comunicador|Íntegro|Audaz', 'atl' => 'Organización|Comunicación|Pensamiento crítico',
 'objetivos' => 'Integrar varios sensores y actuadores con una lógica única|Producir documentación de ingeniería completa|Diseñar y ejecutar un plan de pruebas|Validar la reproducibilidad con terceros',
 'entregables' => 'Sistema funcionando con dos sensores y dos actuadores|Expediente completo de ingeniería|Plan de pruebas ejecutado|Informe del equipo que intentó reconstruirlo',
 'lenguaje' => 'Python', 'dificultad' => 'avanzado', 'sesiones' => 8, 'horas' => 10.0, 'ia' => 1,
 'codigo_inicial' => "// Expediente de ingenieria (indice obligatorio)\n// 1. Requisitos: que debe hacer y como se comprueba cada uno\n// 2. Diagrama de bloques: sensores -> control -> actuadores\n// 3. Esquema de conexiones con pines y voltajes\n// 4. Logica de control (maquina de estados)\n// 5. Plan de pruebas: normales, limite y de fallo\n// 6. Manual de uso y de mantenimiento\n// 7. Que haria distinto en la siguiente version",
 'fases' => [
   ['indagar', 'Requisitos verificables', 'Define la tarea y redacta los requisitos de forma que cada uno se pueda comprobar objetivamente. Descarta los que no sean medibles.', 'Lista de requisitos verificables con su método de comprobación.', 70],
   ['desarrollar', 'Diseño documentado', 'Elabora el diagrama de bloques, el esquema de conexiones y la máquina de estados del control antes de conectar nada.', 'Los tres documentos de diseño completos.', 80],
   ['crear', 'Integrar y probar', 'Construye el sistema y ejecuta el plan de pruebas: casos normales, límite y de fallo de cada sensor. Documenta cada resultado.', 'Sistema funcionando y plan de pruebas ejecutado con evidencia.', 160],
   ['evaluar', 'Que otro lo reconstruya', 'Entrega solo el expediente a otro equipo y pídeles reconstruir el sistema. Anota cada vez que tuvieron que preguntarte y complétalo.', 'Informe de reconstrucción y expediente corregido.', 70],
 ],
 'recursos' => [
   ['plantilla', 'Expediente de ingeniería', 'Índice obligatorio con el contenido de cada sección.'],
   ['plantilla', 'Plan de pruebas de sistema físico', 'Casos normales, límite y de fallo de sensores.'],
 ]],

['codigo' => 'VCP-12-16', 'titulo' => 'Enseñar con IA: la guía del departamento',
 'objeto' => 'la guía de uso de IA para el aula',
 'resumen' => 'Producir, con evidencia recogida en el colegio, la guía práctica de uso de IA que usará el departamento.',
 'descripcion' => '<p>El estudiante que termina el Diploma es quien mejor conoce el uso real de la IA en el colegio. Aquí recoge esa experiencia —la suya y la de otros cursos— y produce la guía práctica que el departamento de Tecnología entregará a docentes y estudiantes el año siguiente.</p><p>No es un documento de principios: es una guía con casos resueltos, actividades recomendadas por nivel y las advertencias que solo se aprenden usándola. Se valida con docentes que no participaron en su elaboración.</p>',
 'pregunta' => '¿Qué le diría a quien empieza a usar IA para aprender, después de tres años usándola?',
 'contexto' => 'Identidades y relaciones', 'concepto' => 'Comunicación',
 'perfil' => 'Reflexivo|Solidario|Buen comunicador|Íntegro', 'atl' => 'Reflexión|Comunicación|Colaboración',
 'objetivos' => 'Sistematizar experiencia propia y ajena|Recoger evidencia de uso en varios niveles|Redactar orientaciones prácticas y accionables|Validar un documento con sus destinatarios',
 'entregables' => 'Encuesta o entrevistas a estudiantes de tres niveles|Guía con casos resueltos y recomendaciones por nivel|Validación con tres docentes ajenos al proceso|Versión final entregada al departamento',
 'lenguaje' => 'Documentación', 'dificultad' => 'avanzado', 'sesiones' => 6, 'horas' => 7.0, 'ia' => 1,
 'codigo_inicial' => "// Estructura de la guia\n// 1. Para que SI conviene usarla, por nivel\n// 2. Para que NO, con el motivo\n// 3. Como declarar el uso en una entrega\n// 4. Diez casos frecuentes resueltos\n// 5. Senales de que estas dejando de aprender\n// 6. Que hacer cuando la IA se equivoca y no lo notas",
 'fases' => [
   ['indagar', 'Cómo se usa hoy', 'Recoge con encuesta o entrevistas cómo usan la IA estudiantes de tres niveles distintos. Identifica los usos que ayudan y los que sustituyen el aprendizaje.', 'Evidencia de uso de tres niveles con la clasificación de usos.', 65],
   ['desarrollar', 'Estructura y casos', 'Define la estructura de la guía y selecciona los diez casos frecuentes que resolverá. Cada caso debe venir de la evidencia recogida.', 'Estructura definida y los diez casos seleccionados con su origen.', 55],
   ['crear', 'Redactar la guía', 'Escribe la guía completa con recomendaciones por nivel, casos resueltos y advertencias. Que sea breve y accionable, no un tratado.', 'Guía completa redactada.', 100],
   ['evaluar', 'Validar con docentes', 'Entrega la guía a tres docentes que no participaron y pídeles resolver tres casos nuevos con ella. Corrige lo que resultó ambiguo.', 'Validación documentada y versión final entregada al departamento.', 60],
 ],
 'recursos' => [
   ['plantilla', 'Estructura de guía práctica', 'Secciones y extensión recomendada de cada una.'],
 ]],

['codigo' => 'VCP-12-17', 'titulo' => 'Sociedad digital: el informe que deja el egresado',
 'objeto' => 'el informe de diagnóstico digital',
 'resumen' => 'Diagnosticar la madurez digital del colegio y entregar un informe con recomendaciones priorizadas.',
 'descripcion' => '<p>El estudiante realiza un diagnóstico de la situación digital del colegio: infraestructura, competencias, privacidad de datos, accesibilidad, uso pedagógico. Recoge evidencia de todos los estamentos y produce un informe con recomendaciones priorizadas por impacto y viabilidad.</p><p>Es un ejercicio de consultoría real, con una restricción que lo hace exigente: cada recomendación debe indicar quién la ejecutaría, qué costaría y cómo se comprobaría que funcionó. Se presenta a la coordinación.</p>',
 'pregunta' => '¿Qué le dejo por escrito al colegio que me formó?',
 'contexto' => 'Equidad y desarrollo', 'concepto' => 'Sistemas',
 'perfil' => 'Solidario|Indagador|Buen comunicador|Reflexivo', 'atl' => 'Alfabetización informacional|Comunicación|Organización',
 'objetivos' => 'Diseñar un diagnóstico multidimensional|Recoger evidencia de varios estamentos|Priorizar por impacto y viabilidad|Formular recomendaciones ejecutables y verificables',
 'entregables' => 'Marco de diagnóstico con cinco dimensiones|Evidencia de al menos tres estamentos|Informe con recomendaciones priorizadas|Presentación a la coordinación',
 'lenguaje' => 'Documentación', 'dificultad' => 'avanzado', 'sesiones' => 6, 'horas' => 7.0, 'ia' => 1,
 'codigo_inicial' => "// Matriz de recomendaciones\n// | # | Recomendacion | Dimension | Impacto (1-5) | Viabilidad (1-5) |\n// |   | Quien la ejecuta | Costo estimado | Como se comprueba en 6 meses |\n//\n// Ordenar por impacto x viabilidad. Nada de \"mejorar la tecnologia\".",
 'fases' => [
   ['indagar', 'Marco y evidencia', 'Define las cinco dimensiones del diagnóstico y qué evidencia necesita cada una. Recoge datos de estudiantes, docentes y administración.', 'Marco de cinco dimensiones y evidencia de tres estamentos.', 80],
   ['desarrollar', 'Analizar y priorizar', 'Analiza los hallazgos por dimensión. Puntúa cada recomendación posible por impacto y viabilidad y ordénalas.', 'Análisis por dimensión y matriz de recomendaciones priorizada.', 60],
   ['crear', 'Redactar el informe', 'Escribe el informe: situación, hallazgos con evidencia y recomendaciones con responsable, costo y forma de verificación.', 'Informe completo con las recomendaciones ejecutables.', 100],
   ['evaluar', 'Presentar y escuchar', 'Presenta a la coordinación. Registra qué recomendaciones aceptan, cuáles descartan y por qué. Ajusta las que resulten inviables.', 'Acta de la presentación e informe ajustado.', 60],
 ],
 'recursos' => [
   ['plantilla', 'Marco de madurez digital escolar', 'Cinco dimensiones con sus indicadores.'],
   ['plantilla', 'Matriz de priorización', 'Impacto, viabilidad, responsable, costo, verificación.'],
 ]],

['codigo' => 'VCP-12-18', 'titulo' => 'Proyecto Python: reproducir un resultado publicado',
 'objeto' => 'la reproducción del estudio',
 'resumen' => 'Tomar un resultado publicado con datos abiertos, reproducirlo con código propio y documentar las diferencias.',
 'descripcion' => '<p>El estudiante elige un análisis publicado que use datos abiertos y trata de reproducirlo desde cero con su propio código. Es una de las experiencias más formativas posibles: casi nunca sale igual a la primera, y averiguar por qué enseña más que el resultado.</p><p>La conclusión no es si el estudio estaba bien o mal, sino qué información faltaba para reproducirlo. Esa lista es una lección directa sobre cómo documentar el trabajo propio, y se aplica de inmediato a la evaluación interna.</p>',
 'pregunta' => '¿Qué hace falta para que otra persona obtenga exactamente mi mismo resultado?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Relaciones',
 'perfil' => 'Indagador|Íntegro|Pensador', 'atl' => 'Pensamiento crítico|Alfabetización informacional|Organización',
 'objetivos' => 'Leer un análisis publicado y extraer su método|Reimplementar el análisis desde los datos originales|Documentar las diferencias y su causa|Extraer criterios de documentación reproducible',
 'entregables' => 'Ficha del estudio y su método declarado|Reimplementación completa con su código|Comparación de resultados y análisis de las diferencias|Lista de lo que faltaba para reproducirlo',
 'lenguaje' => 'Python', 'dificultad' => 'avanzado', 'sesiones' => 6, 'horas' => 6.0, 'ia' => 1,
 'codigo_inicial' => "# Registro de reproduccion\n# Resultado publicado:              Mi resultado:\n# Diferencia:                       Causa probable:\n#\n# Decisiones que el estudio NO documenta y tuve que suponer:\n# 1.\n# 2.",
 'fases' => [
   ['indagar', 'Elegir y entender', 'Elige un análisis publicado con datos abiertos accesibles. Extrae su método paso a paso y marca lo que no queda claro.', 'Ficha del estudio con el método extraído y los puntos oscuros marcados.', 60],
   ['desarrollar', 'Plan de reproducción', 'Consigue los datos originales y planifica la reimplementación. Declara por adelantado los supuestos que tendrás que hacer.', 'Datos obtenidos y plan con los supuestos declarados.', 55],
   ['crear', 'Reimplementar', 'Programa el análisis desde cero. No mires el código original si existe: el objetivo es reproducir desde la descripción.', 'Reimplementación completa con su resultado.', 100],
   ['evaluar', 'Comparar y aprender', 'Compara tu resultado con el publicado. Analiza cada diferencia y redacta qué le faltaba al estudio para ser reproducible. Aplica esos criterios a tu evaluación interna.', 'Comparación, análisis de causas y criterios aplicados a tu propio trabajo.', 60],
 ],
 'recursos' => [
   ['lectura', 'Qué hace reproducible un análisis', 'Datos, versiones, semilla aleatoria y decisiones documentadas.'],
 ]],

['codigo' => 'VCP-12-19', 'titulo' => 'IA y futuro profesional: mi plan de los próximos cinco años',
 'objeto' => 'el plan de desarrollo profesional',
 'resumen' => 'Analizar el campo al que se quiere entrar y construir un plan de destrezas fundamentado en evidencia.',
 'descripcion' => '<p>El estudiante analiza el campo profesional al que quiere entrar: qué destrezas se piden hoy, cuáles se automatizarán, cuáles ganarán valor. Combina ofertas de empleo reales, informes sectoriales y entrevistas a dos profesionales del área.</p><p>El producto es un plan personal de cinco años con destrezas concretas, formas de adquirirlas y evidencias de logro. Cierra el plan de aula de siete años con la pregunta que el estudiante se llevará al salir: qué aprender ahora que siga valiendo después.</p>',
 'pregunta' => '¿Qué destrezas seguirán valiendo cuando la mitad de lo que sé hoy esté automatizado?',
 'contexto' => 'Orientación en el espacio y el tiempo', 'concepto' => 'Relaciones',
 'perfil' => 'Reflexivo|Indagador|Audaz|Equilibrado', 'atl' => 'Autogestión|Alfabetización informacional|Reflexión',
 'objetivos' => 'Analizar la demanda real de un campo profesional|Distinguir destrezas perecederas de duraderas|Entrevistar a profesionales en ejercicio|Construir un plan verificable con hitos',
 'entregables' => 'Análisis de veinte ofertas reales del campo|Dos entrevistas a profesionales|Clasificación de destrezas por durabilidad|Plan de cinco años con hitos y evidencias',
 'lenguaje' => 'Investigación', 'dificultad' => 'avanzado', 'sesiones' => 5, 'horas' => 6.0, 'ia' => 1,
 'codigo_inicial' => "// Analisis de destrezas\n// | Destreza | Aparece en X de 20 ofertas | Automatizable? | Durabilidad (1-5) |\n//\n// Plan a cinco anos\n// | Ano | Destreza | Como la adquiero | Evidencia de que la logre |",
 'fases' => [
   ['indagar', 'Qué pide el campo hoy', 'Recoge veinte ofertas reales del campo que te interesa. Extrae las destrezas pedidas y cuenta su frecuencia.', 'Análisis de veinte ofertas con la frecuencia de cada destreza.', 60],
   ['desarrollar', 'Perecedero y duradero', 'Clasifica cada destreza por durabilidad y justifica. Entrevista a dos profesionales sobre qué cambió en su trabajo en cinco años.', 'Clasificación justificada y dos entrevistas registradas.', 65],
   ['crear', 'Construir el plan', 'Redacta el plan de cinco años: qué destreza cada año, cómo la adquirirás y con qué evidencia demostrarás haberla logrado.', 'Plan de cinco años con hitos y evidencias definidas.', 85],
   ['evaluar', 'Someterlo a crítica', 'Presenta el plan a un profesional del área y a tu orientador. Registra las objeciones y ajusta lo que resulte irreal.', 'Registro de las dos revisiones y plan ajustado.', 55],
 ],
 'recursos' => [
   ['plantilla', 'Análisis de ofertas de empleo', 'Cómo extraer destrezas y contar su frecuencia.'],
   ['plantilla', 'Plan de desarrollo a cinco años', 'Año, destreza, adquisición, evidencia.'],
 ]],
],

];
