<?php
/**
 * Banco de actividades · Nivel N9 (9.º · PAI 4 · Diseño e Informática)
 */

declare(strict_types=1);

return [

['codigo' => 'VCP-9-01', 'titulo' => 'Clases y objetos: modelar el carné estudiantil',
 'objeto' => 'el modelo del carné estudiantil',
 'resumen' => 'Primera clase propia: atributos, métodos y la diferencia entre la plantilla y cada objeto concreto.',
 'descripcion' => '<p>El estudiante modela el carné del colegio como una clase: qué datos tiene todo carné (atributos) y qué se puede hacer con él (métodos: validar vigencia, mostrar, registrar entrada). Crea varios objetos y comprueba que cada uno tiene sus propios valores pero comparte el mismo comportamiento.</p><p>La actividad insiste en el error más común del principiante: confundir la clase con el objeto. Se resuelve con una consigna práctica: imprimir el mismo método sobre cinco objetos distintos y explicar por qué el resultado cambia.</p>',
 'pregunta' => '¿Qué gano al describir primero el tipo de cosa y después cada cosa concreta?',
 'contexto' => 'Identidades y relaciones', 'concepto' => 'Sistemas',
 'perfil' => 'Pensador|Informado e instruido', 'atl' => 'Organización|Transferencia',
 'objetivos' => 'Definir clases con atributos y métodos|Instanciar objetos y distinguirlos de la clase|Usar el constructor para inicializar estado|Encapsular la validación dentro del objeto',
 'entregables' => 'Archivo carne.py con la clase completa|Cinco objetos creados y probados|Explicación escrita de la diferencia entre clase y objeto',
 'lenguaje' => 'Python', 'dificultad' => 'intermedio', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "from datetime import date\n\nclass Carne:\n    def __init__(self, codigo, nombre, grado, vence):\n        self.codigo = codigo\n        self.nombre = nombre\n        self.grado = grado\n        self.vence = vence\n\n    def vigente(self):\n        # TODO: compara vence con la fecha de hoy\n        pass\n\n    # TODO: metodo mostrar() que devuelva el texto del carne",
 'fases' => [
   ['indagar', 'Qué datos lleva un carné', 'Reúne tres carnés reales (colegio, biblioteca, transporte). Haz una tabla de qué datos aparecen en todos y cuáles son propios de uno solo. Identifica qué operaciones se hacen con cada carné.', 'Tabla comparativa de tres carnés con datos y operaciones.', 45],
   ['desarrollar', 'De la tabla a la clase', 'Diseña la clase en papel: nombre, atributos, métodos con sus parámetros y retorno. Marca qué atributos no deberían poder cambiarse desde fuera y por qué.', 'Ficha de diseño de la clase con justificación de la encapsulación.', 45],
   ['crear', 'Programar la clase y sus objetos', 'Implementa la clase completa y crea cinco objetos con datos distintos, uno de ellos con carné vencido. Ejecuta el mismo método sobre los cinco.', 'Archivo carne.py con cinco objetos y salida de los cinco.', 75],
   ['evaluar', 'Probar los límites del modelo', 'Intenta representar con tu clase un caso raro: un carné provisional, uno de docente, uno sin fecha de vencimiento. Explica qué habría que cambiar y por qué no lo hiciste ahora.', 'Análisis de tres casos límite y propuesta de cambio al modelo.', 45],
 ],
 'recursos' => [
   ['lectura', 'Clase, objeto, atributo, método', 'Cuatro definiciones con el mismo ejemplo.'],
 ]],

['codigo' => 'VCP-9-02', 'titulo' => 'Herencia y polimorfismo: el catálogo de la biblioteca',
 'objeto' => 'el catálogo de materiales',
 'resumen' => 'Jerarquía de clases para libros, revistas y material audiovisual, con un método que se comporta distinto en cada tipo.',
 'descripcion' => '<p>El estudiante construye la clase base Material y tres subclases con plazos de préstamo y reglas distintas. El mismo método <code>fecha_devolucion()</code> devuelve resultados diferentes según el tipo, y el programa principal no necesita saber con qué tipo está tratando.</p><p>La conversación importante ocurre al decidir qué va en la clase base: todo lo que se repite. El estudiante debe justificar cada atributo que sube o baja en la jerarquía, y comprobar el costo de equivocarse agregando un cuarto tipo al final de la actividad.</p>',
 'pregunta' => '¿Cómo escribo un programa que funcione igual con tipos de cosas que aún no existen?',
 'contexto' => 'Orientación en el espacio y el tiempo', 'concepto' => 'Relaciones',
 'perfil' => 'Pensador|De mentalidad abierta', 'atl' => 'Pensamiento crítico|Transferencia',
 'objetivos' => 'Diseñar una jerarquía de clases justificada|Sobrescribir métodos en las subclases|Usar polimorfismo en un recorrido único|Evaluar la jerarquía agregando un tipo nuevo',
 'entregables' => 'Diagrama de la jerarquía|Archivo catalogo.py con tres subclases|Cuarto tipo agregado y registro de cuánto código hubo que tocar',
 'lenguaje' => 'Python', 'dificultad' => 'intermedio', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "class Material:\n    def __init__(self, titulo, codigo):\n        self.titulo = titulo\n        self.codigo = codigo\n\n    def dias_prestamo(self):\n        return 14\n\nclass Libro(Material):\n    pass\n\n# TODO: Revista con 3 dias\n# TODO: Audiovisual con 2 dias y regla propia\n# TODO: recorre una lista mixta y muestra el plazo de cada uno",
 'fases' => [
   ['indagar', 'Qué se repite y qué es propio', 'Investiga los plazos y reglas reales de tres tipos de material en la biblioteca del colegio. Marca en una tabla qué comparten y qué es exclusivo de cada tipo.', 'Tabla de reglas con lo común y lo específico marcado.', 45],
   ['desarrollar', 'Diseñar la jerarquía', 'Dibuja el diagrama de clases indicando qué atributos y métodos van en la base y cuáles en cada subclase. Justifica cada ubicación con la tabla anterior.', 'Diagrama de clases con justificación por elemento.', 50],
   ['crear', 'Programar y recorrer una lista mixta', 'Implementa la base y las tres subclases. Crea una lista con materiales de los tres tipos y recórrela con un solo ciclo mostrando el plazo de cada uno.', 'Archivo catalogo.py con la lista mixta funcionando.', 85],
   ['evaluar', 'Agregar un cuarto tipo', 'Agrega un tipo nuevo (por ejemplo, mapa o instrumento) y cuenta cuántas líneas del programa existente tuviste que modificar. Si fueron muchas, explica qué falló en el diseño.', 'Cuarto tipo funcionando y conteo de líneas modificadas con análisis.', 50],
 ],
 'recursos' => [
   ['lectura', 'Herencia: cuándo sí y cuándo no', 'Tres señales de que la herencia es la herramienta equivocada.'],
 ]],

['codigo' => 'VCP-9-03', 'titulo' => 'Diseñar antes de programar: diagramas y contratos',
 'objeto' => 'el diseño documentado del sistema',
 'resumen' => 'Producir el diseño completo de un sistema pequeño —clases, flujo y datos— y validarlo con otro equipo antes de escribir código.',
 'descripcion' => '<p>Actividad sin programación. El estudiante recibe un encargo (por ejemplo, el sistema de inscripción a los clubes del colegio) y debe entregar el diseño: diagrama de clases, diagrama de flujo del caso principal y estructura de datos. Ningún archivo .py.</p><p>La validación es cruzada: otro equipo intenta implementar una parte del diseño ajeno y reporta todo lo que faltaba. Los estudiantes descubren que un diseño incompleto se detecta solo cuando alguien más intenta seguirlo, que es exactamente lo que el criterio B del ciclo de diseño evalúa.</p>',
 'pregunta' => '¿Cuánto diseño necesito antes de empezar a programar y cómo sé que es suficiente?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Pensador|Buen comunicador', 'atl' => 'Organización|Colaboración|Comunicación',
 'objetivos' => 'Producir un diagrama de clases legible|Modelar el flujo del caso de uso principal|Definir la estructura de datos y sus restricciones|Validar un diseño mediante implementación cruzada',
 'entregables' => 'Diagrama de clases|Diagrama de flujo del caso principal|Especificación de datos|Informe del equipo que intentó implementarlo',
 'lenguaje' => 'Diagramas', 'dificultad' => 'intermedio', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "// Especificacion de datos (completa en texto)\n// Entidad:\n//   campo: tipo, obligatorio, restriccion\n// Ejemplo:\n// Club\n//   nombre: texto, obligatorio, maximo 60\n//   cupo: entero, obligatorio, mayor que 0",
 'fases' => [
   ['indagar', 'Entender el encargo', 'Entrevista a quien coordina los clubes. Determina quiénes son los usuarios, qué necesita cada uno y qué reglas existen (cupos, requisitos, plazos). Redacta el planteamiento del problema.', 'Acta de entrevista y planteamiento del problema.', 50],
   ['desarrollar', 'Producir el diseño completo', 'Elabora el diagrama de clases, el diagrama de flujo del caso principal y la especificación de datos con tipos y restricciones. Redacta seis especificaciones de éxito medibles.', 'Los tres documentos de diseño y seis especificaciones.', 90],
   ['crear', 'Implementación cruzada', 'Intercambia el diseño con otro equipo. Cada equipo implementa una función del diseño ajeno siguiéndolo literalmente y anota cada vez que tuvo que suponer algo.', 'Función implementada y lista de suposiciones que tuvo que hacer.', 65],
   ['evaluar', 'Corregir el diseño con el informe ajeno', 'Recibe la lista de suposiciones del otro equipo, clasifícalas por gravedad y corrige tu diseño. Explica cuál fue la omisión más costosa y por qué se te pasó.', 'Diseño corregido y análisis de la omisión más grave.', 45],
 ],
 'recursos' => [
   ['plantilla', 'Plantilla de diagrama de clases', 'Formato con cajas de atributos y métodos.'],
   ['plantilla', 'Especificación de datos', 'Entidad, campo, tipo, obligatorio, restricción.'],
 ]],

['codigo' => 'VCP-9-04', 'titulo' => 'Aplicación web con formularios',
 'objeto' => 'la aplicación web de formularios',
 'resumen' => 'Formulario accesible con validación en el navegador, manejo del DOM y respuesta inmediata al usuario.',
 'descripcion' => '<p>El estudiante construye un formulario real —inscripción a un club, solicitud de préstamo— con etiquetas correctas, validación en JavaScript y mensajes de error asociados al campo. Aprende que la validación del navegador es comodidad, no seguridad, y que un formulario mal etiquetado es inutilizable con lector de pantalla.</p><p>La prueba final se hace navegando el formulario solo con el teclado. Es el momento en que la accesibilidad deja de ser un discurso y se vuelve un requisito comprobable.</p>',
 'pregunta' => '¿Puede alguien completar mi formulario sin ver la pantalla y sin usar el ratón?',
 'contexto' => 'Equidad y desarrollo', 'concepto' => 'Comunicación',
 'perfil' => 'Solidario|Buen comunicador', 'atl' => 'Comunicación|Pensamiento crítico',
 'objetivos' => 'Construir formularios con etiquetas y estados accesibles|Validar en el cliente con mensajes asociados al campo|Manipular el DOM para responder al usuario|Comprobar la navegación por teclado',
 'entregables' => 'Página del formulario con seis campos validados|Registro de la prueba de navegación por teclado|Lista de verificación de accesibilidad completada',
 'lenguaje' => 'HTML, CSS, JavaScript', 'dificultad' => 'intermedio', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "<form id=\"inscripcion\" novalidate>\n  <p>\n    <label for=\"nombre\">Nombre completo</label>\n    <input id=\"nombre\" name=\"nombre\" required aria-describedby=\"err-nombre\">\n    <span id=\"err-nombre\" class=\"error\" role=\"alert\"></span>\n  </p>\n  <!-- TODO: cinco campos mas -->\n  <button type=\"submit\">Inscribirme</button>\n</form>",
 'fases' => [
   ['indagar', 'Formularios que frustran', 'Completa tres formularios en línea y cronometra. Anota cada momento de duda: qué campo no entendiste, qué error no supiste corregir, qué te obligó a empezar de nuevo.', 'Análisis de tres formularios con los puntos de frustración.', 45],
   ['desarrollar', 'Diseñar campos y mensajes', 'Define los seis campos, su tipo, si son obligatorios y la regla de validación de cada uno. Redacta el mensaje de error exacto de cada regla.', 'Tabla de seis campos con reglas y mensajes.', 45],
   ['crear', 'Construir el formulario', 'Programa el HTML con etiquetas asociadas, la validación en JavaScript y los mensajes en vivo. El error debe anunciarse junto al campo, no en una alerta global.', 'Formulario funcionando con las seis validaciones.', 90],
   ['evaluar', 'Prueba con teclado y con un usuario', 'Completa tu formulario usando solo el teclado. Después pide a una persona que lo complete sin ayuda y cronometra. Corrige los dos problemas más graves.', 'Registro de las dos pruebas y correcciones aplicadas.', 55],
 ],
 'recursos' => [
   ['plantilla', 'Lista de verificación de formularios accesibles', 'Doce puntos comprobables.'],
   ['lectura', 'Por qué la validación del navegador no es seguridad', 'Demostración con las herramientas de desarrollo.'],
 ]],

['codigo' => 'VCP-9-05', 'titulo' => 'Guardar datos en el navegador con JSON',
 'objeto' => 'la aplicación con almacenamiento local',
 'resumen' => 'Persistir el estado de una aplicación web en el navegador y enfrentarse a los problemas de un almacenamiento que puede desaparecer.',
 'descripcion' => '<p>El estudiante hace que su aplicación recuerde: guarda el estado en localStorage como JSON y lo recupera al abrir. Aparecen problemas nuevos y reales: qué pasa si el usuario borra los datos, si abre la aplicación en otro navegador, si el JSON guardado tiene una versión anterior de la estructura.</p><p>La actividad exige manejar los tres casos. Es la primera vez que el estudiante escribe código defensivo para un entorno que no controla, lo que prepara el terreno para el trabajo con servidores en 10.º.</p>',
 'pregunta' => '¿Dónde viven realmente los datos de una aplicación y qué pasa cuando desaparecen?',
 'contexto' => 'Orientación en el espacio y el tiempo', 'concepto' => 'Sistemas',
 'perfil' => 'Pensador|Reflexivo', 'atl' => 'Organización|Pensamiento crítico',
 'objetivos' => 'Serializar y deserializar estado con JSON|Usar localStorage con manejo de errores|Migrar datos entre versiones de la estructura|Explicar los límites del almacenamiento en el cliente',
 'entregables' => 'Aplicación que conserva el estado al recargar|Manejo de los tres casos límite documentado|Explicación de qué datos nunca deberían guardarse en el navegador',
 'lenguaje' => 'JavaScript', 'dificultad' => 'intermedio', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "var CLAVE = \"vcp.tareas.v1\";\n\nfunction guardar(estado) {\n  try {\n    localStorage.setItem(CLAVE, JSON.stringify(estado));\n  } catch (e) {\n    // TODO: avisa al usuario que no se pudo guardar\n  }\n}\n\nfunction cargar() {\n  // TODO: lee, valida la estructura y devuelve un estado por defecto si falla\n}",
 'fases' => [
   ['indagar', 'Dónde guardan los datos las aplicaciones', 'Abre las herramientas del navegador en tres sitios y observa qué guardan. Clasifica lo que encuentres en preferencia, sesión y contenido, y valora si algo de eso sería sensible.', 'Inventario de tres sitios con la clasificación y una observación de privacidad.', 45],
   ['desarrollar', 'Diseñar la estructura y su versión', 'Define el JSON que guardarás, incluyendo un número de versión. Escribe qué hará el programa si encuentra una versión anterior o un JSON corrupto.', 'Esquema del JSON con versión y plan de migración.', 45],
   ['crear', 'Guardar, cargar y migrar', 'Implementa guardar y cargar con try y catch, la validación de la estructura y la migración desde la versión anterior. Prueba con datos corruptos escritos a mano.', 'Aplicación que sobrevive a un JSON corrupto y a un cambio de versión.', 80],
   ['evaluar', 'Tres escenarios de pérdida', 'Prueba: borrar los datos del navegador, abrir en otro navegador y modificar el JSON a mano. Documenta qué vio el usuario en cada caso y si el resultado es aceptable.', 'Documentación de los tres escenarios con la evaluación de cada uno.', 45],
 ],
 'recursos' => [
   ['lectura', 'localStorage: límites y riesgos', 'Tamaño, ámbito por origen y qué nunca guardar.'],
 ]],

['codigo' => 'VCP-9-06', 'titulo' => 'Introducción a SQL: la base de datos del club',
 'objeto' => 'la base de datos del club',
 'resumen' => 'Modelar dos tablas relacionadas, poblarlas y responder preguntas reales con consultas SQL.',
 'descripcion' => '<p>El estudiante crea las tablas de socios e inscripciones, define la relación entre ellas y responde con SQL preguntas que en Python le habrían costado veinte líneas: cuántos socios por club, quién no se ha inscrito, cuál es el club con más demanda.</p><p>La comparación es explícita: la misma pregunta resuelta con un ciclo en Python y con una consulta SQL. El estudiante mide líneas de código y tiempo de escritura, y decide con datos cuándo conviene cada herramienta.</p>',
 'pregunta' => '¿Por qué preguntarle a una base de datos es distinto de recorrer una lista?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Relaciones',
 'perfil' => 'Pensador|Indagador', 'atl' => 'Pensamiento crítico|Transferencia',
 'objetivos' => 'Crear tablas con tipos y claves|Insertar y consultar datos con SQL|Relacionar dos tablas con JOIN|Comparar el enfoque declarativo con el imperativo',
 'entregables' => 'Script SQL de creación y carga|Diez consultas que respondan preguntas reales|Comparación de una misma pregunta resuelta en SQL y en Python',
 'lenguaje' => 'SQL', 'dificultad' => 'intermedio', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "CREATE TABLE socios (\n  id INT PRIMARY KEY AUTO_INCREMENT,\n  nombre VARCHAR(100) NOT NULL,\n  grado VARCHAR(10) NOT NULL\n);\n\n-- TODO: tabla clubes\n-- TODO: tabla inscripciones con las dos claves foraneas\n-- TODO: consulta de socios por club",
 'fases' => [
   ['indagar', 'Qué preguntas necesita responder el club', 'Entrevista a quien coordina los clubes y recoge diez preguntas que necesita responder cada mes. Marca cuáles requieren cruzar información de dos fuentes.', 'Lista de diez preguntas con las que requieren cruce marcadas.', 45],
   ['desarrollar', 'Modelar las tablas', 'Diseña las tablas con sus campos, tipos y claves. Justifica por qué la inscripción es una tabla aparte y no una columna en socios.', 'Modelo de tres tablas con justificación de la relación.', 50],
   ['crear', 'Crear, cargar y consultar', 'Escribe el script de creación, carga al menos treinta filas realistas y programa las diez consultas que responden las preguntas recogidas.', 'Script SQL completo y las diez consultas con su resultado.', 90],
   ['evaluar', 'SQL contra Python', 'Elige la pregunta más compleja y resuélvela también en Python leyendo un CSV. Compara líneas de código, tiempo de escritura y facilidad para cambiar la pregunta.', 'Las dos soluciones y una conclusión con datos.', 50],
 ],
 'recursos' => [
   ['lectura', 'SELECT, WHERE, JOIN y GROUP BY', 'Guía de una página con un ejemplo de cada uno.'],
   ['dataset', 'Datos de ejemplo de clubes', 'Treinta socios y cinco clubes para cargar.'],
 ]],

['codigo' => 'VCP-9-07', 'titulo' => 'Consumir datos abiertos de la ciudad',
 'objeto' => 'la aplicación de datos abiertos',
 'resumen' => 'Conectar una aplicación a una API pública, manejar la respuesta y explicar sus límites y su licencia.',
 'descripcion' => '<p>El estudiante elige un conjunto de datos abiertos de su ciudad —calidad del aire, ciclorrutas, bibliotecas públicas— y construye una aplicación que lo consulta y lo presenta con una pregunta concreta en mente. Aprende a leer la documentación de una API, manejar el error de red y respetar los límites de uso.</p><p>Una parte de la evaluación es no técnica: quién publica esos datos, con qué licencia, cada cuánto se actualizan y qué decisiones se podrían tomar mal si el estudiante los presenta sin contexto.</p>',
 'pregunta' => '¿De quién son los datos que uso y qué responsabilidad tengo al publicarlos?',
 'contexto' => 'Globalización y sustentabilidad', 'concepto' => 'Relaciones',
 'perfil' => 'Informado e instruido|Íntegro', 'atl' => 'Alfabetización informacional|Alfabetización mediática',
 'objetivos' => 'Leer documentación de una API y construir peticiones|Procesar respuestas JSON anidadas|Manejar errores de red y datos faltantes|Citar la fuente, la licencia y la fecha de actualización',
 'entregables' => 'Aplicación que consulta la API y responde una pregunta|Ficha de la fuente con licencia y frecuencia de actualización|Manejo documentado de tres errores posibles',
 'lenguaje' => 'JavaScript o Python', 'dificultad' => 'avanzado', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "async function consultar(url) {\n  try {\n    const r = await fetch(url);\n    if (!r.ok) throw new Error(\"HTTP \" + r.status);\n    return await r.json();\n  } catch (e) {\n    // TODO: distingue error de red, error del servidor y json invalido\n  }\n}",
 'fases' => [
   ['indagar', 'Elegir la fuente y leer su ficha', 'Explora dos portales de datos abiertos. Elige un conjunto y documenta: quién lo publica, licencia, última actualización, qué campos tiene y qué campos suelen venir vacíos.', 'Ficha completa de la fuente elegida y descarte justificado de la otra.', 50],
   ['desarrollar', 'Una pregunta que valga la pena', 'Formula la pregunta concreta que tu aplicación responderá y diseña la vista que la contesta. Define qué hacer cuando la API no responde o devuelve datos incompletos.', 'Pregunta, boceto de la vista y plan de manejo de errores.', 45],
   ['crear', 'Construir la aplicación', 'Implementa la consulta, el procesamiento y la presentación. Muestra siempre la fuente y la fecha de los datos en pantalla. Maneja los tres errores previstos.', 'Aplicación funcionando con la atribución visible.', 90],
   ['evaluar', 'Qué decisión equivocada podría provocar', 'Muestra tu aplicación a dos personas y pregúntales qué concluyen. Analiza si alguna conclusión posible sería incorrecta por un límite de los datos, y agrega la advertencia necesaria.', 'Registro de las dos lecturas y advertencia agregada a la interfaz.', 55],
 ],
 'recursos' => [
   ['enlace', 'Portales de datos abiertos', 'Directorio de fuentes nacionales y municipales.'],
   ['plantilla', 'Ficha de fuente de datos', 'Publicador, licencia, actualización, campos, limitaciones.'],
 ]],

['codigo' => 'VCP-9-08', 'titulo' => 'Aplicación para una necesidad de la comunidad escolar',
 'objeto' => 'la aplicación para la comunidad escolar',
 'resumen' => 'Proyecto insignia de 9.º: detectar una necesidad real dentro del colegio y resolverla con una aplicación web completa.',
 'descripcion' => '<p>El estudiante identifica una necesidad verdadera —turnos del laboratorio, objetos perdidos, préstamo de balones, cartelera de eventos— con evidencia recogida por él mismo, y construye la aplicación que la resuelve. El cliente es una persona concreta del colegio, no un usuario imaginario.</p><p>El proyecto exige las cuatro fases del ciclo de diseño con evidencia: entrevista al cliente, especificaciones acordadas, desarrollo con registro de cambios y evaluación con uso real durante una semana. La aplicación debe seguir funcionando cuando el autor no esté presente para explicarla.</p>',
 'pregunta' => '¿Cómo sé que estoy resolviendo un problema real y no el problema que me habría gustado tener?',
 'contexto' => 'Equidad y desarrollo', 'concepto' => 'Sistemas',
 'perfil' => 'Solidario|Audaz|Reflexivo', 'atl' => 'Autogestión|Colaboración|Organización',
 'objetivos' => 'Identificar y documentar una necesidad con evidencia|Acordar especificaciones con un cliente real|Construir una aplicación web funcional|Evaluar con uso real y datos de una semana',
 'entregables' => 'Acta de entrevista con el cliente|Especificaciones firmadas|Aplicación desplegada y usable|Informe de una semana de uso real|Bitácora completa del ciclo de diseño',
 'lenguaje' => 'HTML, CSS, JavaScript', 'dificultad' => 'avanzado', 'sesiones' => 8, 'horas' => 8.0, 'ia' => 1,
 'codigo_inicial' => "// Estructura sugerida\n// index.html   vista principal\n// app.js       logica y estado\n// datos.js     acceso al almacenamiento\n// estilos.css  presentacion\n// TODO: empieza por el flujo principal, no por el diseno visual",
 'fases' => [
   ['indagar', 'Encontrar la necesidad real', 'Observa durante una semana y entrevista a tres personas de distintos roles. Documenta el problema con evidencia: cuántas veces ocurre, cuánto tiempo cuesta, a quién afecta. Redacta el planteamiento del problema.', 'Acta de tres entrevistas, evidencia cuantificada y planteamiento del problema.', 90],
   ['desarrollar', 'Especificaciones acordadas con el cliente', 'Redacta ocho especificaciones medibles y hazlas revisar por tu cliente. Presenta dos alternativas de solución, justifica la elegida y planifica el desarrollo con fechas.', 'Ocho especificaciones firmadas por el cliente, dos alternativas y cronograma.', 80],
   ['crear', 'Construir con registro de cambios', 'Desarrolla la aplicación en incrementos funcionales. Registra en la bitácora cada cambio significativo con su motivo, incluidos los que se apartan del plan original.', 'Aplicación funcional y bitácora con al menos diez entradas fechadas.', 200],
   ['evaluar', 'Una semana de uso real', 'Entrega la aplicación al cliente y déjala en uso una semana. Recoge datos de uso y una entrevista final. Evalúa cada especificación como cumplida, parcial o no cumplida y propone tres mejoras justificadas.', 'Informe de uso, evaluación de las ocho especificaciones y tres mejoras propuestas.', 80],
 ],
 'recursos' => [
   ['plantilla', 'Acta de entrevista con el cliente', 'Preguntas guía y espacio para acuerdos.'],
   ['plantilla', 'Matriz de especificaciones', 'Especificación, cómo se comprueba, resultado, evidencia.'],
   ['plantilla', 'Bitácora del ciclo de diseño', 'Formato de entrada con fase, decisión y motivo.'],
 ]],

['codigo' => 'VCP-9-09', 'titulo' => 'Agente con herramientas: el tutor de matemáticas',
 'objeto' => 'el agente tutor',
 'resumen' => 'Agente que resuelve con una calculadora propia en lugar de improvisar, y que guía en vez de dar la respuesta.',
 'descripcion' => '<p>El estudiante construye un agente al que se le entregan herramientas: una función que calcula, otra que verifica un resultado. El agente decide cuándo usarlas. La comparación con un agente sin herramientas es reveladora: el segundo se equivoca en aritmética larga con una seguridad absoluta.</p><p>El segundo eje es pedagógico: el tutor no puede dar la respuesta final. Debe devolver una pista, una pregunta o un paso. El estudiante escribe esa restricción, la prueba con compañeros reales y mide cuántos consiguieron llegar solos a la respuesta.</p>',
 'pregunta' => '¿Cuándo debe una máquina calcular y cuándo debe callarse y preguntar?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Íntegro|Pensador|Solidario', 'atl' => 'Pensamiento crítico|Reflexión',
 'objetivos' => 'Definir herramientas que un agente puede invocar|Restringir el comportamiento del agente por diseño|Comparar respuestas con y sin herramienta|Medir el efecto pedagógico con usuarios reales',
 'entregables' => 'Herramienta de cálculo programada|Ficha del agente con la regla de no dar la respuesta|Comparación de veinte respuestas con y sin herramienta|Prueba con tres compañeros',
 'lenguaje' => 'Python', 'dificultad' => 'avanzado', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "def calcular(expresion):\n    \"\"\"Herramienta que el agente puede invocar. Solo aritmetica basica.\"\"\"\n    permitido = set(\"0123456789+-*/(). \")\n    if not set(expresion) <= permitido:\n        return \"expresion no permitida\"\n    return str(eval(expresion))\n\n# TODO: describe la herramienta al agente\n# TODO: regla: nunca dar el resultado final del ejercicio del estudiante",
 'fases' => [
   ['indagar', 'Dónde falla un modelo sin herramientas', 'Plantea a un modelo diez operaciones aritméticas largas y verifica cada resultado con una calculadora. Registra la tasa de error y el tipo de error.', 'Tabla de diez operaciones con la tasa de error medida.', 45],
   ['desarrollar', 'Diseñar la herramienta y la restricción', 'Define la firma de la herramienta, qué acepta y qué rechaza. Redacta la regla que impide dar la respuesta final y las tres formas de ayuda permitidas.', 'Especificación de la herramienta y ficha del agente con la restricción.', 50],
   ['crear', 'Conectar agente y herramienta', 'Implementa la herramienta con validación de entrada y configura el agente para usarla. Prueba las mismas diez operaciones de la fase de indagación.', 'Herramienta funcionando y las diez operaciones con resultado correcto.', 80],
   ['evaluar', 'Prueba con tres compañeros', 'Tres compañeros usan el tutor con un ejercicio real. Mide cuántos llegaron solos a la respuesta y cuántas veces el agente rompió su propia regla. Corrige y vuelve a probar una vez.', 'Registro de las tres sesiones, roturas de la regla y corrección aplicada.', 55],
 ],
 'recursos' => [
   ['lectura', 'Agentes con herramientas', 'Cómo se describe una herramienta y cuándo el modelo decide usarla.'],
   ['lectura', 'Riesgos de eval y cómo acotarlo', 'Por qué la validación de la expresión es obligatoria.'],
 ]],

['codigo' => 'VCP-9-10', 'titulo' => 'Control de versiones y trabajo en equipo',
 'objeto' => 'el repositorio del equipo',
 'resumen' => 'Trabajar en equipo sobre el mismo código con Git: ramas, fusiones y la resolución de un conflicto provocado a propósito.',
 'descripcion' => '<p>Tres estudiantes trabajan sobre el mismo proyecto. Cada uno desarrolla en su rama y luego integran. El docente provoca deliberadamente un conflicto haciendo que dos personas modifiquen la misma función, y el equipo debe resolverlo sin perder el trabajo de nadie.</p><p>El aprendizaje central no es la sintaxis de los comandos sino el acuerdo: qué se escribe en un mensaje de confirmación, cuándo se integra, quién revisa. El equipo redacta su propio acuerdo de trabajo y lo evalúa al final del proyecto.</p>',
 'pregunta' => '¿Cómo trabajamos tres personas sobre el mismo archivo sin destruir el trabajo de los demás?',
 'contexto' => 'Identidades y relaciones', 'concepto' => 'Sistemas',
 'perfil' => 'Solidario|Buen comunicador|Íntegro', 'atl' => 'Colaboración|Organización|Comunicación',
 'objetivos' => 'Registrar cambios con mensajes útiles|Trabajar en ramas y fusionarlas|Resolver un conflicto conservando ambos aportes|Acordar y evaluar una forma de trabajo en equipo',
 'entregables' => 'Repositorio con al menos quince confirmaciones de tres autores|Registro del conflicto resuelto|Acuerdo de trabajo del equipo y su evaluación final',
 'lenguaje' => 'Git', 'dificultad' => 'intermedio', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 0,
 'codigo_inicial' => "# Flujo acordado por el equipo\ngit checkout -b funcion-nueva\n# ... editar ...\ngit add archivo.py\ngit commit -m \"Agrega validacion de cupo maximo\"\ngit checkout main\ngit merge funcion-nueva\n# TODO: documenta que hace tu equipo cuando aparece un conflicto",
 'fases' => [
   ['indagar', 'Cómo se pierde el trabajo', 'Recuerda o investiga tres formas reales de perder trabajo en equipo (sobrescribir un archivo compartido, versiones con nombres distintos, copias en distintos computadores). Explica el costo de cada una.', 'Análisis de tres formas de pérdida con su costo.', 40],
   ['desarrollar', 'Acuerdo de trabajo del equipo', 'Redacta con tu equipo el acuerdo: cómo se nombran las ramas, qué debe decir un mensaje de confirmación, cuándo se integra a la rama principal, quién revisa.', 'Acuerdo escrito y firmado por los tres integrantes.', 40],
   ['crear', 'Trabajar en ramas e integrar', 'Cada integrante desarrolla una funcionalidad en su rama con al menos cinco confirmaciones. Integren las tres ramas y resuelvan el conflicto provocado sin perder trabajo.', 'Repositorio con quince confirmaciones y el conflicto resuelto documentado.', 85],
   ['evaluar', 'Revisar el acuerdo con evidencia', 'Revisen el historial: ¿los mensajes explican el cambio? ¿alguien integró sin avisar? Evalúen cada punto del acuerdo con evidencia del repositorio y propongan dos ajustes.', 'Evaluación del acuerdo con evidencia y dos ajustes propuestos.', 45],
 ],
 'recursos' => [
   ['lectura', 'Git en diez comandos', 'Los comandos que realmente se usan en el aula.'],
   ['lectura', 'Cómo escribir un mensaje de confirmación', 'Qué cambió y por qué, en una línea.'],
 ]],

];
