<?php
/**
 * Banco de actividades · Nivel N10 (10.º · PAI 5 · Diseño, Informática y Proyecto Personal)
 */

declare(strict_types=1);

return [

['codigo' => 'VCP-10-01', 'titulo' => 'Investigación de usuarios y especificaciones de diseño',
 'objeto' => 'el informe de investigación de usuarios',
 'resumen' => 'Convertir observaciones y entrevistas en especificaciones medibles que alguien más pueda comprobar.',
 'descripcion' => '<p>El estudiante investiga a los usuarios de su futuro producto con tres métodos distintos: observación directa, entrevista y análisis de una solución existente. Con esa evidencia redacta especificaciones que puedan comprobarse sin discutir: no "debe ser rápido" sino "debe registrar un préstamo en menos de treinta segundos".</p><p>La actividad ataca la debilidad más común del criterio A: la investigación decorativa que se hace después de decidir la solución. Aquí el orden es forzado, y la especificación que no tenga evidencia detrás se elimina.</p>',
 'pregunta' => '¿Cómo distingo lo que el usuario necesita de lo que yo quiero construir?',
 'contexto' => 'Equidad y desarrollo', 'concepto' => 'Relaciones',
 'perfil' => 'Indagador|De mentalidad abierta', 'atl' => 'Alfabetización informacional|Pensamiento crítico',
 'objetivos' => 'Aplicar tres métodos de investigación de usuarios|Distinguir necesidad de solución preconcebida|Redactar especificaciones medibles y verificables|Trazar cada especificación a su evidencia',
 'entregables' => 'Registro de observación, entrevista y análisis de producto|Diez especificaciones medibles|Matriz de trazabilidad especificación-evidencia',
 'lenguaje' => 'Documentación', 'dificultad' => 'intermedio', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "// Matriz de trazabilidad\n// | Especificacion | Como se comprueba | Evidencia que la sustenta |\n// | 1. Registrar un prestamo en menos de 30 s | Cronometro, 5 intentos | Observacion 12/02, la bibliotecaria tardo 1:40 |",
 'fases' => [
   ['indagar', 'Tres métodos, tres evidencias', 'Observa el proceso actual durante dos sesiones sin intervenir y cronometra. Entrevista a dos usuarios con preguntas abiertas. Analiza una solución existente y anota qué resuelve y qué no.', 'Registro de observación con tiempos, dos entrevistas y análisis de un producto.', 90],
   ['desarrollar', 'De la evidencia a la especificación', 'Convierte cada hallazgo en una especificación medible. Elimina las que no tengan evidencia. Ordénalas por prioridad acordada con el usuario.', 'Diez especificaciones priorizadas y matriz de trazabilidad.', 70],
   ['crear', 'Redactar el informe de investigación', 'Escribe el informe: contexto, métodos, hallazgos, especificaciones y fuentes. Cada afirmación debe remitir a un dato del registro, no a una impresión.', 'Informe de investigación completo con fuentes citadas.', 70],
   ['evaluar', 'Validar con el usuario', 'Presenta las especificaciones al usuario y pídele que marque las que no reflejan su necesidad. Corrige y registra qué entendiste mal y por qué.', 'Especificaciones validadas y análisis de los malentendidos.', 50],
 ],
 'recursos' => [
   ['plantilla', 'Guía de entrevista de usuario', 'Preguntas abiertas y errores que sesgan la respuesta.'],
   ['plantilla', 'Matriz de trazabilidad', 'Especificación, comprobación, evidencia.'],
 ]],

['codigo' => 'VCP-10-02', 'titulo' => 'Prototipado y arquitectura de la solución',
 'objeto' => 'el prototipo y la arquitectura',
 'resumen' => 'Probar tres alternativas de solución con prototipos baratos antes de comprometerse con una.',
 'descripcion' => '<p>El estudiante produce tres prototipos en papel o de baja fidelidad de soluciones distintas al mismo problema, los prueba con usuarios y solo entonces elige. La regla es explícita: no se escribe código hasta que un usuario haya recorrido un prototipo.</p><p>La segunda mitad es la arquitectura: qué componentes tendrá el sistema, cómo se comunican, dónde vive cada dato. El estudiante entrega un diagrama que otro equipo debe poder leer sin explicaciones.</p>',
 'pregunta' => '¿Cuánto cuesta descubrir que la solución elegida era la equivocada, y cuándo conviene descubrirlo?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Audaz|Pensador', 'atl' => 'Pensamiento creativo|Pensamiento crítico',
 'objetivos' => 'Generar y prototipar tres alternativas distintas|Probar prototipos con usuarios reales|Justificar la elección con criterios explícitos|Diseñar la arquitectura de componentes y datos',
 'entregables' => 'Tres prototipos de baja fidelidad|Registro de prueba con dos usuarios por prototipo|Matriz de decisión|Diagrama de arquitectura',
 'lenguaje' => 'Documentación', 'dificultad' => 'intermedio', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "// Matriz de decision\n// Criterios (con peso): facilidad de uso 40, tiempo de desarrollo 30,\n// mantenibilidad 20, costo 10\n// | Alternativa | Criterio 1 | Criterio 2 | ... | Total |",
 'fases' => [
   ['indagar', 'Cómo lo resuelven otros', 'Analiza tres soluciones existentes al mismo problema, incluida una fuera del ámbito escolar. Anota la decisión de diseño más interesante de cada una.', 'Análisis comparativo de tres soluciones.', 50],
   ['desarrollar', 'Tres prototipos y una matriz', 'Construye tres prototipos de baja fidelidad de soluciones distintas. Define los criterios de decisión con sus pesos antes de probar, no después.', 'Tres prototipos y matriz de decisión con criterios y pesos definidos.', 75],
   ['crear', 'Probar y decidir', 'Dos usuarios recorren cada prototipo intentando completar la misma tarea. Registra tiempos y dificultades. Completa la matriz con esos datos y elige.', 'Registro de seis pruebas y decisión justificada con la matriz.', 80],
   ['evaluar', 'Diseñar y validar la arquitectura', 'Dibuja la arquitectura de la solución elegida: componentes, responsabilidades y flujo de datos. Pide a otro equipo que la lea y explique con sus palabras; corrige lo que no se entendió.', 'Diagrama de arquitectura y registro de la lectura cruzada.', 60],
 ],
 'recursos' => [
   ['plantilla', 'Matriz de decisión ponderada', 'Criterios, pesos y puntuación.'],
   ['plantilla', 'Guion de prueba de prototipo', 'Tarea, tiempo, dificultades, comentarios.'],
 ]],

['codigo' => 'VCP-10-03', 'titulo' => 'Base de datos relacional normalizada',
 'objeto' => 'el modelo de datos normalizado',
 'resumen' => 'Modelar un dominio real hasta la tercera forma normal y demostrar con datos el costo de no normalizar.',
 'descripcion' => '<p>El estudiante parte de una hoja de cálculo real con datos repetidos y la convierte en un modelo relacional. La normalización se enseña con consecuencias: primero se muestran las anomalías de actualización, inserción y borrado en la tabla plana, y solo entonces se separan las tablas.</p><p>El producto es el modelo entidad-relación, el script de creación con claves e índices, y una demostración práctica de que una actualización que antes exigía tocar cuarenta filas ahora toca una.</p>',
 'pregunta' => '¿Qué problemas concretos evita separar los datos en tablas?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Relaciones',
 'perfil' => 'Pensador|Íntegro', 'atl' => 'Pensamiento crítico|Organización',
 'objetivos' => 'Detectar anomalías en una tabla no normalizada|Aplicar las tres primeras formas normales|Definir claves primarias, foráneas e índices|Demostrar con datos el beneficio de la normalización',
 'entregables' => 'Diagrama entidad-relación|Script SQL con claves e índices|Demostración de las tres anomalías antes y después',
 'lenguaje' => 'SQL', 'dificultad' => 'avanzado', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "-- Tabla plana de partida (con anomalias)\nCREATE TABLE prestamos_plano (\n  id INT PRIMARY KEY,\n  estudiante_nombre VARCHAR(100),\n  estudiante_grado VARCHAR(10),\n  libro_titulo VARCHAR(200),\n  libro_autor VARCHAR(120),\n  fecha DATE\n);\n\n-- TODO: separa en estudiantes, libros y prestamos\n-- TODO: define claves foraneas e indices",
 'fases' => [
   ['indagar', 'Encontrar las anomalías', 'Con la tabla plana cargada, intenta: cambiar el nombre de un autor, registrar un libro que nadie ha prestado y borrar el único préstamo de un estudiante. Documenta qué falla en cada caso.', 'Demostración de las tres anomalías con las consultas usadas.', 50],
   ['desarrollar', 'Modelar hasta la tercera forma normal', 'Identifica las entidades, sus claves y las dependencias funcionales. Dibuja el diagrama entidad-relación con la cardinalidad de cada relación.', 'Diagrama entidad-relación y justificación de cada separación.', 60],
   ['crear', 'Crear el esquema y migrar', 'Escribe el script de creación con claves primarias, foráneas e índices. Migra los datos de la tabla plana al nuevo esquema con consultas de inserción.', 'Script SQL completo y datos migrados sin pérdida.', 90],
   ['evaluar', 'Repetir las tres pruebas', 'Repite las tres operaciones de la primera fase sobre el modelo normalizado. Compara cuántas filas se afectan en cada caso y cuánto código requiere cada operación.', 'Comparación cuantitativa antes y después con conclusión.', 50],
 ],
 'recursos' => [
   ['dataset', 'Hoja de cálculo de préstamos sin normalizar', 'Doscientas filas con redundancia real.'],
   ['lectura', 'Las tres primeras formas normales', 'Explicadas con las anomalías que cada una elimina.'],
 ]],

['codigo' => 'VCP-10-04', 'titulo' => 'Backend con PHP y MySQL: CRUD completo',
 'objeto' => 'la aplicación con servidor',
 'resumen' => 'Construir el servidor que lee y escribe en la base de datos, con consultas preparadas y validación en el servidor.',
 'descripcion' => '<p>El estudiante construye las cuatro operaciones —crear, leer, actualizar y borrar— sobre su modelo de datos, con PHP y MySQL. La regla no negociable es el uso de consultas preparadas: el docente demuestra en clase una inyección SQL contra una versión vulnerable escrita por el propio grupo.</p><p>La actividad establece la separación entre validación del cliente (comodidad) y validación del servidor (obligación). El estudiante debe demostrar que su servidor rechaza datos inválidos aunque se envíen saltándose el formulario.</p>',
 'pregunta' => '¿Por qué no puedo confiar en los datos que llegan desde el navegador?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Íntegro|Pensador', 'atl' => 'Pensamiento crítico|Organización',
 'objetivos' => 'Conectar a MySQL con PDO y consultas preparadas|Implementar las cuatro operaciones CRUD|Validar en el servidor de forma independiente del cliente|Demostrar y prevenir una inyección SQL',
 'entregables' => 'Aplicación CRUD funcionando|Demostración de la inyección en la versión vulnerable y su bloqueo en la segura|Registro de seis validaciones del servidor',
 'lenguaje' => 'PHP, MySQL', 'dificultad' => 'avanzado', 'sesiones' => 6, 'horas' => 6.0, 'ia' => 1,
 'codigo_inicial' => "<?php\n\$pdo = new PDO('mysql:host=localhost;dbname=club;charset=utf8mb4', 'usuario', 'clave', [\n  PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,\n]);\n\n// Version vulnerable (solo para la demostracion en clase)\n// \$sql = \"SELECT * FROM socios WHERE nombre = '\$nombre'\";\n\n// TODO: version segura con consulta preparada\n// TODO: crear, leer, actualizar y borrar",
 'fases' => [
   ['indagar', 'Ver una inyección funcionando', 'Con la versión vulnerable del ejemplo, construye una entrada que devuelva todos los registros. Explica exactamente qué consulta se terminó ejecutando y por qué.', 'Entrada maliciosa, consulta resultante y explicación del mecanismo.', 50],
   ['desarrollar', 'Diseñar las rutas y las validaciones', 'Define las operaciones, su método, sus parámetros y las validaciones de cada una. Especifica qué responde el servidor ante un dato inválido.', 'Tabla de operaciones con parámetros, validaciones y respuestas.', 50],
   ['crear', 'Implementar el CRUD seguro', 'Programa las cuatro operaciones con consultas preparadas y las validaciones del servidor. Prueba cada una desde el formulario y desde una petición directa.', 'Aplicación CRUD funcionando con validación del servidor.', 110],
   ['evaluar', 'Atacar tu propio servidor', 'Envía peticiones saltándote el formulario con datos inválidos y con la entrada maliciosa de la primera fase. Documenta la respuesta del servidor en cada caso.', 'Registro de seis intentos de ataque y la respuesta obtenida.', 60],
 ],
 'recursos' => [
   ['lectura', 'Consultas preparadas con PDO', 'Por qué el parámetro nunca se concatena.'],
   ['lectura', 'Validar en el servidor', 'Lista de comprobaciones mínimas por tipo de dato.'],
 ]],

['codigo' => 'VCP-10-05', 'titulo' => 'Autenticación y seguridad básica',
 'objeto' => 'el sistema de acceso',
 'resumen' => 'Registro e inicio de sesión con contraseñas cifradas, control de sesión y protección contra los ataques más comunes.',
 'descripcion' => '<p>El estudiante implementa el acceso a su aplicación: registro, inicio y cierre de sesión, contraseñas guardadas con una función de hash lenta, control de intentos y protección contra el envío de formularios desde otro sitio.</p><p>La actividad incluye una demostración incómoda y necesaria: el docente muestra qué se ve en la base de datos cuando las contraseñas se guardan en texto plano, usando contraseñas reales de una filtración pública anonimizada. Después de eso nadie vuelve a guardar una contraseña sin cifrar.</p>',
 'pregunta' => '¿Qué pasa con las contraseñas de mis usuarios si alguien accede a mi base de datos?',
 'contexto' => 'Identidades y relaciones', 'concepto' => 'Sistemas',
 'perfil' => 'Íntegro|Reflexivo', 'atl' => 'Pensamiento crítico|Reflexión',
 'objetivos' => 'Guardar contraseñas con hash y sal|Gestionar sesiones de forma segura|Limitar intentos de acceso|Proteger formularios con un token antifalsificación',
 'entregables' => 'Registro e inicio de sesión funcionando|Captura de la tabla de usuarios mostrando los hashes|Documentación de las cuatro protecciones implementadas',
 'lenguaje' => 'PHP', 'dificultad' => 'avanzado', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "<?php\n// Registro\n\$hash = password_hash(\$clave, PASSWORD_DEFAULT);\n\n// Inicio de sesion\nif (password_verify(\$clave, \$usuario['password_hash'])) {\n    session_regenerate_id(true);\n    \$_SESSION['usuario_id'] = \$usuario['id'];\n}\n\n// TODO: limitar intentos\n// TODO: token CSRF en cada formulario\n// TODO: cierre de sesion completo",
 'fases' => [
   ['indagar', 'Qué revela una filtración', 'Analiza un caso público de filtración de contraseñas. Determina qué se filtró exactamente, cómo estaban guardadas y qué consecuencias tuvo para los usuarios.', 'Estudio de caso con las consecuencias documentadas.', 50],
   ['desarrollar', 'Diseñar el flujo de acceso', 'Diagrama los flujos de registro, inicio, cierre y recuperación. Define las reglas: longitud mínima, número de intentos, duración de la sesión, y justifica cada valor.', 'Diagramas de flujo y tabla de reglas justificadas.', 50],
   ['crear', 'Implementar el acceso seguro', 'Programa registro, inicio y cierre con hash, regeneración de identificador de sesión, límite de intentos y token antifalsificación en todos los formularios.', 'Sistema de acceso funcionando con las cuatro protecciones.', 100],
   ['evaluar', 'Intentar entrar sin permiso', 'Prueba: acceder a una página interna sin sesión, reenviar un formulario sin token, superar el límite de intentos y leer la contraseña en la base de datos. Documenta cada resultado.', 'Registro de las cuatro pruebas con la respuesta del sistema.', 55],
 ],
 'recursos' => [
   ['lectura', 'password_hash y por qué el hash debe ser lento', 'Comparación con md5 y sha1.'],
   ['lectura', 'Tokens CSRF explicados', 'El ataque y la defensa en un diagrama.'],
 ]],

['codigo' => 'VCP-10-06', 'titulo' => 'Accesibilidad y diseño inclusivo',
 'objeto' => 'la interfaz accesible',
 'resumen' => 'Auditar y corregir una aplicación propia según criterios de accesibilidad comprobables, con pruebas reales de uso.',
 'descripcion' => '<p>El estudiante audita su propia aplicación con una lista de verificación derivada de las pautas WCAG en nivel AA: contraste, navegación por teclado, textos alternativos, jerarquía de encabezados, campos etiquetados y anuncio de errores.</p><p>La prueba definitiva es de uso, no de lista: una persona navega la aplicación con lector de pantalla o con el monitor apagado. Los estudiantes que superan la lista de verificación pero fallan la prueba de uso aprenden la diferencia entre cumplir un criterio y ser realmente usable.</p>',
 'pregunta' => '¿Mi aplicación excluye a alguien sin que yo me haya dado cuenta?',
 'contexto' => 'Equidad y desarrollo', 'concepto' => 'Comunicación',
 'perfil' => 'Solidario|De mentalidad abierta|Íntegro', 'atl' => 'Pensamiento crítico|Reflexión',
 'objetivos' => 'Auditar una interfaz con criterios objetivos|Medir contraste y corregir la paleta|Garantizar la operación completa por teclado|Contrastar el cumplimiento formal con la usabilidad real',
 'entregables' => 'Auditoría inicial con doce criterios|Correcciones aplicadas y verificadas|Registro de la prueba de uso sin pantalla',
 'lenguaje' => 'HTML, CSS', 'dificultad' => 'intermedio', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "<!-- Antes -->\n<div class=\"boton\" onclick=\"enviar()\">Enviar</div>\n<img src=\"grafica.png\">\n\n<!-- TODO: convierte el div en un boton real -->\n<!-- TODO: describe la grafica en el alt o en un texto asociado -->",
 'fases' => [
   ['indagar', 'Navegar sin ver y sin ratón', 'Recorre tu aplicación solo con el teclado y luego con el monitor apagado usando un lector de pantalla. Anota cada punto donde te quedaste sin saber qué pasaba.', 'Registro de los dos recorridos con los puntos de bloqueo.', 50],
   ['desarrollar', 'Auditoría con criterios', 'Aplica la lista de doce criterios a tu aplicación y clasifica cada incumplimiento por gravedad. Define el orden de corrección según el impacto en el usuario.', 'Auditoría de doce criterios con la priorización justificada.', 45],
   ['crear', 'Corregir e implementar', 'Corrige los incumplimientos: elementos interactivos reales, foco visible, contraste suficiente, textos alternativos, errores anunciados y encabezados en orden.', 'Aplicación corregida con las doce comprobaciones documentadas.', 85],
   ['evaluar', 'Prueba de uso real', 'Una persona que no conoce la aplicación la usa con el monitor apagado o con lector de pantalla para completar una tarea. Compara el resultado con tu auditoría.', 'Registro de la prueba y análisis de las diferencias con la auditoría.', 50],
 ],
 'recursos' => [
   ['plantilla', 'Lista de verificación WCAG AA', 'Doce criterios comprobables sin herramientas de pago.'],
   ['lectura', 'Contraste de color: cómo se calcula', 'Relación de contraste y umbrales de AA.'],
 ]],

['codigo' => 'VCP-10-07', 'titulo' => 'Pruebas con usuarios y criterios de éxito',
 'objeto' => 'el informe de pruebas con usuarios',
 'resumen' => 'Diseñar un protocolo de prueba, ejecutarlo con cinco usuarios y convertir las observaciones en decisiones de diseño.',
 'descripcion' => '<p>El estudiante diseña un protocolo con tareas concretas, define qué se medirá (tiempo, errores, ayudas solicitadas) y prueba con cinco usuarios sin ayudarlos. La regla que más cuesta cumplir es la de no intervenir: quien explica su producto durante la prueba pierde el dato más valioso.</p><p>Al final se contrastan los resultados con los criterios de éxito definidos en la fase de investigación, y cada incumplimiento se convierte en una decisión: corregir, aceptar con justificación o dejar para una versión futura.</p>',
 'pregunta' => '¿Qué observo cuando dejo de explicar mi producto y solo miro cómo lo usan?',
 'contexto' => 'Identidades y relaciones', 'concepto' => 'Relaciones',
 'perfil' => 'Reflexivo|De mentalidad abierta', 'atl' => 'Reflexión|Pensamiento crítico',
 'objetivos' => 'Diseñar tareas de prueba observables|Medir tiempo, errores y solicitudes de ayuda|Contrastar resultados con criterios de éxito|Convertir hallazgos en decisiones justificadas',
 'entregables' => 'Protocolo de prueba con cinco tareas|Datos de cinco usuarios|Informe con la evaluación de cada criterio de éxito y las decisiones tomadas',
 'lenguaje' => 'Documentación', 'dificultad' => 'intermedio', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "// Protocolo de prueba\n// Tarea 1: registra un prestamo nuevo\n//   Exito si: aparece en la lista con la fecha correcta\n//   Se mide: tiempo, errores, ayudas pedidas\n// TODO: cuatro tareas mas, sin instrucciones que revelen el camino",
 'fases' => [
   ['indagar', 'Cómo se hace una prueba honesta', 'Investiga dos protocolos de prueba de usabilidad. Identifica tres errores que sesgan el resultado (guiar, preguntar en negativo, elegir usuarios que ya conocen el producto).', 'Análisis de dos protocolos y los tres sesgos identificados.', 40],
   ['desarrollar', 'Diseñar el protocolo', 'Redacta cinco tareas en el lenguaje del usuario, sin nombrar botones. Define qué medirás en cada una y el criterio de éxito de cada tarea.', 'Protocolo con cinco tareas, mediciones y criterios de éxito.', 45],
   ['crear', 'Ejecutar con cinco usuarios', 'Realiza las cinco sesiones sin intervenir. Registra tiempo, errores, ayudas y comentarios literales. No corrijas al usuario aunque se equivoque.', 'Datos completos de cinco sesiones con citas literales.', 85],
   ['evaluar', 'De los datos a las decisiones', 'Evalúa cada criterio de éxito con los datos. Por cada incumplimiento decide: corregir ahora, aceptar con justificación o posponer, y explica el porqué.', 'Informe con la evaluación de todos los criterios y las decisiones justificadas.', 50],
 ],
 'recursos' => [
   ['plantilla', 'Protocolo de prueba de usabilidad', 'Tareas, mediciones y hoja de registro.'],
   ['lectura', 'Por qué cinco usuarios', 'Qué proporción de problemas detecta cada tamaño de muestra.'],
 ]],

['codigo' => 'VCP-10-08', 'titulo' => 'Proyecto Personal: producto y bitácora',
 'objeto' => 'el Proyecto Personal',
 'resumen' => 'Proyecto insignia de 10.º: conducir de forma autónoma un producto digital completo con bitácora del proceso.',
 'descripcion' => '<p>El estudiante dirige su propio proyecto durante varias semanas: define el objetivo y el contexto global, investiga, planifica, construye y evalúa. La particularidad del Proyecto Personal es que el proceso se evalúa tanto como el producto, y la bitácora es la única evidencia de ese proceso.</p><p>La exigencia técnica es que el producto sea real y usable por alguien distinto del autor. La exigencia de proceso es que la bitácora registre las decisiones difíciles y los cambios de rumbo, no solo los avances exitosos: un proyecto sin obstáculos documentados es un proyecto mal documentado.</p>',
 'pregunta' => '¿Soy capaz de llevar un proyecto complejo de principio a fin sin que nadie me diga qué hacer cada día?',
 'contexto' => 'Elegido por el estudiante', 'concepto' => 'Sistemas',
 'perfil' => 'Audaz|Reflexivo|Íntegro|Indagador', 'atl' => 'Autogestión|Organización|Reflexión|Transferencia',
 'objetivos' => 'Definir objetivo y contexto global propios|Planificar y sostener un proyecto de varias semanas|Construir un producto usable por terceros|Documentar decisiones, obstáculos y cambios de rumbo',
 'entregables' => 'Propuesta con objetivo y criterios de éxito|Producto terminado y en uso|Bitácora de al menos veinte entradas fechadas|Informe final y sustentación de diez minutos',
 'lenguaje' => 'Elegido por el estudiante', 'dificultad' => 'avanzado', 'sesiones' => 10, 'horas' => 12.0, 'ia' => 1,
 'codigo_inicial' => "// Entrada de bitacora (formato minimo)\n// Fecha:\n// Fase del ciclo de diseno:\n// Que hice hoy:\n// Que no funciono y por que:\n// Que decidi y que descarte:\n// Proximo paso:",
 'fases' => [
   ['indagar', 'Objetivo, contexto global e investigación', 'Define el objetivo del proyecto y el contexto global que lo enmarca. Investiga con al menos cuatro fuentes diversas y una consulta a un experto. Redacta el planteamiento del problema.', 'Propuesta de proyecto, investigación con cuatro fuentes y consulta a un experto.', 150],
   ['desarrollar', 'Criterios de éxito y plan', 'Redacta los criterios de éxito del producto y el plan de trabajo con hitos semanales. Los criterios deben poder evaluarlos otras personas sin ti presente.', 'Criterios de éxito, cronograma con hitos y plan de recursos.', 100],
   ['crear', 'Construir con bitácora diaria', 'Desarrolla el producto siguiendo el plan. Registra cada sesión en la bitácora incluyendo obstáculos, decisiones y cambios respecto al plan original con su justificación.', 'Producto terminado y bitácora con veinte entradas fechadas.', 320],
   ['evaluar', 'Evaluar el producto y el proceso', 'Evalúa el producto contra cada criterio de éxito con evidencia de terceros. Evalúa también tu proceso: qué habilidad desarrollaste, qué harías distinto. Prepara la sustentación.', 'Informe final con evaluación de producto y proceso, y sustentación de diez minutos.', 110],
 ],
 'recursos' => [
   ['plantilla', 'Bitácora del Proyecto Personal', 'Formato de entrada diaria alineado con los criterios.'],
   ['plantilla', 'Criterios de éxito evaluables por terceros', 'Cómo redactarlos para que no dependan del autor.'],
   ['lectura', 'Guía del Proyecto Personal', 'Objetivos, criterios y calendario del colegio.'],
 ]],

['codigo' => 'VCP-10-09', 'titulo' => 'Ética de la IA: buscar el sesgo en un conjunto de datos',
 'objeto' => 'el análisis de sesgo',
 'resumen' => 'Auditar un conjunto de datos y un modelo sencillo para descubrir a quién perjudican, y proponer una corrección.',
 'descripcion' => '<p>El estudiante entrena un clasificador sencillo con un conjunto de datos que contiene un sesgo deliberado y descubre que el modelo funciona peor para un subgrupo. Mide esa diferencia por grupo, no solo la exactitud global, que es exactamente donde se esconde el problema.</p><p>La actividad conecta con Teoría del Conocimiento e ITGS: el estudiante debe distinguir el sesgo que viene de los datos, el que viene del diseño y el que viene de la pregunta que alguien decidió hacer. La entrega incluye una recomendación realista, no una consigna.</p>',
 'pregunta' => '¿Un sistema que acierta el noventa por ciento de las veces es justo?',
 'contexto' => 'Equidad y desarrollo', 'concepto' => 'Relaciones',
 'perfil' => 'Íntegro|Pensador|De mentalidad abierta', 'atl' => 'Pensamiento crítico|Reflexión|Alfabetización mediática',
 'objetivos' => 'Entrenar y evaluar un clasificador sencillo|Medir el desempeño desagregado por subgrupo|Distinguir el origen del sesgo|Proponer correcciones viables y sus límites',
 'entregables' => 'Modelo entrenado y evaluado|Tabla de desempeño por subgrupo|Informe con el origen del sesgo y dos correcciones propuestas',
 'lenguaje' => 'Python', 'dificultad' => 'avanzado', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "# Evaluacion desagregada\ndef exactitud(reales, predichas):\n    aciertos = sum(1 for r, p in zip(reales, predichas) if r == p)\n    return aciertos / len(reales)\n\n# TODO: calcula la exactitud por subgrupo, no solo la global\n# TODO: compara y documenta la diferencia",
 'fases' => [
   ['indagar', 'Casos reales de sesgo algorítmico', 'Estudia dos casos documentados de sistemas que perjudicaron a un grupo. Identifica en cada uno de dónde vino el sesgo y quién lo detectó.', 'Estudio de dos casos con el origen del sesgo identificado.', 50],
   ['desarrollar', 'Diseñar la auditoría', 'Define qué subgrupos analizarás, qué métricas usarás y qué diferencia considerarás inaceptable. Fija ese umbral antes de ver los resultados.', 'Plan de auditoría con subgrupos, métricas y umbral fijado por anticipado.', 45],
   ['crear', 'Entrenar y auditar', 'Entrena el clasificador, mide la exactitud global y la desagregada por subgrupo. Documenta las diferencias encontradas y compáralas con tu umbral.', 'Modelo entrenado y tabla de desempeño global y por subgrupo.', 85],
   ['evaluar', 'Proponer una corrección honesta', 'Propón dos correcciones: una sobre los datos y otra sobre el uso del sistema. Explica los límites de cada una y qué no puede arreglar la técnica.', 'Informe con dos correcciones, sus límites y una recomendación de uso.', 60],
 ],
 'recursos' => [
   ['dataset', 'Conjunto de datos con sesgo documentado', 'Datos preparados para el aula con la fuente del sesgo explicada.'],
   ['lectura', 'Métricas de equidad', 'Exactitud desagregada, paridad y sus tensiones.'],
 ]],

['codigo' => 'VCP-10-10', 'titulo' => 'Despliegue: llevar la aplicación al servidor',
 'objeto' => 'el despliegue de la aplicación',
 'resumen' => 'Publicar la aplicación en un servidor real, con variables de entorno, respaldos y un plan de reversión.',
 'descripcion' => '<p>El estudiante lleva su aplicación de su computador a un servidor: sube el código, configura la base de datos, separa las credenciales del código y comprueba que funciona para alguien más. Descubre que funciona en mi máquina no es un criterio de éxito.</p><p>Se exige un plan de reversión escrito antes del despliegue y un respaldo verificado, es decir, restaurado y comprobado. Un respaldo que nunca se ha restaurado no es un respaldo.</p>',
 'pregunta' => '¿Qué hago cuando la versión nueva sale mal y hay gente usándola?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Reflexivo|Pensador', 'atl' => 'Organización|Autogestión',
 'objetivos' => 'Separar configuración y credenciales del código|Desplegar en un servidor y verificar desde fuera|Crear y restaurar un respaldo|Escribir y ejecutar un plan de reversión',
 'entregables' => 'Aplicación accesible desde otro dispositivo|Respaldo restaurado y verificado|Plan de reversión escrito y probado una vez',
 'lenguaje' => 'PHP, MySQL', 'dificultad' => 'avanzado', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "# Lista de verificacion de despliegue\n# [ ] Credenciales fuera del codigo\n# [ ] Errores no visibles para el usuario final\n# [ ] Base de datos creada y migrada\n# [ ] Respaldo hecho Y restaurado de prueba\n# [ ] Plan de reversion escrito\n# [ ] Probado desde un dispositivo ajeno",
 'fases' => [
   ['indagar', 'Qué cambia entre mi equipo y el servidor', 'Enumera diez diferencias entre tu entorno de desarrollo y un servidor real: rutas, permisos, versiones, mayúsculas en nombres de archivo, zona horaria. Explica cuál podría romper tu aplicación.', 'Lista de diez diferencias con el riesgo asociado a cada una.', 45],
   ['desarrollar', 'Plan de despliegue y de reversión', 'Escribe el procedimiento paso a paso del despliegue y, aparte, el de reversión. El de reversión debe poder ejecutarlo otra persona en menos de cinco minutos.', 'Los dos procedimientos escritos y revisados por un compañero.', 45],
   ['crear', 'Desplegar y verificar', 'Ejecuta el despliegue: sube el código, configura credenciales fuera del repositorio, crea la base de datos y comprueba la aplicación desde un dispositivo que no sea el tuyo.', 'Aplicación funcionando en el servidor y verificada desde otro dispositivo.', 80],
   ['evaluar', 'Simulacro de desastre', 'Provoca un fallo controlado, ejecuta tu plan de reversión y cronometra. Restaura el respaldo en una base de datos vacía y verifica que los datos están completos.', 'Registro del simulacro con tiempos y verificación del respaldo restaurado.', 50],
 ],
 'recursos' => [
   ['plantilla', 'Lista de verificación de despliegue', 'Diez puntos obligatorios antes de publicar.'],
   ['lectura', 'Credenciales fuera del código', 'Variables de entorno y archivos de configuración ignorados.'],
 ]],

];
