<?php
/**
 * Banco de ampliación · Niveles N6, N7 y N8
 *
 * Siete actividades por nivel repartidas en cuatro ejes:
 *   · Sociedad digital        (ciudadanía, privacidad, desinformación, brecha)
 *   · Proyectos en Python     (programas completos, no ejercicios sueltos)
 *   · Robótica                (con placa física o con simulador si no la hay)
 *   · IA para aprender        (la IA como herramienta de estudio, con método)
 *
 * Indexado por código de nivel.
 */

declare(strict_types=1);

return [

// =========================================================== 6.º · PAI 1 ===
'N6' => [

['codigo' => 'VCP-6-13', 'titulo' => 'Mi huella digital: lo que internet ya sabe de mí',
 'objeto' => 'el informe de huella digital',
 'resumen' => 'Rastrear qué información propia es pública, medir cuánta hay y decidir qué dejar y qué borrar.',
 'descripcion' => '<p>El estudiante se busca a sí mismo: su nombre, su correo, sus perfiles. Anota qué encuentra, quién lo publicó y si él lo autorizó. Casi siempre descubre que la mayor parte no la publicó él, sino su familia, su colegio o un compañero.</p><p>La actividad termina con decisiones concretas: qué configuración cambia, qué pide que borren y qué acuerda con su familia antes de la próxima publicación. No es una charla sobre riesgos: es una auditoría con acciones.</p>',
 'pregunta' => 'Si alguien que no me conoce me buscara hoy, ¿qué encontraría y quién lo publicó?',
 'contexto' => 'Identidades y relaciones', 'concepto' => 'Comunicación',
 'perfil' => 'Reflexivo|Íntegro|Informado e instruido', 'atl' => 'Alfabetización mediática|Autogestión',
 'objetivos' => 'Distinguir información pública, privada y compartida sin permiso|Auditar la propia presencia en la red|Ajustar la configuración de privacidad de un servicio|Acordar reglas de publicación con la familia',
 'entregables' => 'Inventario de al menos diez hallazgos con su origen|Capturas de la configuración antes y después|Acuerdo de publicación firmado con la familia',
 'lenguaje' => 'Investigación', 'dificultad' => 'inicial', 'sesiones' => 3, 'horas' => 3.0, 'ia' => 0,
 'codigo_inicial' => "# Inventario de huella digital\n# | # | Que encontre | Donde | Quien lo publico | Lo autorice? | Que hago |\n# | 1 |              |       |                  | si / no      | dejar / pedir que borren / cambiar ajuste |",
 'fases' => [
   ['indagar', 'Qué es información personal', 'Clasifica veinte datos (nombre, colegio, dirección, foto de uniforme, horario) en públicos, privados y sensibles. Explica por qué la combinación de dos datos inocentes puede dejar de serlo.', 'Clasificación de veinte datos con un ejemplo de combinación peligrosa.', 45],
   ['desarrollar', 'Plan de búsqueda', 'Escribe qué vas a buscar y dónde: buscador, redes del colegio, grupos de mensajería, álbumes familiares. Define qué anotarás de cada hallazgo.', 'Plan de búsqueda con las fuentes y el formato del inventario.', 40],
   ['crear', 'La auditoría', 'Ejecuta la búsqueda con acompañamiento de un adulto y completa el inventario. Cambia al menos dos ajustes de privacidad y guarda la captura antes y después.', 'Inventario completo y capturas de los dos cambios.', 60],
   ['evaluar', 'Qué cambio de verdad', 'Vuelve a buscarte una semana después. Anota qué desapareció, qué sigue y por qué. Escribe el acuerdo de publicación con tu familia.', 'Segunda búsqueda comparada y acuerdo familiar escrito.', 40],
 ],
 'recursos' => [
   ['plantilla', 'Inventario de huella digital', 'Tabla de seis columnas para imprimir.'],
   ['plantilla', 'Acuerdo familiar de publicación', 'Qué se publica, quién autoriza y qué nunca se sube.'],
 ]],

['codigo' => 'VCP-6-14', 'titulo' => 'La contraseña que nadie adivina',
 'objeto' => 'el comprobador de contraseñas',
 'resumen' => 'Programar un medidor de fortaleza y comprobar con él por qué las contraseñas de siempre son malas.',
 'descripcion' => '<p>El estudiante escribe un programa que puntúa una contraseña según su longitud y la variedad de caracteres, y calcula cuántas combinaciones tendría que probar alguien para adivinarla. Después pasa por el medidor las contraseñas típicas del curso, anonimizadas.</p><p>El resultado es un cartel para el salón con las tres reglas que el propio curso decidió, no las que dictó el docente. Une programación con seguridad de una forma que se recuerda.</p>',
 'pregunta' => '¿Qué hace difícil una contraseña: que sea rara o que sea larga?',
 'contexto' => 'Identidades y relaciones', 'concepto' => 'Lógica',
 'perfil' => 'Pensador|Íntegro', 'atl' => 'Pensamiento crítico|Autogestión',
 'objetivos' => 'Recorrer cadenas y clasificar caracteres|Calcular combinaciones con potencias|Traducir un cálculo en una recomendación práctica|Comunicar una norma de seguridad a otros',
 'entregables' => 'Archivo claves.py con el medidor|Tabla de diez contraseñas evaluadas (anonimizadas)|Cartel con las tres reglas del curso',
 'lenguaje' => 'Python', 'dificultad' => 'inicial', 'sesiones' => 3, 'horas' => 3.0, 'ia' => 1,
 'codigo_inicial' => "def analizar(clave):\n    tiene_min = any(c.islower() for c in clave)\n    tiene_may = any(c.isupper() for c in clave)\n    tiene_num = any(c.isdigit() for c in clave)\n    # TODO: tiene_simbolo\n    # TODO: cuenta el tamano del alfabeto usado\n    # TODO: combinaciones = alfabeto ** len(clave)\n    return 0",
 'fases' => [
   ['indagar', 'Contraseñas que se repiten', 'Investiga cuáles son las contraseñas más usadas del mundo y por qué la gente las elige. Anota las tres razones más frecuentes.', 'Lista de las diez más usadas y tres razones por las que se eligen.', 40],
   ['desarrollar', 'La regla de puntuación', 'Decide cómo puntuará tu programa: cuántos puntos por longitud, cuántos por cada tipo de carácter. Justifica los pesos con lo que encontraste.', 'Tabla de puntuación con la justificación de cada peso.', 40],
   ['crear', 'Programar el medidor', 'Implementa el análisis y el cálculo de combinaciones. Prueba con diez contraseñas: cinco típicas y cinco inventadas por ti.', 'Archivo claves.py y la tabla de diez resultados.', 60],
   ['evaluar', 'Larga o rara', 'Compara una contraseña corta con símbolos y una frase larga sin ellos. Cuál gana según tu programa. Escribe las tres reglas del curso a partir del resultado.', 'Comparación de los dos casos y cartel con las tres reglas.', 40],
 ],
 'recursos' => [
   ['lectura', 'Por qué la longitud gana', 'El cálculo de combinaciones explicado con potencias.'],
 ]],

['codigo' => 'VCP-6-15', 'titulo' => 'Proyecto Python: el organizador de la mochila',
 'objeto' => 'el organizador de la mochila',
 'resumen' => 'Programa completo que arma la lista de lo que hay que llevar cada día según el horario del curso.',
 'descripcion' => '<p>Primer proyecto de varias sesiones: el estudiante guarda el horario en un diccionario, asocia materiales a cada materia y produce la lista del día siguiente. Une listas, diccionarios, condicionales y funciones en algo que usa de verdad.</p><p>Se evalúa con un criterio simple y honesto: durante una semana, ¿el programa acertó lo que había que llevar? Los fallos se anotan y se corrigen, que es exactamente el ciclo de diseño en pequeño.</p>',
 'pregunta' => '¿Puedo confiar en un programa para algo que me importa de verdad?',
 'contexto' => 'Orientación en el espacio y el tiempo', 'concepto' => 'Sistemas',
 'perfil' => 'Reflexivo|Pensador', 'atl' => 'Organización|Autogestión',
 'objetivos' => 'Modelar un horario con diccionarios y listas|Relacionar dos estructuras de datos|Producir una salida útil para el usuario|Corregir un programa con datos de uso real',
 'entregables' => 'Archivo mochila.py funcionando|Registro de una semana de uso con aciertos y fallos|Versión corregida tras la semana',
 'lenguaje' => 'Python', 'dificultad' => 'inicial', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "HORARIO = {\n    \"lunes\": [\"Matematicas\", \"Ciencias\", \"Deportes\"],\n    # TODO: el resto de la semana\n}\nMATERIALES = {\n    \"Matematicas\": [\"cuaderno\", \"calculadora\"],\n    \"Deportes\": [\"uniforme\", \"botella de agua\"],\n    # TODO: el resto\n}\n\n# TODO: funcion lista_del_dia(dia) que no repita materiales",
 'fases' => [
   ['indagar', 'Qué se olvida de verdad', 'Pregunta a cinco compañeros qué olvidaron traer en las últimas dos semanas. Clasifica los olvidos por materia y busca el patrón.', 'Registro de olvidos de cinco compañeros con el patrón identificado.', 40],
   ['desarrollar', 'Estructura del horario', 'Diseña cómo guardarás el horario y los materiales. Decide qué hace el programa cuando dos materias piden lo mismo.', 'Diseño de las dos estructuras y la regla para materiales repetidos.', 45],
   ['crear', 'Programar y usar', 'Implementa el programa y úsalo cada noche durante una semana. Anota cada vez que la lista estuvo mal.', 'Archivo mochila.py y registro de siete días.', 75],
   ['evaluar', 'Cuántas veces acertó', 'Calcula el porcentaje de aciertos. Corrige las causas de los fallos y explica cuál era del programa y cuál tuya.', 'Porcentaje de acierto, correcciones aplicadas y análisis de las causas.', 40],
 ],
 'recursos' => [
   ['lectura', 'Diccionarios que apuntan a listas', 'Cómo relacionar dos estructuras.'],
 ]],

['codigo' => 'VCP-6-16', 'titulo' => 'Robótica sin robot: el brazo de cartón programado',
 'objeto' => 'el brazo mecánico',
 'resumen' => 'Construir un brazo articulado de cartón y escribir el programa que describe cada movimiento paso a paso.',
 'descripcion' => '<p>Antes de tocar un robot real, el estudiante construye uno de cartón con tres articulaciones y escribe el programa que lo movería: ángulos, orden y tiempos. Un compañero ejecuta el programa moviendo el brazo a mano, exactamente como se lo indican.</p><p>El objetivo es entender que un robot no «sabe» nada: repite ángulos. Cuando el brazo tira el vaso porque el programa decía 90 grados en vez de 45, la lección queda aprendida sin gastar un solo componente.</p>',
 'pregunta' => '¿Qué necesita saber una máquina para mover algo sin romperlo?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Audaz|Pensador|Buen comunicador', 'atl' => 'Pensamiento crítico|Colaboración',
 'objetivos' => 'Descomponer un movimiento en pasos y ángulos|Escribir instrucciones sin ambigüedad|Simular la ejecución con un operador humano|Corregir el programa a partir de la ejecución',
 'entregables' => 'Brazo de cartón con tres articulaciones|Programa de movimiento en pseudocódigo y en Python|Video o registro de la ejecución y las correcciones',
 'lenguaje' => 'Python', 'dificultad' => 'inicial', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 0,
 'codigo_inicial' => "# Cada instruccion mueve UNA articulacion\nMOVIMIENTOS = [\n    (\"base\", 45),      # grados\n    (\"codo\", 90),\n    (\"pinza\", \"cerrar\"),\n    # TODO: completa la secuencia para levantar el vaso\n]\n\nfor parte, valor in MOVIMIENTOS:\n    print(f\"Mueve {parte} a {valor}\")",
 'fases' => [
   ['indagar', 'Cómo se mueve un brazo', 'Observa tu propio brazo levantando un vaso. Cuenta cuántas articulaciones intervienen y en qué orden. Dibuja el recorrido.', 'Dibujo del recorrido con las articulaciones y el orden numerado.', 45],
   ['desarrollar', 'Construir y medir', 'Construye el brazo de cartón con tres articulaciones. Mide con transportador los ángulos que necesitas para alcanzar el vaso.', 'Brazo construido y tabla de ángulos medidos.', 55],
   ['crear', 'Programar la secuencia', 'Escribe la secuencia de movimientos y pásala a Python. Un compañero la ejecuta a mano, sin improvisar ni corregir nada.', 'Programa escrito y registro de la primera ejecución.', 60],
   ['evaluar', 'Por qué falló', 'Anota qué salió mal y si la causa fue el ángulo, el orden o la falta de una instrucción. Corrige y vuelve a ejecutar hasta lograrlo.', 'Análisis de los fallos y programa corregido que funciona.', 40],
 ],
 'recursos' => [
   ['plantilla', 'Molde del brazo de cartón', 'Piezas y puntos de articulación para recortar.'],
   ['plantilla', 'Tabla de ángulos', 'Articulación, ángulo, orden, observación.'],
 ]],

['codigo' => 'VCP-6-17', 'titulo' => 'Estudiar con IA: pídele preguntas, no respuestas',
 'objeto' => 'la sesión de estudio con IA',
 'resumen' => 'Usar un asistente para que te tome la lección antes de un examen, y medir si sirvió comparando dos temas.',
 'descripcion' => '<p>El estudiante prepara dos temas de otra asignatura: uno estudiando como siempre y otro pidiéndole al asistente que le haga preguntas, nunca que se lo explique todo. Al terminar, se autoevalúa con las mismas diez preguntas en ambos temas.</p><p>La comparación es personal y honesta: para algunos funciona mejor, para otros no. Lo que se aprende no es que la IA sea buena o mala, sino a medir si una técnica de estudio funciona para uno mismo.</p>',
 'pregunta' => '¿Aprendo más cuando me explican o cuando me preguntan?',
 'contexto' => 'Identidades y relaciones', 'concepto' => 'Comunicación',
 'perfil' => 'Reflexivo|Íntegro|Equilibrado', 'atl' => 'Autogestión|Reflexión',
 'objetivos' => 'Dirigir un asistente para que interrogue en vez de explicar|Comparar dos técnicas de estudio con la misma medida|Registrar el uso de IA de forma trazable|Elegir una técnica con evidencia propia',
 'entregables' => 'Instrucción usada con el asistente|Registro de las dos sesiones de estudio|Autoevaluación de los dos temas y conclusión personal',
 'lenguaje' => 'Lenguaje natural', 'dificultad' => 'inicial', 'sesiones' => 3, 'horas' => 3.0, 'ia' => 1,
 'codigo_inicial' => "# Instruccion para el asistente (texto)\n# \"Vas a tomarme la leccion sobre ___. Hazme una pregunta a la vez.\n#  Espera mi respuesta. Si me equivoco, NO me des la respuesta: dame una\n#  pista y vuelve a preguntar. Al final dime que temas debo repasar.\"",
 'fases' => [
   ['indagar', 'Cómo estudio hoy', 'Describe exactamente qué haces para estudiar un tema. Cronométralo la próxima vez. Anota en qué momento te distraes.', 'Descripción de tu método actual con el tiempo medido.', 35],
   ['desarrollar', 'La instrucción que interroga', 'Redacta la instrucción para que el asistente te pregunte y no te explique. Incluye qué debe hacer cuando te equivoques.', 'Instrucción redactada y probada una vez.', 40],
   ['crear', 'Los dos temas', 'Estudia el tema A como siempre y el tema B con el asistente. Cronometra ambos y guarda la conversación completa del tema B.', 'Registro de las dos sesiones con tiempos y la conversación guardada.', 60],
   ['evaluar', 'Cuál funcionó mejor', 'Respóndete diez preguntas de cada tema sin ayuda. Compara los aciertos y el tiempo invertido. Decide qué harás en el próximo examen.', 'Autoevaluación comparada y decisión justificada.', 45],
 ],
 'recursos' => [
   ['plantilla', 'Registro de sesión de estudio', 'Tema, técnica, tiempo, distracciones, aciertos.'],
   ['plantilla', 'Declaración de uso de IA', 'Formato exigido en las entregas del colegio.'],
 ]],

['codigo' => 'VCP-6-18', 'titulo' => 'El semáforo inteligente del cruce del colegio',
 'objeto' => 'el simulador del semáforo',
 'resumen' => 'Programar la lógica de un semáforo con tiempos, botón peatonal y modo nocturno.',
 'descripcion' => '<p>El estudiante observa el cruce real frente al colegio, mide los tiempos y programa un semáforo que los respeta. Aparecen los ciclos, los estados y las esperas, y también la primera noción de sistema con estados: un semáforo no es una lista de instrucciones, es una máquina que cambia de estado.</p><p>Si el colegio tiene placas o kits, el mismo programa se lleva a tres LED. Si no, se simula con la pantalla y colores de texto: la lógica es idéntica.</p>',
 'pregunta' => '¿Cómo decide un semáforo cuánto tiempo dar a cada quien?',
 'contexto' => 'Equidad y desarrollo', 'concepto' => 'Sistemas',
 'perfil' => 'Solidario|Pensador', 'atl' => 'Pensamiento crítico|Organización',
 'objetivos' => 'Modelar un sistema con estados y transiciones|Controlar tiempos con ciclos y esperas|Atender una entrada del usuario (botón peatonal)|Justificar los tiempos con mediciones reales',
 'entregables' => 'Medición de los tiempos del cruce real|Diagrama de estados del semáforo|Archivo semaforo.py con modo día, noche y botón',
 'lenguaje' => 'Python', 'dificultad' => 'inicial', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "import time\n\nESTADOS = [(\"VERDE\", 20), (\"AMARILLO\", 3), (\"ROJO\", 15)]\n\nwhile True:\n    for color, segundos in ESTADOS:\n        print(color)\n        time.sleep(segundos)\n    # TODO: si alguien pulsa el boton peatonal, acorta el verde\n    # TODO: modo nocturno: solo amarillo intermitente",
 'fases' => [
   ['indagar', 'Medir el cruce real', 'Con acompañamiento, mide cuántos segundos dura cada luz y cuánto tarda una persona mayor en cruzar. Anota si alcanza.', 'Tabla de tiempos medidos y la conclusión sobre si el tiempo alcanza.', 45],
   ['desarrollar', 'Diagrama de estados', 'Dibuja los estados del semáforo y las flechas que los conectan. Marca qué provoca cada cambio: el tiempo o el botón.', 'Diagrama de estados completo con las causas de cada transición.', 45],
   ['crear', 'Programar los tres modos', 'Implementa el ciclo normal, el botón peatonal y el modo nocturno. Usa los tiempos que mediste, no los del ejemplo.', 'Archivo semaforo.py con los tres modos funcionando.', 70],
   ['evaluar', '¿Es justo con todos?', 'Comprueba si tu tiempo de cruce alcanza para alguien que camina despacio o usa silla de ruedas. Ajusta y explica el cambio.', 'Prueba de accesibilidad y ajuste justificado de los tiempos.', 40],
 ],
 'recursos' => [
   ['plantilla', 'Hoja de medición de cruce', 'Luz, duración, personas que cruzan, observaciones.'],
   ['lectura', 'Máquinas de estados para principiantes', 'Estados, transiciones y disparadores.'],
 ]],

['codigo' => 'VCP-6-19', 'titulo' => 'No todo el mundo tiene internet',
 'objeto' => 'el estudio de la brecha digital',
 'resumen' => 'Medir la conectividad real del curso y proponer una solución para quien no la tiene.',
 'descripcion' => '<p>El estudiante encuesta a su curso sobre acceso a internet y a dispositivos: si es propio o compartido, si alcanza para tareas, si se corta. Con esos datos calcula porcentajes y los compara con las cifras nacionales.</p><p>El producto es una propuesta concreta para el colegio: una sala abierta a cierta hora, préstamo de equipos, tareas descargables. Se presenta a la coordinación con los datos que la sustentan.</p>',
 'pregunta' => '¿Todos mis compañeros pueden hacer las tareas en las mismas condiciones?',
 'contexto' => 'Equidad y desarrollo', 'concepto' => 'Relaciones',
 'perfil' => 'Solidario|Indagador|De mentalidad abierta', 'atl' => 'Alfabetización informacional|Comunicación',
 'objetivos' => 'Diseñar una encuesta respetuosa sobre un tema sensible|Calcular y comparar porcentajes|Contrastar datos propios con fuentes nacionales|Proponer una solución viable con evidencia',
 'entregables' => 'Encuesta anónima aplicada al curso|Análisis con porcentajes y comparación nacional|Propuesta de una página para la coordinación',
 'lenguaje' => 'Python', 'dificultad' => 'inicial', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "respuestas = [\n    {\"internet\": \"si\", \"dispositivo\": \"compartido\"},\n    # TODO: carga las respuestas de tu curso\n]\n\n# TODO: cuenta y calcula porcentajes\n# TODO: compara con la cifra nacional que investigaste",
 'fases' => [
   ['indagar', 'Preguntar sin incomodar', 'Redacta la encuesta cuidando que nadie se sienta señalado: anónima, sin nombres, con opciones neutras. Pide a un docente que la revise antes.', 'Encuesta revisada y aprobada por un docente.', 45],
   ['desarrollar', 'Buscar la cifra nacional', 'Encuentra en una fuente oficial qué porcentaje de hogares del país tiene internet. Anota el año y la fuente exacta.', 'Dato nacional con su fuente y año.', 35],
   ['crear', 'Aplicar y contar', 'Aplica la encuesta y programa el conteo. Calcula los porcentajes y compáralos con la cifra nacional.', 'Datos del curso procesados y comparados.', 65],
   ['evaluar', 'Una propuesta que se pueda cumplir', 'Escribe la propuesta para la coordinación. Debe indicar qué se hace, quién lo hace y qué cuesta. Preséntala y anota la respuesta.', 'Propuesta de una página y registro de la reunión.', 45],
 ],
 'recursos' => [
   ['dataset', 'Cifras oficiales de conectividad', 'Enlaces a las estadísticas nacionales de acceso a internet.'],
   ['plantilla', 'Encuesta anónima de conectividad', 'Preguntas neutras revisadas para el aula.'],
 ]],
],

// =========================================================== 7.º · PAI 2 ===
'N7' => [

['codigo' => 'VCP-7-13', 'titulo' => 'Cazadores de bulos: verificar antes de compartir',
 'objeto' => 'el protocolo de verificación',
 'resumen' => 'Construir un protocolo propio de verificación y aplicarlo a cinco mensajes reales que circulan en el colegio.',
 'descripcion' => '<p>El estudiante recoge cinco mensajes que circularon de verdad en los grupos del curso y los verifica: quién lo dice, cuándo, dónde está la fuente original, si la imagen es de otro año. Documenta el resultado de cada uno.</p><p>El producto es un protocolo de cinco pasos que cabe en una tarjeta y que el curso adopta. Lo interesante es que sale de casos propios: los bulos del salón, no ejemplos de libro.</p>',
 'pregunta' => '¿Qué compruebo antes de reenviar algo que me indignó?',
 'contexto' => 'Globalización y sustentabilidad', 'concepto' => 'Comunicación',
 'perfil' => 'Pensador|Íntegro|De mentalidad abierta', 'atl' => 'Alfabetización mediática|Pensamiento crítico',
 'objetivos' => 'Rastrear la fuente original de un mensaje|Comprobar la fecha y el contexto de una imagen|Distinguir dato, opinión y montaje|Convertir el método en un protocolo transferible',
 'entregables' => 'Cinco mensajes verificados con su veredicto y evidencia|Protocolo de cinco pasos en formato tarjeta|Registro de cuántos compañeros lo adoptaron',
 'lenguaje' => 'Investigación', 'dificultad' => 'intermedio', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "# Ficha de verificacion\n# Mensaje:\n# Quien lo dice y desde cuando circula:\n# Fuente original (enlace o \"no encontrada\"):\n# La imagen es de esta fecha? Como lo compruebo:\n# Veredicto: cierto / falso / engañoso / no verificable\n# Evidencia:",
 'fases' => [
   ['indagar', 'Por qué se comparte un bulo', 'Analiza tres mensajes falsos conocidos. Identifica qué emoción provocan: miedo, indignación, ternura. Explica por qué eso los hace viajar rápido.', 'Análisis de tres bulos con la emoción que explota cada uno.', 45],
   ['desarrollar', 'Los cinco pasos', 'Redacta tu protocolo: qué compruebas primero, qué después, y cuándo decides que no puedes verificarlo. Debe caber en una tarjeta.', 'Protocolo de cinco pasos redactado.', 40],
   ['crear', 'Verificar cinco mensajes reales', 'Aplica el protocolo a cinco mensajes que hayan circulado en tu entorno. Documenta cada paso con su evidencia.', 'Cinco fichas de verificación completas.', 75],
   ['evaluar', 'Que lo use alguien más', 'Entrega la tarjeta a cinco compañeros y pídeles verificar un mensaje con ella. Anota dónde se atascaron y simplifica el protocolo.', 'Registro de cinco usos y protocolo simplificado.', 45],
 ],
 'recursos' => [
   ['lectura', 'Cómo comprobar una imagen', 'Búsqueda inversa y lectura de metadatos, paso a paso.'],
   ['plantilla', 'Tarjeta de verificación', 'Formato de bolsillo para imprimir.'],
 ]],

['codigo' => 'VCP-7-14', 'titulo' => 'Proyecto Python: gestor de gastos del curso',
 'objeto' => 'el gestor de gastos',
 'resumen' => 'Programa que registra ingresos y gastos de una actividad del curso, calcula el saldo y avisa cuando se pasa del presupuesto.',
 'descripcion' => '<p>El curso siempre organiza algo: una salida, una rifa, un detalle de fin de año. El estudiante programa el gestor que lleva las cuentas: registra movimientos, calcula el saldo, agrupa por categoría y avisa cuando el gasto supera lo previsto.</p><p>La exigencia es que las cuentas cuadren al centavo con las de un compañero que las lleve en papel. Cuando no cuadran, hay que encontrar por qué, y ahí aparece la primera conversación seria sobre redondeo y errores de captura.</p>',
 'pregunta' => '¿Cómo sé que las cuentas de mi programa son las correctas?',
 'contexto' => 'Equidad y desarrollo', 'concepto' => 'Sistemas',
 'perfil' => 'Íntegro|Organizado|Pensador', 'atl' => 'Organización|Pensamiento crítico',
 'objetivos' => 'Guardar registros estructurados en archivo|Agrupar y sumar por categoría|Comparar contra un presupuesto|Verificar el resultado con un método independiente',
 'entregables' => 'Archivo gastos.py con registro, saldo y alertas|Cuentas reales de una actividad del curso|Comprobación contra el registro en papel',
 'lenguaje' => 'Python', 'dificultad' => 'intermedio', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "movimientos = []   # {\"fecha\":..,\"concepto\":..,\"categoria\":..,\"monto\":..}\nPRESUPUESTO = {\"transporte\": 200000, \"comida\": 150000}\n\ndef registrar(fecha, concepto, categoria, monto):\n    movimientos.append({\"fecha\": fecha, \"concepto\": concepto,\n                        \"categoria\": categoria, \"monto\": monto})\n\n# TODO: saldo()  suma ingresos menos gastos\n# TODO: por_categoria()  agrupa y compara con PRESUPUESTO\n# TODO: guarda y carga desde archivo",
 'fases' => [
   ['indagar', 'Cómo se llevan las cuentas hoy', 'Pregunta a quien haya manejado el dinero de una actividad del curso. Averigua qué anotaba, dónde y qué se le complicó.', 'Entrevista con al menos cinco datos concretos del método actual.', 40],
   ['desarrollar', 'Categorías y presupuesto', 'Define las categorías de gasto y el presupuesto de cada una. Decide qué hace el programa cuando una categoría se pasa.', 'Lista de categorías, presupuesto y regla de alerta.', 40],
   ['crear', 'Programar y llevar las cuentas', 'Implementa el gestor y lleva con él las cuentas reales de una actividad. Guarda los movimientos en archivo.', 'Archivo gastos.py y las cuentas reales cargadas.', 75],
   ['evaluar', 'Que cuadre al centavo', 'Compara tu saldo con el que llevó un compañero en papel. Si no cuadran, encuentra la causa exacta y corrígela.', 'Comparación de los dos saldos y explicación de la diferencia.', 45],
 ],
 'recursos' => [
   ['plantilla', 'Libro de cuentas en papel', 'Para llevar el control paralelo y comparar.'],
 ]],

['codigo' => 'VCP-7-15', 'titulo' => 'Robot seguidor de línea: sensores y decisiones',
 'objeto' => 'el robot seguidor de línea',
 'resumen' => 'Programar la lógica de un seguidor de línea y ajustarla midiendo cuántas veces se sale del recorrido.',
 'descripcion' => '<p>El estudiante programa la lógica clásica de la robótica educativa: leer dos sensores y decidir si avanzar, girar a la izquierda o a la derecha. Con placa física si el colegio la tiene; con un simulador de rejilla si no, porque la lógica que se aprende es la misma.</p><p>La parte que enseña de verdad es el ajuste: el primer programa siempre zigzaguea o se sale en las curvas cerradas. El estudiante mide cuántas veces se sale por vuelta y ajusta hasta bajar ese número, con datos y no por ensayo ciego.</p>',
 'pregunta' => '¿Cómo decide un robot hacia dónde girar si solo sabe si ve negro o blanco?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Pensador|Audaz|Reflexivo', 'atl' => 'Pensamiento crítico|Colaboración',
 'objetivos' => 'Leer entradas de sensores y decidir con condicionales|Construir una tabla de verdad de dos sensores|Medir el desempeño con un indicador objetivo|Ajustar parámetros con datos, no por intuición',
 'entregables' => 'Tabla de verdad de las cuatro combinaciones|Programa del seguidor|Registro de salidas por vuelta antes y después del ajuste',
 'lenguaje' => 'Python', 'dificultad' => 'intermedio', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "# izquierda / derecha: True si el sensor ve la linea negra\ndef decidir(izquierda, derecha):\n    if izquierda and derecha:\n        return \"adelante\"\n    # TODO: completa las otras tres combinaciones\n    return \"parar\"\n\n# Tabla de verdad\n# | izq | der | accion |\n# |  V  |  V  | adelante |\n# |  V  |  F  |          |\n# |  F  |  V  |          |\n# |  F  |  F  |          |",
 'fases' => [
   ['indagar', 'Qué ve un sensor', 'Investiga cómo distingue el negro del blanco un sensor infrarrojo. Prueba con distintos materiales y anota cuáles confunden al sensor.', 'Explicación del funcionamiento y lista de tres materiales que lo confunden.', 45],
   ['desarrollar', 'La tabla de verdad', 'Completa las cuatro combinaciones posibles de los dos sensores y decide la acción de cada una. Justifica el caso en que ninguno ve la línea.', 'Tabla de verdad completa con la justificación del caso perdido.', 40],
   ['crear', 'Programar y recorrer', 'Implementa la lógica y haz que el robot recorra la pista tres veces. Cuenta cuántas veces se sale en cada vuelta.', 'Programa funcionando y registro de tres vueltas.', 80],
   ['evaluar', 'Bajar las salidas', 'Ajusta velocidad o tiempos de giro y vuelve a medir. Documenta qué cambio produjo la mayor mejora y por qué.', 'Tabla de mediciones antes y después con el análisis del ajuste.', 45],
 ],
 'recursos' => [
   ['plantilla', 'Pista de línea negra', 'Trazado imprimible con recta, curva suave y curva cerrada.'],
   ['codigo', 'simulador_linea.py', 'Simulador de rejilla para trabajar sin placa física.'],
 ]],

['codigo' => 'VCP-7-16', 'titulo' => 'La IA como corrector: qué acepto y qué rechazo',
 'objeto' => 'el texto corregido con criterio',
 'resumen' => 'Pedir a un asistente que corrija un texto propio y decidir sugerencia por sugerencia cuál se aplica y por qué.',
 'descripcion' => '<p>El estudiante entrega al asistente un texto suyo de otra asignatura y le pide correcciones de ortografía, claridad y estructura. Cada sugerencia se anota y se decide: se acepta, se modifica o se rechaza, siempre con el motivo escrito.</p><p>El aprendizaje aparece al rechazar: cuando el asistente propone una palabra más elegante pero que el estudiante no usaría nunca, entender por qué rechazarla es entender qué es la voz propia. El texto final sigue sonando a quien lo escribió.</p>',
 'pregunta' => '¿Sigue siendo mío un texto que otro corrigió?',
 'contexto' => 'Expresión personal y cultural', 'concepto' => 'Comunicación',
 'perfil' => 'Íntegro|Reflexivo|Buen comunicador', 'atl' => 'Reflexión|Pensamiento crítico',
 'objetivos' => 'Distinguir corrección de reescritura|Evaluar una sugerencia antes de aplicarla|Conservar la voz propia en un texto revisado|Declarar la asistencia recibida con detalle',
 'entregables' => 'Texto original y texto final|Tabla de todas las sugerencias con la decisión y el motivo|Reflexión sobre las sugerencias rechazadas',
 'lenguaje' => 'Lenguaje natural', 'dificultad' => 'intermedio', 'sesiones' => 3, 'horas' => 3.0, 'ia' => 1,
 'codigo_inicial' => "# Tabla de sugerencias\n# | # | Que sugirio | Tipo (ortografia/claridad/estilo) | Decision | Motivo |\n#\n# Regla: si rechazas menos de 3 sugerencias, probablemente no estas leyendo,\n# solo aceptando.",
 'fases' => [
   ['indagar', 'Tipos de corrección', 'Clasifica diez correcciones posibles en ortográficas, de claridad y de estilo. Explica cuáles son objetivas y cuáles son cuestión de gusto.', 'Clasificación de diez correcciones con la distinción justificada.', 40],
   ['desarrollar', 'Qué le voy a pedir', 'Redacta la instrucción: qué tipos de corrección quieres, cuáles no, y que te explique el motivo de cada una en vez de reescribir el texto.', 'Instrucción redactada con los límites explícitos.', 35],
   ['crear', 'Corregir con criterio', 'Somete tu texto y registra cada sugerencia. Decide una por una y aplica solo las que aceptes o modifiques.', 'Tabla completa de sugerencias y texto final.', 60],
   ['evaluar', '¿Suena a mí?', 'Pide a un compañero que lea el texto original y el final y diga si los escribió la misma persona. Analiza las sugerencias que rechazaste.', 'Opinión del compañero y reflexión sobre los rechazos.', 40],
 ],
 'recursos' => [
   ['plantilla', 'Registro de sugerencias', 'Sugerencia, tipo, decisión y motivo.'],
 ]],

['codigo' => 'VCP-7-17', 'titulo' => 'Proyecto Python: reproductor de listas del curso',
 'objeto' => 'el gestor de listas',
 'resumen' => 'Programa que arma listas de reproducción por criterios y las guarda, con la música o los podcasts que use el curso.',
 'descripcion' => '<p>El estudiante construye un gestor que guarda canciones o pódcast con su duración, género y valoración, y arma listas según criterios: máximo de minutos, un género, sin repetir artista. Es un ejercicio de filtrado y ordenamiento con un producto que apetece usar.</p><p>El requisito interesante es el de duración: armar una lista que dure exactamente lo que dura el recreo obliga a pensar en acumulación y en qué hacer cuando ninguna combinación cuadra exacto.</p>',
 'pregunta' => '¿Cómo elijo automáticamente un subconjunto que cumpla varias condiciones a la vez?',
 'contexto' => 'Expresión personal y cultural', 'concepto' => 'Lógica',
 'perfil' => 'Pensador|Buen comunicador', 'atl' => 'Pensamiento crítico|Organización',
 'objetivos' => 'Filtrar listas con varias condiciones|Ordenar por criterios distintos|Acumular hasta un límite|Guardar y recuperar datos en archivo',
 'entregables' => 'Archivo listas.py con al menos tres criterios|Catálogo de veinte piezas cargado|Tres listas generadas y valoradas por compañeros',
 'lenguaje' => 'Python', 'dificultad' => 'intermedio', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "catalogo = [\n    {\"titulo\": \"...\", \"artista\": \"...\", \"genero\": \"...\", \"minutos\": 3.5, \"nota\": 4},\n]\n\ndef lista_por_duracion(catalogo, minutos_max):\n    # TODO: acumula hasta acercarte a minutos_max sin pasarte\n    pass\n\n# TODO: lista_por_genero()  y  lista_sin_repetir_artista()",
 'fases' => [
   ['indagar', 'Qué hace buena a una lista', 'Pregunta a cinco compañeros qué les molesta de las listas automáticas. Anota los tres reclamos más repetidos.', 'Resultado de la consulta con los tres reclamos principales.', 35],
   ['desarrollar', 'Los criterios', 'Define los tres criterios que programarás y qué hace cada uno cuando no encuentra suficientes piezas.', 'Especificación de los tres criterios con el caso de datos insuficientes.', 40],
   ['crear', 'Programar el gestor', 'Carga veinte piezas reales y programa los tres criterios. Genera una lista con cada uno.', 'Archivo listas.py y las tres listas generadas.', 70],
   ['evaluar', 'Que la escuchen', 'Tres compañeros valoran de 1 a 5 cada lista generada. Anota los comentarios y ajusta el criterio peor valorado.', 'Valoraciones registradas y ajuste aplicado.', 40],
 ],
 'recursos' => [
   ['lectura', 'Filtrar y ordenar listas', 'sorted, filter y expresiones de lista.'],
 ]],

['codigo' => 'VCP-7-18', 'titulo' => 'Robótica: el invernadero que se riega solo',
 'objeto' => 'el sistema de riego automático',
 'resumen' => 'Diseñar y programar un sistema que decide cuándo regar según humedad, hora y días sin lluvia.',
 'descripcion' => '<p>El estudiante diseña un sistema de riego para las materas del colegio: lee la humedad del suelo, mira la hora y decide si riega y por cuánto tiempo. Con sensor real o con datos simulados de una semana, la lógica de decisión es la misma.</p><p>La actividad exige justificar cada umbral con una fuente o con una medición, no con un número inventado. Y exige pensar en los fallos: qué pasa si el sensor se daña y reporta siempre seco.</p>',
 'pregunta' => '¿Qué debe comprobar una máquina antes de tomar una decisión que puede hacer daño?',
 'contexto' => 'Globalización y sustentabilidad', 'concepto' => 'Sistemas',
 'perfil' => 'Solidario|Pensador|Reflexivo', 'atl' => 'Pensamiento crítico|Transferencia',
 'objetivos' => 'Combinar varias entradas en una decisión|Justificar umbrales con evidencia|Prever el fallo de un sensor|Registrar el comportamiento del sistema en el tiempo',
 'entregables' => 'Tabla de umbrales con su justificación|Programa riego.py con la lógica y el control de fallo|Registro de una semana de decisiones',
 'lenguaje' => 'Python', 'dificultad' => 'intermedio', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "HUMEDAD_MINIMA = 30      # TODO: justifica este numero\nHORA_INICIO, HORA_FIN = 6, 9\n\ndef decidir_riego(humedad, hora, dias_sin_lluvia, sensor_ok):\n    if not sensor_ok:\n        return \"no regar: sensor sin datos fiables\"\n    # TODO: combina las tres condiciones\n    return \"no regar\"",
 'fases' => [
   ['indagar', 'Cuánta agua necesita', 'Averigua con una fuente qué humedad necesita la planta que vas a regar y a qué hora conviene hacerlo. Cita la fuente.', 'Ficha de la planta con humedad, horario y fuente citada.', 45],
   ['desarrollar', 'Umbrales y fallos', 'Define los umbrales y qué hace el sistema si el sensor da un valor imposible o no responde. Escribe la tabla de decisión completa.', 'Tabla de decisión con los umbrales justificados y el caso de fallo.', 45],
   ['crear', 'Programar y registrar', 'Implementa la lógica y hazla funcionar durante una semana con datos reales o simulados. Registra cada decisión con su motivo.', 'Programa funcionando y registro de siete días de decisiones.', 80],
   ['evaluar', '¿Regó cuando debía?', 'Compara las decisiones del sistema con lo que habría hecho una persona observando la planta. Explica cada desacuerdo.', 'Comparación de siete días y análisis de los desacuerdos.', 45],
 ],
 'recursos' => [
   ['dataset', 'Semana de humedad simulada', 'Datos por hora para trabajar sin sensor físico.'],
   ['lectura', 'Cuando un sensor miente', 'Valores imposibles y control de plausibilidad.'],
 ]],

['codigo' => 'VCP-7-19', 'titulo' => 'Videojuegos y tiempo: medir en vez de opinar',
 'objeto' => 'el estudio de tiempo de pantalla',
 'resumen' => 'Medir el propio tiempo de pantalla durante dos semanas y contrastar los datos con lo que uno creía.',
 'descripcion' => '<p>El estudiante estima cuánto tiempo cree que pasa frente a pantallas y luego lo mide durante dos semanas. La diferencia entre lo estimado y lo medido suele ser grande, y ese hueco es el contenido de la actividad.</p><p>Se trabaja también la lectura crítica de titulares sobre videojuegos: qué dice el estudio original frente a lo que dice el titular. El estudiante termina con un juicio propio y fundamentado, ni alarmista ni complaciente.</p>',
 'pregunta' => '¿Lo que creo sobre mis hábitos coincide con lo que hago?',
 'contexto' => 'Identidades y relaciones', 'concepto' => 'Relaciones',
 'perfil' => 'Reflexivo|Equilibrado|Pensador', 'atl' => 'Autogestión|Alfabetización mediática',
 'objetivos' => 'Estimar y luego medir un hábito propio|Calcular promedios y detectar patrones|Comparar un titular con su estudio original|Formular un juicio con evidencia propia',
 'entregables' => 'Estimación inicial escrita antes de medir|Registro de catorce días|Análisis de un titular frente a su estudio|Conclusión personal con decisiones',
 'lenguaje' => 'Python', 'dificultad' => 'intermedio', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "dias = [\n    {\"dia\": \"lunes\", \"juegos\": 60, \"redes\": 45, \"estudio\": 90},  # minutos\n]\n\n# TODO: promedio por categoria\n# TODO: dia con mas tiempo y dia con menos\n# TODO: compara entre semana y fin de semana",
 'fases' => [
   ['indagar', 'Lo que creo', 'Antes de medir nada, escribe cuántos minutos diarios crees que dedicas a juegos, redes y estudio. Guarda esa hoja cerrada.', 'Estimación inicial escrita y guardada.', 30],
   ['desarrollar', 'Cómo voy a medir', 'Decide qué cuentas como tiempo de pantalla y cómo lo registrarás sin olvidarte. Define las categorías.', 'Método de medición con las categorías definidas.', 35],
   ['crear', 'Catorce días', 'Registra cada día durante dos semanas y programa el análisis: promedios, extremos y comparación entre semana y fin de semana.', 'Registro de catorce días y análisis programado.', 70],
   ['evaluar', 'Estimado contra medido', 'Abre tu estimación inicial y compárala. Analiza además un titular sobre videojuegos frente al estudio que cita. Decide un cambio concreto.', 'Comparación, análisis del titular y un cambio concreto de hábito.', 50],
 ],
 'recursos' => [
   ['plantilla', 'Registro diario de pantalla', 'Catorce filas con las tres categorías.'],
   ['lectura', 'De un estudio a un titular', 'Cómo se exagera un resultado al resumirlo.'],
 ]],
],

// =========================================================== 8.º · PAI 3 ===
'N8' => [

['codigo' => 'VCP-8-13', 'titulo' => 'Quién se queda con mis datos: leer una política de privacidad',
 'objeto' => 'el análisis de la política de privacidad',
 'resumen' => 'Leer de verdad la política de una aplicación que se usa a diario y traducirla a lenguaje claro.',
 'descripcion' => '<p>El estudiante toma la política de privacidad de una aplicación que usa todos los días y la lee entera. Extrae qué datos recoge, con quién los comparte, cuánto los conserva y qué derechos tiene el usuario. Después la reescribe en una página que cualquiera entienda.</p><p>Casi siempre aparece alguna cláusula que sorprende. El estudiante la señala y decide, con argumentos, si sigue usando la aplicación, si cambia algún permiso o si busca una alternativa.</p>',
 'pregunta' => '¿Qué acepté exactamente cuando pulsé «aceptar»?',
 'contexto' => 'Equidad y desarrollo', 'concepto' => 'Relaciones',
 'perfil' => 'Informado e instruido|Íntegro|Pensador', 'atl' => 'Alfabetización mediática|Pensamiento crítico',
 'objetivos' => 'Localizar información concreta en un texto legal|Distinguir dato recogido, inferido y compartido|Traducir lenguaje jurídico a lenguaje claro|Tomar una decisión informada sobre un servicio',
 'entregables' => 'Ficha con los cinco puntos clave y su cita textual|Reescritura de una página en lenguaje claro|Decisión razonada sobre el uso del servicio',
 'lenguaje' => 'Investigación', 'dificultad' => 'intermedio', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "# Ficha de politica de privacidad\n# Aplicacion:                          Fecha de la version:\n# 1. Que datos recoge (cita textual):\n# 2. Que datos INFIERE de mi:\n# 3. Con quien los comparte:\n# 4. Cuanto tiempo los conserva:\n# 5. Como pido que los borren:\n# La clausula que mas me sorprendio:",
 'fases' => [
   ['indagar', 'Dato recogido y dato inferido', 'Explica con ejemplos la diferencia entre un dato que entregas (tu edad) y uno que deducen (tus intereses). Encuentra tres ejemplos de datos inferidos.', 'Explicación con tres ejemplos de inferencia.', 45],
   ['desarrollar', 'Qué voy a buscar', 'Define los cinco puntos que buscarás en el documento y cómo los citarás. Elige la aplicación y localiza su política vigente.', 'Guía de lectura y política localizada con su fecha de versión.', 40],
   ['crear', 'Leerla entera y traducirla', 'Completa la ficha con citas textuales y reescribe la política en una página que entienda un estudiante de 6.º.', 'Ficha con citas y versión en lenguaje claro.', 80],
   ['evaluar', 'Que la entiendan', 'Dale tu versión a dos estudiantes menores y hazles tres preguntas sobre ella. Corrige lo que no entendieron y decide qué harás con la aplicación.', 'Prueba de comprensión, correcciones y decisión razonada.', 45],
 ],
 'recursos' => [
   ['lectura', 'Glosario de términos de privacidad', 'Terceros, finalidad, base legítima, retención.'],
 ]],

['codigo' => 'VCP-8-14', 'titulo' => 'Proyecto Python: agenda de tareas con recordatorios',
 'objeto' => 'la agenda de tareas',
 'resumen' => 'Aplicación completa que guarda tareas con fecha y prioridad, avisa de lo urgente y mide cumplimiento.',
 'descripcion' => '<p>Proyecto de integración: archivos, fechas, ordenamiento, funciones y menú. El estudiante construye la agenda que va a usar el resto del año escolar, con prioridades, fechas límite y un informe semanal de cuánto cumplió.</p><p>Lo que diferencia esta actividad de un ejercicio es la exigencia de uso real durante tres semanas y el informe final con datos: qué porcentaje de tareas entregó a tiempo antes y después de usarla.</p>',
 'pregunta' => '¿Un programa puede cambiar mi forma de organizarme o solo la refleja?',
 'contexto' => 'Identidades y relaciones', 'concepto' => 'Sistemas',
 'perfil' => 'Organizado|Reflexivo|Íntegro', 'atl' => 'Autogestión|Organización',
 'objetivos' => 'Trabajar con fechas y plazos|Ordenar por varios criterios|Persistir datos entre ejecuciones|Evaluar el efecto de una herramienta con datos propios',
 'entregables' => 'Archivo agenda.py con las cinco operaciones|Tres semanas de uso real|Informe de cumplimiento antes y después',
 'lenguaje' => 'Python', 'dificultad' => 'intermedio', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "from datetime import date, timedelta\nimport json\n\ndef cargar():\n    try:\n        with open(\"agenda.json\", encoding=\"utf-8\") as f:\n            return json.load(f)\n    except FileNotFoundError:\n        return []\n\n# TODO: agregar, listar (ordenada), completar, urgentes(dias), informe()",
 'fases' => [
   ['indagar', 'Mi cumplimiento actual', 'Revisa las últimas tres semanas: cuántas tareas tuviste y cuántas entregaste a tiempo. Ese porcentaje es tu punto de partida.', 'Porcentaje de cumplimiento de las tres semanas previas.', 40],
   ['desarrollar', 'Qué guarda cada tarea', 'Define los campos de una tarea y cómo se ordenan. Decide qué significa «urgente» en tu agenda y por qué.', 'Estructura de la tarea y definición de urgencia justificada.', 40],
   ['crear', 'Programar y usar tres semanas', 'Implementa las cinco operaciones con persistencia en JSON. Úsala a diario durante tres semanas.', 'Archivo agenda.py y el JSON con el uso real.', 85],
   ['evaluar', '¿Cumplí más?', 'Calcula tu cumplimiento con la agenda y compáralo con el punto de partida. Analiza si la mejora vino del programa o de estar midiéndote.', 'Comparación de los dos porcentajes y análisis honesto de la causa.', 50],
 ],
 'recursos' => [
   ['lectura', 'JSON para guardar datos', 'Cargar, guardar y qué pasa si el archivo se corrompe.'],
 ]],

['codigo' => 'VCP-8-15', 'titulo' => 'Robótica: el clasificador de residuos del colegio',
 'objeto' => 'el clasificador de residuos',
 'resumen' => 'Sistema que decide en qué caneca va un residuo a partir de sus propiedades, con la lógica que usan los sensores reales.',
 'descripcion' => '<p>El estudiante estudia cómo se clasifican los residuos en el colegio y programa un sistema de decisión basado en propiedades medibles: peso, si es metálico, si es transparente, si flota. Con sensores reales o con entrada manual, la lógica de decisión es lo que se evalúa.</p><p>El proyecto conecta robótica con sustentabilidad y con una pregunta incómoda: aunque la máquina clasifique bien, ¿el colegio separa de verdad después? La respuesta se investiga y se documenta.</p>',
 'pregunta' => '¿De qué sirve clasificar bien si después todo termina en el mismo camión?',
 'contexto' => 'Globalización y sustentabilidad', 'concepto' => 'Sistemas',
 'perfil' => 'Solidario|Indagador|Íntegro', 'atl' => 'Pensamiento crítico|Alfabetización informacional',
 'objetivos' => 'Traducir propiedades físicas en reglas de decisión|Encadenar condiciones en un árbol|Medir la exactitud del clasificador|Investigar la cadena completa del residuo',
 'entregables' => 'Árbol de decisión de al menos cuatro propiedades|Programa clasificador.py|Prueba con veinte residuos reales y su exactitud|Informe sobre qué pasa después en el colegio',
 'lenguaje' => 'Python', 'dificultad' => 'intermedio', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "def clasificar(metalico, transparente, flota, peso_g):\n    if metalico:\n        return \"metal\"\n    # TODO: completa el arbol con las demas propiedades\n    return \"no reciclable\"\n\n# Prueba con 20 residuos reales y anota aciertos y errores",
 'fases' => [
   ['indagar', 'Cómo se clasifica aquí', 'Averigua qué canecas hay en el colegio y qué va en cada una. Pregunta a servicios generales qué pasa con los residuos después de recogerlos.', 'Guía de clasificación del colegio y respuesta sobre el destino final.', 50],
   ['desarrollar', 'El árbol de decisión', 'Elige cuatro propiedades medibles y construye el árbol que lleva de ellas a cada caneca. Marca los casos ambiguos.', 'Árbol de decisión dibujado con los casos ambiguos señalados.', 45],
   ['crear', 'Programar y probar', 'Implementa el clasificador y pruébalo con veinte residuos reales. Anota cada acierto y cada error.', 'Programa y tabla de veinte pruebas con la exactitud calculada.', 80],
   ['evaluar', 'La cadena completa', 'Analiza tus errores y mejora el árbol. Escribe un informe sobre qué pasa con los residuos después del colegio y qué recomiendas.', 'Árbol mejorado, exactitud final e informe con recomendaciones.', 50],
 ],
 'recursos' => [
   ['plantilla', 'Guía de clasificación de residuos', 'Código de colores nacional y qué va en cada caneca.'],
 ]],

['codigo' => 'VCP-8-16', 'titulo' => 'La IA que me explica lo que no entiendo',
 'objeto' => 'el método de estudio asistido',
 'resumen' => 'Usar la IA para desatascarse en un tema difícil, con la regla de reformular con palabras propias antes de seguir.',
 'descripcion' => '<p>El estudiante elige un tema que de verdad no entiende y trabaja con el asistente bajo una regla estricta: después de cada explicación debe reformularla con sus propias palabras y el asistente debe señalarle qué entendió mal. Solo entonces continúa.</p><p>La actividad enseña una técnica de estudio real —la explicación activa— usando la IA como interlocutor infatigable. Y enseña su límite: si no puedes reformular, no entendiste, por muy claro que sonara.</p>',
 'pregunta' => '¿Cómo sé que entendí algo y no solo que me sonó claro?',
 'contexto' => 'Identidades y relaciones', 'concepto' => 'Comunicación',
 'perfil' => 'Reflexivo|Indagador|Íntegro', 'atl' => 'Autogestión|Reflexión|Comunicación',
 'objetivos' => 'Formular con precisión qué es lo que no se entiende|Reformular una explicación con palabras propias|Detectar la comprensión aparente|Documentar el proceso de aprendizaje',
 'entregables' => 'Registro completo de la conversación|Las tres reformulaciones propias con las correcciones recibidas|Explicación final del tema a un compañero, grabada o presencial',
 'lenguaje' => 'Lenguaje natural', 'dificultad' => 'intermedio', 'sesiones' => 3, 'horas' => 3.0, 'ia' => 1,
 'codigo_inicial' => "# Instruccion para el asistente\n# \"Explicame ___ paso a paso. Despues de CADA paso, para y pideme que te lo\n#  repita con mis palabras. Si mi version tiene un error, senalalo sin darme\n#  la respuesta corregida: hazme una pregunta que me lleve a verlo.\"",
 'fases' => [
   ['indagar', 'Dónde me atasco exactamente', 'No basta con «no entiendo fracciones». Localiza el paso concreto donde se te pierde el razonamiento y escríbelo en una frase.', 'El punto exacto de atasco formulado en una frase.', 35],
   ['desarrollar', 'La regla de la reformulación', 'Redacta la instrucción que obliga al asistente a pedirte reformular. Define qué hará cuando tu reformulación tenga un error.', 'Instrucción redactada con la regla de corrección socrática.', 35],
   ['crear', 'La sesión', 'Trabaja el tema con esa regla. Guarda la conversación entera, incluidas tus reformulaciones equivocadas: son la evidencia del aprendizaje.', 'Conversación completa con al menos tres reformulaciones.', 60],
   ['evaluar', 'Explicárselo a alguien', 'Explica el tema a un compañero que no lo sepa, sin notas. Anota qué preguntas te hizo que no supiste responder y vuelve sobre eso.', 'Registro de la explicación y los vacíos que quedaron.', 45],
 ],
 'recursos' => [
   ['lectura', 'La técnica de la explicación activa', 'Por qué explicar consolida más que releer.'],
 ]],

['codigo' => 'VCP-8-17', 'titulo' => 'Proyecto Python: encuesta del colegio de punta a punta',
 'objeto' => 'el sistema de encuesta',
 'resumen' => 'Diseñar, aplicar, procesar y presentar una encuesta real del colegio, con el programa que hace todo el trabajo.',
 'descripcion' => '<p>El estudiante lleva una encuesta real de principio a fin: define la pregunta de investigación, diseña el instrumento, lo aplica a cincuenta personas, procesa los datos con su programa y presenta los resultados a quien pueda actuar sobre ellos.</p><p>Es la actividad que más se parece al trabajo real con datos: la parte de programación es la mitad; la otra mitad es diseñar bien, cuidar la muestra y no afirmar más de lo que los datos permiten.</p>',
 'pregunta' => '¿Qué puedo afirmar con cincuenta respuestas y qué no?',
 'contexto' => 'Equidad y desarrollo', 'concepto' => 'Relaciones',
 'perfil' => 'Indagador|Íntegro|Buen comunicador', 'atl' => 'Alfabetización informacional|Comunicación|Organización',
 'objetivos' => 'Formular una pregunta de investigación acotada|Diseñar un instrumento sin sesgos|Procesar y cruzar respuestas con código|Comunicar resultados sin sobreinterpretar',
 'entregables' => 'Pregunta de investigación y cuestionario|Cincuenta respuestas recogidas|Programa de procesamiento con cruces|Presentación de resultados a un responsable',
 'lenguaje' => 'Python', 'dificultad' => 'avanzado', 'sesiones' => 6, 'horas' => 6.0, 'ia' => 1,
 'codigo_inicial' => "import csv\n\ndef cargar(ruta):\n    with open(ruta, encoding=\"utf-8\") as f:\n        return list(csv.DictReader(f))\n\n# TODO: frecuencias por pregunta\n# TODO: cruce de dos preguntas (tabla de contingencia)\n# TODO: exporta el resumen a un archivo",
 'fases' => [
   ['indagar', 'Una pregunta que valga la pena', 'Propón tres preguntas de investigación sobre el colegio y descarta dos. Explica por qué la elegida se puede responder con una encuesta.', 'Tres propuestas y la justificación del descarte.', 45],
   ['desarrollar', 'Instrumento y muestra', 'Diseña el cuestionario y decide a quién preguntarás y por qué. Define qué cruce de preguntas te interesa antes de recoger nada.', 'Cuestionario, plan de muestreo y el cruce previsto.', 50],
   ['crear', 'Aplicar y procesar', 'Recoge cincuenta respuestas y programa el procesamiento: frecuencias, porcentajes y el cruce definido.', 'Datos recogidos y programa que produce el resumen.', 95],
   ['evaluar', 'Qué puedo afirmar', 'Redacta las conclusiones y marca cuáles se sostienen con tus datos y cuáles serían una exageración. Presenta a un responsable del colegio.', 'Conclusiones con su nivel de respaldo y acta de la presentación.', 55],
 ],
 'recursos' => [
   ['plantilla', 'Diseño de cuestionario', 'Tipos de pregunta y errores que sesgan.'],
   ['lectura', 'Muestra y representatividad', 'Por qué cincuenta respuestas no siempre hablan por todos.'],
 ]],

['codigo' => 'VCP-8-18', 'titulo' => 'Robótica: brazo con tres servos y secuencia programada',
 'objeto' => 'el brazo robótico',
 'resumen' => 'Programar un brazo de tres articulaciones para que repita una secuencia con precisión y se detenga ante un obstáculo.',
 'descripcion' => '<p>Continuación natural del brazo de cartón de 6.º, ahora con control real: tres servomotores, ángulos, tiempos de espera y una parada de seguridad. El estudiante programa una secuencia que traslada un objeto de un punto a otro y la repite diez veces.</p><p>La medición es de precisión: cuántas de las diez repeticiones dejaron el objeto dentro del círculo objetivo. Ese número obliga a pensar en holguras mecánicas, en velocidad y en el orden de los movimientos.</p>',
 'pregunta' => '¿Por qué la misma orden no produce siempre el mismo resultado?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Pensador|Audaz|Reflexivo', 'atl' => 'Pensamiento crítico|Colaboración|Organización',
 'objetivos' => 'Controlar varios actuadores en secuencia|Introducir esperas y comprobaciones de seguridad|Medir la repetibilidad de un sistema físico|Explicar la diferencia entre lo programado y lo ejecutado',
 'entregables' => 'Secuencia programada con ángulos y tiempos|Registro de diez repeticiones con el resultado de cada una|Análisis de la variación y ajustes aplicados',
 'lenguaje' => 'Python', 'dificultad' => 'avanzado', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "SECUENCIA = [\n    (\"base\", 0, 0.5),      # articulacion, angulo, espera en segundos\n    (\"hombro\", 45, 0.5),\n    # TODO: completa hasta soltar el objeto en el destino\n]\n\ndef ejecutar(secuencia, hay_obstaculo):\n    for parte, angulo, espera in secuencia:\n        if hay_obstaculo():\n            return \"parada de seguridad\"\n        # TODO: mueve y espera\n    return \"secuencia completa\"",
 'fases' => [
   ['indagar', 'De la mano al servo', 'Haz el movimiento tú mismo y descompónlo. Mide con transportador los ángulos de cada articulación en cada punto clave.', 'Descomposición del movimiento con los ángulos medidos.', 45],
   ['desarrollar', 'Secuencia y seguridad', 'Escribe la secuencia completa con ángulos y esperas. Define qué detecta la parada de seguridad y qué hace el brazo al activarse.', 'Secuencia documentada y protocolo de parada de seguridad.', 50],
   ['crear', 'Programar y repetir diez veces', 'Implementa la secuencia y ejecútala diez veces seguidas. Marca en el suelo el círculo objetivo y anota cada resultado.', 'Programa funcionando y registro de las diez repeticiones.', 85],
   ['evaluar', 'Por qué varía', 'Analiza las repeticiones fallidas: holgura, velocidad, orden. Aplica un ajuste, repite diez veces y compara la precisión.', 'Análisis de la variación y comparación antes y después del ajuste.', 50],
 ],
 'recursos' => [
   ['lectura', 'Servomotores: ángulo, par y holgura', 'Por qué el servo no llega exactamente donde se le pide.'],
   ['codigo', 'simulador_brazo.py', 'Simulador para trabajar sin hardware.'],
 ]],

['codigo' => 'VCP-8-19', 'titulo' => 'El algoritmo que decide qué veo',
 'objeto' => 'el estudio del algoritmo de recomendación',
 'resumen' => 'Experimentar con una cuenta nueva para observar cómo un sistema de recomendación aprende y encierra.',
 'descripcion' => '<p>Con acompañamiento y en una cuenta creada para la actividad, el estudiante observa qué le recomienda una plataforma al principio y cómo cambia después de veinte interacciones dirigidas hacia un solo tema. Registra las diez primeras recomendaciones de cada momento.</p><p>El resultado hace visible la burbuja: en pocos pasos, el sistema deja de mostrar variedad. El estudiante explica el mecanismo y propone qué haría una persona para salir de ahí a propósito.</p>',
 'pregunta' => '¿Elijo yo lo que veo, o el sistema elige por mí a partir de lo que ya vi?',
 'contexto' => 'Globalización y sustentabilidad', 'concepto' => 'Relaciones',
 'perfil' => 'Pensador|De mentalidad abierta|Íntegro', 'atl' => 'Alfabetización mediática|Pensamiento crítico',
 'objetivos' => 'Diseñar una observación con condiciones controladas|Registrar cambios en un sistema a lo largo del tiempo|Explicar el mecanismo de la retroalimentación|Proponer estrategias conscientes de consumo',
 'entregables' => 'Registro de las recomendaciones en tres momentos|Análisis de la variedad perdida|Explicación del mecanismo|Tres estrategias para diversificar lo que uno ve',
 'lenguaje' => 'Investigación', 'dificultad' => 'intermedio', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "# Registro de recomendaciones\n# Momento 0 (cuenta nueva): 10 titulos y su tema\n# Momento 1 (tras 10 interacciones dirigidas): 10 titulos y su tema\n# Momento 2 (tras 20 interacciones): 10 titulos y su tema\n#\n# Indicador: cuantos TEMAS DISTINTOS aparecen en cada momento",
 'fases' => [
   ['indagar', 'Qué es recomendar', 'Investiga en qué se basa un sistema de recomendación. Escribe con tus palabras qué señales cree que le estás dando cuando ves un video entero.', 'Explicación propia con al menos cuatro señales identificadas.', 45],
   ['desarrollar', 'Diseñar la observación', 'Con tu docente, define el protocolo: qué cuenta usas, cuántas interacciones haces, hacia qué tema y qué registras exactamente en cada momento.', 'Protocolo de observación aprobado por el docente.', 40],
   ['crear', 'Los tres momentos', 'Ejecuta el protocolo y registra las diez recomendaciones de cada momento con su tema. Cuenta los temas distintos.', 'Registro completo de los tres momentos con el conteo de variedad.', 65],
   ['evaluar', 'Salir de la burbuja', 'Analiza cómo cayó la variedad y explica el mecanismo. Propone y prueba tres estrategias para volver a ver cosas distintas.', 'Análisis del mecanismo y las tres estrategias probadas.', 50],
 ],
 'recursos' => [
   ['lectura', 'Cómo funciona una recomendación', 'Señales, similitud y refuerzo, sin matemáticas.'],
   ['plantilla', 'Protocolo de observación', 'Cuenta, interacciones, momentos y registro.'],
 ]],
],

];
