<?php
/**
 * Banco de ampliación · Niveles N9 y N10
 *
 * Mismos cuatro ejes que el bloque anterior: sociedad digital, proyectos en
 * Python, robótica e IA aplicada al aprendizaje, con la exigencia técnica y
 * de documentación que corresponde a PAI 4 y PAI 5.
 */

declare(strict_types=1);

return [

// =========================================================== 9.º · PAI 4 ===
'N9' => [

['codigo' => 'VCP-9-13', 'titulo' => 'Proyecto Python: API del clima para la comunidad escolar',
 'objeto' => 'el servicio de clima escolar',
 'resumen' => 'Aplicación que consume datos meteorológicos, los interpreta y recomienda si la actividad al aire libre se puede hacer.',
 'descripcion' => '<p>El estudiante construye un servicio que consulta datos de clima, los cruza con reglas del colegio (lluvia, índice UV, temperatura) y responde una pregunta concreta: ¿se puede hacer educación física afuera hoy? La respuesta debe venir con el motivo.</p><p>Aparecen el consumo de una API, el manejo de errores de red, la caché para no saturar el servicio y la traducción de datos crudos a una recomendación. El producto se prueba con el docente de Educación Física durante una semana.</p>',
 'pregunta' => '¿Cómo convierto datos crudos en una recomendación en la que alguien confíe?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Solidario|Pensador|Informado e instruido', 'atl' => 'Transferencia|Pensamiento crítico',
 'objetivos' => 'Consumir una API con manejo de errores|Guardar respuestas en caché con vigencia|Traducir umbrales en recomendaciones justificadas|Validar la utilidad con un usuario real',
 'entregables' => 'Aplicación funcionando con caché y control de errores|Tabla de umbrales con su fuente|Registro de una semana de recomendaciones contrastadas con la realidad',
 'lenguaje' => 'Python', 'dificultad' => 'intermedio', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "import json, time, urllib.request\n\nCACHE = \"clima.json\"\nVIGENCIA = 30 * 60   # segundos\n\ndef consultar(url):\n    # TODO: si la cache es reciente, devuelvela sin llamar a la API\n    # TODO: maneja error de red, HTTP 4xx/5xx y JSON invalido por separado\n    pass\n\n# TODO: recomendar(datos) -> (\"si\"/\"no\"/\"con precaucion\", motivo)",
 'fases' => [
   ['indagar', 'Qué necesita saber quien decide', 'Entrevista al docente de Educación Física: qué mira antes de decidir, qué umbrales usa y qué le ha salido mal.', 'Acta de entrevista con los umbrales que usa hoy.', 50],
   ['desarrollar', 'Umbrales con fuente', 'Busca en fuentes oficiales los umbrales de índice UV y temperatura para actividad física escolar. Contrasta con los del docente y acuerda los definitivos.', 'Tabla de umbrales acordada con su fuente.', 45],
   ['crear', 'Programar el servicio', 'Implementa la consulta con caché, los tres tipos de error y la función de recomendación con motivo. Ejecuta a diario una semana.', 'Aplicación funcionando y siete recomendaciones registradas.', 90],
   ['evaluar', '¿Acertó?', 'Contrasta cada recomendación con lo que realmente pasó ese día y con lo que decidió el docente. Analiza los desacuerdos y ajusta un umbral.', 'Tabla de contraste de siete días y ajuste justificado.', 50],
 ],
 'recursos' => [
   ['enlace', 'APIs de clima abiertas', 'Servicios gratuitos con datos horarios y su documentación.'],
   ['lectura', 'Caché con vigencia', 'Por qué y cómo no saturar un servicio ajeno.'],
 ]],

['codigo' => 'VCP-9-14', 'titulo' => 'Ciudadanía digital: el contrato de convivencia en línea',
 'objeto' => 'el acuerdo de convivencia digital',
 'resumen' => 'Redactar con el curso un acuerdo de convivencia para los grupos de mensajería, con casos resueltos y consecuencias.',
 'descripcion' => '<p>Los conflictos de los grupos de mensajería del curso son reales y suelen resolverse mal. El estudiante recoge, de forma anónima, los casos que han pasado, los clasifica y redacta con sus compañeros un acuerdo que los resuelva antes de que ocurran.</p><p>El acuerdo no puede quedarse en principios: se prueba contra diez casos concretos, y cada regla que deje un caso ambiguo se reescribe. Después se somete a votación del curso y se firma.</p>',
 'pregunta' => '¿Puede un grupo ponerse de acuerdo sobre cómo tratarse antes de que haya un problema?',
 'contexto' => 'Identidades y relaciones', 'concepto' => 'Relaciones',
 'perfil' => 'Solidario|Íntegro|Buen comunicador', 'atl' => 'Colaboración|Comunicación|Reflexión',
 'objetivos' => 'Recoger evidencia sensible de forma anónima y respetuosa|Convertir conflictos en reglas verificables|Negociar un acuerdo colectivo|Probar una norma contra casos reales',
 'entregables' => 'Recolección anónima de casos clasificados|Acuerdo de convivencia digital de una página|Prueba contra diez casos|Registro de la votación y las firmas',
 'lenguaje' => 'Documentación', 'dificultad' => 'intermedio', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "// Estructura del acuerdo\n// 1. A que grupos aplica\n// 2. Que si se puede publicar\n// 3. Que nunca (capturas privadas, fotos sin permiso, exclusiones)\n// 4. Que hacemos cuando alguien lo incumple: primer paso, segundo paso\n// 5. Quien media\n// 6. Diez casos resueltos como ejemplo",
 'fases' => [
   ['indagar', 'Qué ha pasado de verdad', 'Recoge de forma anónima los conflictos que ha habido en los grupos del curso. Clasifícalos por tipo sin identificar a nadie.', 'Casos recogidos y clasificados, sin nombres.', 50],
   ['desarrollar', 'De los casos a las reglas', 'Convierte cada tipo de conflicto en una regla que se pueda comprobar. Define los pasos cuando alguien la incumpla.', 'Borrador del acuerdo con reglas verificables.', 45],
   ['crear', 'Negociar y redactar', 'Discute el borrador con el curso, integra las objeciones y redacta la versión final en una página. Pruébala contra diez casos.', 'Acuerdo final y tabla de los diez casos resueltos.', 70],
   ['evaluar', 'Votar y sostener', 'Somete el acuerdo a votación. Un mes después, revisa si se cumplió y qué regla hubo que usar. Ajusta lo que no funcionó.', 'Resultado de la votación y revisión al mes con ajustes.', 45],
 ],
 'recursos' => [
   ['plantilla', 'Recolección anónima de casos', 'Formato que protege la identidad de quien reporta.'],
   ['plantilla', 'Diez casos de convivencia digital', 'Situaciones reales para probar el acuerdo.'],
 ]],

['codigo' => 'VCP-9-15', 'titulo' => 'Robótica: control por eventos y máquina de estados',
 'objeto' => 'el controlador por eventos',
 'resumen' => 'Programar un dispositivo que reacciona a varios eventos a la vez sin bloquearse esperando a ninguno.',
 'descripcion' => '<p>El estudiante descubre por qué <code>sleep</code> arruina un robot: mientras espera, no puede reaccionar. Reescribe un controlador con máquina de estados y comprobación periódica, de modo que atienda un botón, un sensor y un temporizador simultáneamente.</p><p>Es el salto conceptual que separa un programa lineal de un sistema reactivo, y prepara el terreno para la concurrencia de 12.º. Se mide con un criterio duro: el tiempo que tarda en responder al botón mientras hace otra cosa.</p>',
 'pregunta' => '¿Cómo atiende una máquina varias cosas a la vez si solo puede hacer una?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Pensador|Reflexivo', 'atl' => 'Pensamiento crítico|Transferencia',
 'objetivos' => 'Diseñar una máquina de estados con transiciones por evento|Sustituir esperas bloqueantes por comprobación periódica|Medir la latencia de respuesta|Justificar el diseño frente a la versión lineal',
 'entregables' => 'Diagrama de estados y eventos|Las dos versiones del controlador: bloqueante y por eventos|Medición de latencia de ambas',
 'lenguaje' => 'Python', 'dificultad' => 'avanzado', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "import time\n\n# Version bloqueante (la que NO sirve)\n# time.sleep(5)   <- durante 5 s el robot esta sordo\n\nestado = \"reposo\"\nultimo_cambio = time.monotonic()\n\ndef paso(ahora, boton, sensor):\n    global estado, ultimo_cambio\n    # TODO: transiciones por evento, sin sleep\n    return estado",
 'fases' => [
   ['indagar', 'El problema del sleep', 'Programa la versión bloqueante y mide cuánto tarda en reaccionar al botón si lo pulsas durante la espera. Documenta el peor caso.', 'Versión bloqueante y medición del peor tiempo de reacción.', 50],
   ['desarrollar', 'Estados y eventos', 'Dibuja la máquina de estados: qué estados hay, qué evento provoca cada transición y qué se hace al entrar en cada estado.', 'Diagrama de estados completo con eventos y acciones.', 50],
   ['crear', 'Reescribir sin bloquear', 'Implementa el controlador por eventos con un bucle que comprueba todo en cada vuelta. Sin ningún sleep largo.', 'Controlador por eventos funcionando.', 85],
   ['evaluar', 'Medir la latencia', 'Mide el tiempo de reacción al botón en ambas versiones, diez pulsaciones cada una. Compara los peores casos y explica la diferencia.', 'Tabla de veinte mediciones y análisis comparativo.', 50],
 ],
 'recursos' => [
   ['lectura', 'Bucle de eventos sin bloqueo', 'monotonic, comprobación periódica y por qué no usar sleep.'],
 ]],

['codigo' => 'VCP-9-16', 'titulo' => 'Aprender a programar con IA sin dejar de aprender',
 'objeto' => 'el protocolo de aprendizaje asistido',
 'resumen' => 'Diseñar y probar un protocolo personal para usar IA al programar que no impida adquirir la destreza.',
 'descripcion' => '<p>El estudiante resuelve el mismo tipo de problema tres veces: sin ayuda, con ayuda ilimitada de la IA, y con ayuda restringida por reglas que él mismo escribe. Al final se autoevalúa resolviendo un cuarto problema sin ninguna ayuda.</p><p>El cuarto problema es el que importa: mide qué destreza quedó. La conclusión no la dicta el docente, la produce el propio dato del estudiante, y suele ser matizada, no un veredicto a favor o en contra de la IA.</p>',
 'pregunta' => '¿Qué tipo de ayuda me hace mejor programador y cuál me deja igual?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Relaciones',
 'perfil' => 'Reflexivo|Íntegro|Pensador', 'atl' => 'Autogestión|Reflexión|Pensamiento crítico',
 'objetivos' => 'Diseñar un experimento sobre el propio aprendizaje|Definir reglas de asistencia y respetarlas|Medir destreza con una prueba sin ayuda|Formular un protocolo personal fundamentado',
 'entregables' => 'Los cuatro problemas resueltos con su registro|Reglas de asistencia redactadas antes de la prueba|Tiempos y resultados de los cuatro|Protocolo personal de uso de IA al programar',
 'lenguaje' => 'Python o JavaScript', 'dificultad' => 'intermedio', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "# Registro del experimento\n# | Problema | Condicion | Tiempo | Funciono? | Lo entendi? (1-5) |\n# | 1 | sin ayuda            |  |  |  |\n# | 2 | ayuda ilimitada      |  |  |  |\n# | 3 | ayuda con mis reglas |  |  |  |\n# | 4 | PRUEBA sin ayuda     |  |  |  |",
 'fases' => [
   ['indagar', 'Cuatro problemas equivalentes', 'Elige cuatro problemas del mismo tipo y dificultad, verificados con tu docente para que sean comparables.', 'Los cuatro problemas y el visto bueno del docente.', 40],
   ['desarrollar', 'Mis reglas de asistencia', 'Escribe las reglas de la condición 3: qué le puedes pedir a la IA y qué no. Deben ser comprobables por alguien que lea el registro.', 'Reglas de asistencia redactadas antes de empezar.', 40],
   ['crear', 'Resolver en las tres condiciones', 'Resuelve los problemas 1, 2 y 3 en sus condiciones, cronometrando y guardando las conversaciones íntegras.', 'Tres soluciones con tiempos y conversaciones guardadas.', 90],
   ['evaluar', 'La prueba sin red', 'Resuelve el problema 4 sin ninguna ayuda, cronometrado. Compara con los tres anteriores y redacta tu protocolo personal.', 'Problema 4 resuelto, tabla comparativa y protocolo personal.', 55],
 ],
 'recursos' => [
   ['plantilla', 'Registro del experimento', 'Condición, tiempo, resultado, comprensión.'],
   ['lectura', 'Carga cognitiva y andamiaje', 'Cuándo una ayuda enseña y cuándo estorba.'],
 ]],

['codigo' => 'VCP-9-17', 'titulo' => 'Proyecto Python: panel de datos abiertos de la ciudad',
 'objeto' => 'el panel de datos abiertos',
 'resumen' => 'Descargar, limpiar y publicar un conjunto de datos abiertos de Barranquilla que responda una pregunta ciudadana.',
 'descripcion' => '<p>El estudiante elige un conjunto de datos abiertos de la ciudad, lo descarga, lo limpia (que es la mayor parte del trabajo) y construye un panel que responde una pregunta concreta y útil para alguien.</p><p>La limpieza es el contenido real: registros duplicados, fechas en tres formatos, campos vacíos, categorías escritas de cinco maneras. El estudiante documenta cada decisión de limpieza, porque cada una cambia el resultado.</p>',
 'pregunta' => '¿Cuánto de lo que muestra un panel depende de decisiones que nadie ve?',
 'contexto' => 'Globalización y sustentabilidad', 'concepto' => 'Relaciones',
 'perfil' => 'Indagador|Íntegro|Informado e instruido', 'atl' => 'Alfabetización informacional|Pensamiento crítico',
 'objetivos' => 'Evaluar la calidad de un conjunto de datos abierto|Documentar decisiones de limpieza y su efecto|Construir visualizaciones honestas|Comunicar hallazgos con sus limitaciones',
 'entregables' => 'Ficha de la fuente con licencia y fecha|Registro de decisiones de limpieza con filas afectadas|Panel publicado que responde la pregunta|Nota de limitaciones',
 'lenguaje' => 'Python, HTML', 'dificultad' => 'avanzado', 'sesiones' => 6, 'horas' => 6.0, 'ia' => 1,
 'codigo_inicial' => "import csv\n\n# Registro de limpieza\n# | Decision | Filas afectadas | Efecto en el resultado |\n# | Descartar filas sin fecha |  |  |\n# | Unificar \"Norte\"/\"NORTE\"/\"norte\" |  |  |\n\ndef cargar_y_limpiar(ruta):\n    # TODO: normaliza, deduplica y registra cuantas filas tocas\n    pass",
 'fases' => [
   ['indagar', 'Elegir fuente y pregunta', 'Explora el portal de datos abiertos y elige un conjunto. Formula la pregunta ciudadana que vas a responder y verifica que los datos puedan responderla.', 'Ficha de la fuente y pregunta verificada contra las columnas disponibles.', 50],
   ['desarrollar', 'Auditar la calidad', 'Cuenta valores vacíos, duplicados y categorías inconsistentes. Decide qué harás con cada problema y anticipa cómo afectará al resultado.', 'Auditoría de calidad y plan de limpieza con el efecto previsto.', 55],
   ['crear', 'Limpiar y publicar', 'Programa la limpieza registrando las filas afectadas por cada decisión. Construye el panel que responde la pregunta.', 'Registro de limpieza y panel funcionando.', 100],
   ['evaluar', 'Qué cambia si decido distinto', 'Repite el análisis cambiando una decisión de limpieza y compara los resultados. Escribe la nota de limitaciones del panel.', 'Comparación de los dos resultados y nota de limitaciones publicada.', 55],
 ],
 'recursos' => [
   ['enlace', 'Portal de datos abiertos', 'Conjuntos municipales y nacionales con su licencia.'],
   ['plantilla', 'Registro de decisiones de limpieza', 'Decisión, filas afectadas, efecto.'],
 ]],

['codigo' => 'VCP-9-18', 'titulo' => 'Robótica: sensor, actuador y calibración',
 'objeto' => 'el sistema calibrado',
 'resumen' => 'Calibrar un sensor real construyendo su curva de respuesta y usarla para que las medidas signifiquen algo.',
 'descripcion' => '<p>Un sensor no devuelve centímetros ni grados: devuelve un número. El estudiante construye la curva de calibración midiendo valores conocidos, ajusta la relación y convierte la lectura cruda en una unidad real con un margen de error declarado.</p><p>Es la actividad que introduce la idea de incertidumbre: ninguna medida es exacta, y decir «23 grados» sin decir «más o menos uno» es decir menos de lo que se sabe. Conecta directamente con Ciencias.</p>',
 'pregunta' => '¿Qué significa realmente el número que me devuelve un sensor?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Relaciones',
 'perfil' => 'Indagador|Pensador|Íntegro', 'atl' => 'Pensamiento crítico|Transferencia',
 'objetivos' => 'Construir una curva de calibración con puntos conocidos|Ajustar una relación lineal y evaluarla|Convertir lectura cruda a unidad física|Declarar el margen de error de una medida',
 'entregables' => 'Tabla de calibración con al menos ocho puntos|Gráfica con el ajuste|Programa que convierte y declara el margen|Comparación contra un instrumento de referencia',
 'lenguaje' => 'Python', 'dificultad' => 'avanzado', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "# Puntos de calibracion: (valor_real, lectura_cruda)\nPUNTOS = [(0, 12), (10, 98), (20, 187)]   # TODO: al menos 8 puntos\n\ndef ajustar(puntos):\n    # TODO: calcula pendiente y corte (minimos cuadrados o dos puntos extremos)\n    return 1.0, 0.0\n\ndef a_unidad(lectura, m, b):\n    return (lectura - b) / m",
 'fases' => [
   ['indagar', 'Qué devuelve el sensor', 'Toma diez lecturas crudas en condiciones distintas sin convertir nada. Observa el rango y la estabilidad: ¿varía la lectura sin que cambie nada?', 'Diez lecturas crudas con el análisis de estabilidad.', 45],
   ['desarrollar', 'Diseñar la calibración', 'Define ocho puntos de referencia conocidos y cómo los conseguirás. Predice si la relación será lineal y por qué.', 'Plan de calibración con los ocho puntos y la predicción.', 45],
   ['crear', 'Calibrar y convertir', 'Toma los puntos, calcula el ajuste y programa la conversión. Grafica los puntos con la recta ajustada.', 'Tabla, gráfica y programa de conversión funcionando.', 85],
   ['evaluar', 'Cuánto me equivoco', 'Compara tus medidas convertidas con un instrumento de referencia en cinco puntos nuevos. Calcula el error y decláralo en la salida del programa.', 'Comparación de cinco puntos, error calculado y salida con margen.', 50],
 ],
 'recursos' => [
   ['lectura', 'Calibración y curva de respuesta', 'De la lectura cruda a la unidad física.'],
   ['plantilla', 'Hoja de calibración', 'Valor real, lectura, repeticiones, promedio.'],
 ]],

['codigo' => 'VCP-9-19', 'titulo' => 'Trabajo, automatización y las profesiones que vienen',
 'objeto' => 'el estudio sobre automatización del trabajo',
 'resumen' => 'Investigar cómo cambia un oficio concreto de la ciudad con la automatización, entrevistando a quien lo ejerce.',
 'descripcion' => '<p>El estudiante elige un oficio real de su entorno —conductor, cajero, contador, diseñador— y estudia cómo lo ha cambiado ya la automatización. Combina fuentes documentales con una entrevista a alguien que ejerza ese oficio hoy.</p><p>El contraste entre lo que dicen los artículos y lo que dice la persona suele ser grande: los titulares hablan de desaparición y la persona habla de tareas que cambiaron. El estudiante presenta una conclusión equilibrada y personal sobre su propio futuro.</p>',
 'pregunta' => '¿Desaparecen los oficios o cambian las tareas que los componen?',
 'contexto' => 'Globalización y sustentabilidad', 'concepto' => 'Relaciones',
 'perfil' => 'Indagador|De mentalidad abierta|Solidario', 'atl' => 'Alfabetización informacional|Comunicación|Reflexión',
 'objetivos' => 'Descomponer un oficio en tareas|Evaluar qué tareas son automatizables y cuáles no|Contrastar fuentes documentales con testimonio directo|Formular una conclusión propia sobre el futuro laboral',
 'entregables' => 'Descomposición del oficio en al menos diez tareas|Cuatro fuentes documentales evaluadas|Entrevista registrada con quien ejerce el oficio|Conclusión personal de una página',
 'lenguaje' => 'Investigación', 'dificultad' => 'intermedio', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "// Matriz de tareas del oficio\n// | Tarea | Repetitiva? | Requiere juicio? | Requiere trato humano? | Automatizable? |\n//\n// Conclusion: no se automatiza un OFICIO, se automatizan TAREAS.\n// Cuales quedan y que valor tienen?",
 'fases' => [
   ['indagar', 'Descomponer el oficio', 'Elige el oficio y descompónlo en al menos diez tareas concretas. Clasifica cada una por repetitividad, juicio requerido y trato humano.', 'Matriz de diez tareas clasificadas.', 50],
   ['desarrollar', 'Qué dicen las fuentes', 'Reúne cuatro fuentes sobre la automatización de ese oficio, al menos una optimista y una pesimista. Evalúa su credibilidad e intereses.', 'Cuatro fuentes evaluadas con su posición.', 50],
   ['crear', 'Escuchar a quien lo hace', 'Entrevista a alguien que ejerza el oficio. Pregunta qué tareas ya cambiaron, cuáles teme perder y cuáles cree que nunca se automatizarán.', 'Entrevista registrada con al menos ocho respuestas.', 70],
   ['evaluar', 'Mi conclusión', 'Contrasta la matriz, las fuentes y la entrevista. Escribe qué destrezas cultivarías tú si ese fuera tu oficio, y por qué.', 'Conclusión de una página con las tres fuentes contrastadas.', 50],
 ],
 'recursos' => [
   ['plantilla', 'Matriz de tareas automatizables', 'Cinco columnas para clasificar cada tarea.'],
   ['plantilla', 'Guion de entrevista laboral', 'Preguntas abiertas sobre cambios en el oficio.'],
 ]],
],

// ========================================================== 10.º · PAI 5 ===
'N10' => [

['codigo' => 'VCP-10-13', 'titulo' => 'Proyecto Python: API propia con autenticación',
 'objeto' => 'la API del proyecto',
 'resumen' => 'Construir una API propia que sirva los datos del proyecto personal, con claves de acceso y límites de uso.',
 'descripcion' => '<p>El estudiante deja de consumir APIs y construye la suya: endpoints que devuelven JSON, autenticación por clave, límite de peticiones y códigos de estado correctos. Es el paso que convierte una aplicación en un servicio del que otros pueden depender.</p><p>La evaluación la hace un compañero: recibe solo la documentación y debe consumir la API sin preguntar nada. Cada vez que tiene que preguntar, es un fallo de diseño o de documentación, no del compañero.</p>',
 'pregunta' => '¿Puede otro programa usar el mío sin que yo esté delante para explicarlo?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Pensador|Buen comunicador|Íntegro', 'atl' => 'Organización|Comunicación',
 'objetivos' => 'Diseñar endpoints coherentes y predecibles|Autenticar peticiones y limitar el uso|Devolver códigos de estado y errores útiles|Documentar una interfaz para terceros',
 'entregables' => 'API con al menos cuatro endpoints|Autenticación por clave y límite de peticiones|Documentación completa|Informe del compañero que la consumió a ciegas',
 'lenguaje' => 'PHP o Python', 'dificultad' => 'avanzado', 'sesiones' => 6, 'horas' => 7.0, 'ia' => 1,
 'codigo_inicial' => "<?php\nheader('Content-Type: application/json; charset=utf-8');\n\n// TODO: valida la clave de la cabecera Authorization\n// TODO: limita a N peticiones por minuto y por clave\n// TODO: responde 200, 401, 404, 422 y 429 segun corresponda\n// Toda respuesta de error debe decir QUE hacer, no solo que fallo.",
 'fases' => [
   ['indagar', 'Qué hace buena a una API', 'Consume dos APIs públicas y anota qué te resultó predecible y qué te confundió. Extrae cinco reglas de diseño de esa experiencia.', 'Análisis de dos APIs y cinco reglas propias de diseño.', 50],
   ['desarrollar', 'Contrato de la interfaz', 'Especifica los endpoints: ruta, método, parámetros, respuesta y errores posibles. Escríbelo antes de programar nada.', 'Especificación completa de al menos cuatro endpoints.', 55],
   ['crear', 'Implementar y documentar', 'Programa la API con autenticación, límite de uso y códigos correctos. Redacta la documentación con un ejemplo de llamada por endpoint.', 'API funcionando y documentación completa.', 110],
   ['evaluar', 'Consumo a ciegas', 'Entrega solo la documentación a un compañero y pídele consumir la API. Anota cada vez que tuvo que preguntarte algo y corrígelo.', 'Informe del consumo a ciegas y correcciones aplicadas.', 55],
 ],
 'recursos' => [
   ['lectura', 'Códigos de estado que importan', '200, 401, 404, 422 y 429 con ejemplos.'],
   ['plantilla', 'Especificación de endpoint', 'Ruta, método, parámetros, respuesta, errores.'],
 ]],

['codigo' => 'VCP-10-14', 'titulo' => 'Robótica: prototipo asistivo para una necesidad real',
 'objeto' => 'el prototipo asistivo',
 'resumen' => 'Diseñar y construir un dispositivo que resuelva una dificultad concreta de una persona real del entorno.',
 'descripcion' => '<p>El estudiante identifica a una persona con una dificultad concreta —alcanzar un objeto, recordar una toma, orientarse— y diseña con ella un prototipo que la ayude. La persona participa en el diseño desde el principio, no solo en la prueba final.</p><p>Es el proyecto donde la robótica deja de ser un juguete. La medida del éxito la pone la persona usuaria, no el docente ni el estudiante, y con frecuencia obliga a rehacer el diseño entero después de la primera prueba.</p>',
 'pregunta' => '¿Estoy resolviendo el problema de alguien o el que yo imaginé que tenía?',
 'contexto' => 'Equidad y desarrollo', 'concepto' => 'Sistemas',
 'perfil' => 'Solidario|Audaz|Reflexivo|De mentalidad abierta', 'atl' => 'Colaboración|Pensamiento creativo|Reflexión',
 'objetivos' => 'Codiseñar con la persona usuaria desde el inicio|Traducir una necesidad en especificaciones medibles|Construir e iterar un prototipo funcional|Evaluar con criterios definidos por quien lo usa',
 'entregables' => 'Registro del codiseño con la persona usuaria|Especificaciones acordadas con ella|Prototipo funcional|Evaluación con los criterios de la persona usuaria',
 'lenguaje' => 'Python', 'dificultad' => 'avanzado', 'sesiones' => 7, 'horas' => 8.0, 'ia' => 1,
 'codigo_inicial' => "// Especificaciones acordadas con la persona usuaria\n// | # | Que debe lograr | Como lo comprobamos | Quien lo define |\n// | 1 |                 |                     | la persona usuaria |\n//\n// Regla del proyecto: ninguna especificacion la define el estudiante solo.",
 'fases' => [
   ['indagar', 'Escuchar antes de imaginar', 'Acompaña a la persona en la actividad difícil y observa sin proponer nada. Después pregunta qué le molesta más y qué ya intentó.', 'Registro de la observación y de la conversación, sin propuestas todavía.', 70],
   ['desarrollar', 'Codiseñar', 'Presenta tres ideas muy simples y deja que la persona elija y modifique. Acuerden juntos las especificaciones y cómo se comprobará cada una.', 'Tres ideas presentadas y especificaciones firmadas por la persona usuaria.', 70],
   ['crear', 'Construir e iterar', 'Construye el prototipo. Muéstralo en dos momentos intermedios y ajusta con lo que la persona diga, aunque implique rehacer.', 'Prototipo funcional y bitácora con las dos iteraciones.', 130],
   ['evaluar', 'Que lo use sin ti', 'La persona usa el prototipo sin tu ayuda durante varios días. Evalúa cada especificación con su criterio y documenta qué falta.', 'Evaluación con la persona usuaria y lista de mejoras pendientes.', 60],
 ],
 'recursos' => [
   ['plantilla', 'Guía de codiseño', 'Cómo involucrar a la persona usuaria en cada fase.'],
   ['lectura', 'Diseño asistivo con dignidad', 'Errores frecuentes al diseñar «para» en vez de «con».'],
 ]],

['codigo' => 'VCP-10-15', 'titulo' => 'Huella ambiental de lo digital',
 'objeto' => 'el estudio de huella digital ambiental',
 'resumen' => 'Estimar el consumo energético de la actividad digital del colegio y proponer reducciones medibles.',
 'descripcion' => '<p>La nube no es una nube: son centros de datos que consumen energía. El estudiante estima el consumo asociado a la actividad digital del colegio —almacenamiento, videollamadas, streaming en clase— usando factores publicados y datos propios de uso.</p><p>Toda cifra debe tener fuente y todo cálculo debe poder rehacerse. La propuesta final debe ser medible: no «usar menos internet», sino acciones con un ahorro estimado y una forma de comprobarlo.</p>',
 'pregunta' => '¿Cuánta energía cuesta lo que llamamos «la nube»?',
 'contexto' => 'Globalización y sustentabilidad', 'concepto' => 'Relaciones',
 'perfil' => 'Informado e instruido|Íntegro|Solidario', 'atl' => 'Alfabetización informacional|Pensamiento crítico',
 'objetivos' => 'Localizar y evaluar factores de consumo publicados|Estimar con datos propios y supuestos declarados|Analizar la sensibilidad del resultado a los supuestos|Proponer reducciones medibles',
 'entregables' => 'Modelo de estimación con supuestos declarados|Fuentes de cada factor|Análisis de sensibilidad|Tres propuestas de reducción con ahorro estimado',
 'lenguaje' => 'Python', 'dificultad' => 'avanzado', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "# Todo factor lleva fuente. Todo supuesto se declara.\nFACTORES = {\n    \"streaming_gb\": 0.0,     # kWh por GB   FUENTE:\n    \"almacenamiento_gb_mes\": 0.0,  #             FUENTE:\n}\nSUPUESTOS = [\n    \"Se asume que el 60 % del video se ve en calidad media.\",\n]\n\n# TODO: estima el consumo mensual del colegio\n# TODO: repite el calculo variando cada factor un 50 % arriba y abajo",
 'fases' => [
   ['indagar', 'Buscar factores fiables', 'Encuentra al menos tres fuentes con factores de consumo energético digital. Compáralas: si difieren mucho, explica por qué.', 'Tres fuentes comparadas con la explicación de sus diferencias.', 55],
   ['desarrollar', 'Modelo y supuestos', 'Construye el modelo de estimación y declara cada supuesto por escrito. Recoge los datos de uso reales del colegio que puedas.', 'Modelo documentado con todos los supuestos declarados.', 50],
   ['crear', 'Estimar y probar la sensibilidad', 'Programa la estimación y repítela variando cada factor. Observa qué supuesto cambia más el resultado.', 'Estimación con el análisis de sensibilidad de cada factor.', 85],
   ['evaluar', 'Reducciones que se puedan medir', 'Propón tres acciones con su ahorro estimado y cómo se comprobaría. Preséntalas a quien administre la infraestructura del colegio.', 'Tres propuestas medibles y acta de la presentación.', 50],
 ],
 'recursos' => [
   ['dataset', 'Factores de consumo digital', 'Estudios publicados con kWh por GB y por hora de video.'],
   ['lectura', 'Análisis de sensibilidad', 'Cómo saber qué supuesto sostiene tu resultado.'],
 ]],

['codigo' => 'VCP-10-16', 'titulo' => 'IA que ayuda a estudiar a todo un curso',
 'objeto' => 'el asistente de estudio del curso',
 'resumen' => 'Construir y evaluar un asistente de repaso para una asignatura concreta, con evidencia de si mejora el aprendizaje.',
 'descripcion' => '<p>El estudiante construye un asistente de repaso para una asignatura del colegio, cargado con el temario real y con reglas pedagógicas: pregunta antes de explicar, no da respuestas de tareas y adapta la dificultad. Lo prueban ocho compañeros durante dos semanas.</p><p>La evaluación es lo distintivo: cuatro compañeros lo usan y cuatro estudian como siempre, y todos hacen la misma prueba de repaso. El estudiante analiza si hubo diferencia y, sobre todo, reconoce las limitaciones de un experimento con ocho personas.</p>',
 'pregunta' => '¿Puedo demostrar que mi herramienta ayuda, o solo que gustó?',
 'contexto' => 'Identidades y relaciones', 'concepto' => 'Sistemas',
 'perfil' => 'Indagador|Íntegro|Solidario|Reflexivo', 'atl' => 'Pensamiento crítico|Colaboración|Reflexión',
 'objetivos' => 'Diseñar un asistente con reglas pedagógicas explícitas|Cargar y acotar el asistente a un temario real|Diseñar una comparación con grupo de control|Distinguir satisfacción de aprendizaje',
 'entregables' => 'Asistente configurado con su ficha de reglas|Registro de uso de cuatro compañeros durante dos semanas|Resultados de la prueba de repaso en ambos grupos|Análisis con las limitaciones declaradas',
 'lenguaje' => 'Lenguaje natural', 'dificultad' => 'avanzado', 'sesiones' => 6, 'horas' => 6.0, 'ia' => 1,
 'codigo_inicial' => "# Ficha del asistente de repaso\n# Asignatura y temario exacto que puede tratar:\n# Reglas pedagogicas:\n#   1. Pregunta antes de explicar.\n#   2. Nunca resuelve una tarea que este calificada.\n#   3. Si el estudiante falla dos veces, baja la dificultad.\n#   4. Cierra cada sesion diciendo que repasar.\n# Que hace si le preguntan algo fuera del temario:",
 'fases' => [
   ['indagar', 'Qué se atasca en esa asignatura', 'Consulta al docente y a ocho compañeros qué temas cuestan más. Elige uno y consigue el temario exacto.', 'Consulta a nueve personas y el temario del tema elegido.', 55],
   ['desarrollar', 'Reglas y diseño del experimento', 'Redacta la ficha del asistente con sus reglas. Diseña la comparación: quién usa qué, durante cuánto y qué prueba harán todos.', 'Ficha del asistente y diseño del experimento aprobado por el docente.', 55],
   ['crear', 'Construir y poner a prueba', 'Configura el asistente y déjalo en uso dos semanas con cuatro compañeros. Registra el uso; los otros cuatro estudian como siempre.', 'Asistente funcionando y registro de dos semanas de uso.', 100],
   ['evaluar', 'Ayudó o solo gustó', 'Aplica la misma prueba a los ocho. Compara resultados y satisfacción por separado. Declara las limitaciones de una muestra tan pequeña.', 'Resultados comparados, distinción entre gusto y aprendizaje, limitaciones declaradas.', 60],
 ],
 'recursos' => [
   ['plantilla', 'Ficha de asistente pedagógico', 'Alcance, reglas, límites y respuesta fuera de temario.'],
   ['lectura', 'Grupo de control en el aula', 'Cómo comparar sin perjudicar a nadie.'],
 ]],

['codigo' => 'VCP-10-17', 'titulo' => 'Seguridad del proyecto: pensar como quien ataca',
 'objeto' => 'la revisión de seguridad',
 'resumen' => 'Auditar el propio proyecto buscando las fallas más comunes y corregirlas con evidencia.',
 'descripcion' => '<p>El estudiante audita su propio proyecto con una lista de las fallas más frecuentes: entradas sin validar, contraseñas mal guardadas, sesiones débiles, archivos accesibles, mensajes de error que revelan de más. Documenta cada hallazgo con la prueba que lo demuestra.</p><p>Se hace únicamente sobre el proyecto propio y en el entorno del colegio: el alcance ético se define y se firma antes de empezar. Esa delimitación es parte de la evaluación, no un trámite.</p>',
 'pregunta' => '¿Qué haría alguien que quisiera romper lo que construí?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Íntegro|Pensador|Reflexivo', 'atl' => 'Pensamiento crítico|Organización',
 'objetivos' => 'Aplicar una lista de comprobación de seguridad|Demostrar cada hallazgo con una prueba reproducible|Corregir y verificar la corrección|Delimitar el alcance ético de una auditoría',
 'entregables' => 'Alcance ético firmado antes de empezar|Informe con al menos seis hallazgos y su prueba|Correcciones aplicadas y verificadas|Segunda pasada de la auditoría',
 'lenguaje' => 'PHP, JavaScript', 'dificultad' => 'avanzado', 'sesiones' => 5, 'horas' => 6.0, 'ia' => 1,
 'codigo_inicial' => "// Alcance de la auditoria (firmar antes de empezar)\n// Sistemas incluidos: SOLO mi proyecto, en mi entorno local o el del colegio.\n// Sistemas excluidos: cualquier servicio de terceros y cualquier cuenta ajena.\n// Datos: inventados. Nunca datos de personas reales.\n//\n// Hallazgo | Como lo demuestro | Gravedad | Correccion | Verificacion",
 'fases' => [
   ['indagar', 'Las fallas más frecuentes', 'Estudia las categorías de fallas más comunes en aplicaciones web. Para cada una, escribe cómo se vería en tu proyecto.', 'Lista de ocho categorías con su forma concreta en tu proyecto.', 55],
   ['desarrollar', 'Alcance y plan', 'Redacta y firma el alcance ético con tu docente. Planifica qué probarás en cada categoría y con qué datos inventados.', 'Alcance firmado y plan de pruebas.', 45],
   ['crear', 'Auditar con evidencia', 'Ejecuta las pruebas y documenta cada hallazgo con los pasos exactos para reproducirlo y una captura o registro.', 'Informe con al menos seis hallazgos reproducibles y su gravedad.', 90],
   ['evaluar', 'Corregir y volver a probar', 'Corrige los hallazgos por orden de gravedad y repite cada prueba. Documenta cuáles quedaron cerrados y cuáles no, y por qué.', 'Correcciones verificadas y segunda pasada documentada.', 55],
 ],
 'recursos' => [
   ['plantilla', 'Lista de comprobación de seguridad web', 'Ocho categorías con la prueba típica de cada una.'],
   ['plantilla', 'Acuerdo de alcance ético', 'Qué se prueba, qué no y con qué datos.'],
 ]],

['codigo' => 'VCP-10-18', 'titulo' => 'Proyecto Python: automatizar una tarea del colegio',
 'objeto' => 'la automatización administrativa',
 'resumen' => 'Automatizar una tarea repetitiva real de la administración del colegio y medir el tiempo que ahorra.',
 'descripcion' => '<p>El estudiante busca en la administración del colegio una tarea repetitiva que alguien hace a mano —consolidar listas, renombrar archivos, generar constancias, cruzar dos planillas— y la automatiza. Antes cronometra cuánto se tarda a mano.</p><p>El indicador es el tiempo ahorrado por mes, calculado con la frecuencia real de la tarea. Y hay una condición innegociable: la persona que hacía el trabajo debe poder usar el programa sin el estudiante presente.</p>',
 'pregunta' => '¿Cuánto tiempo de una persona vale una hora de mi programación?',
 'contexto' => 'Equidad y desarrollo', 'concepto' => 'Sistemas',
 'perfil' => 'Solidario|Pensador|Buen comunicador', 'atl' => 'Organización|Comunicación|Transferencia',
 'objetivos' => 'Identificar y cronometrar una tarea repetitiva real|Automatizar procesamiento de archivos y datos|Diseñar para un usuario no técnico|Medir el ahorro con datos verificables',
 'entregables' => 'Cronometraje del proceso manual|Programa funcionando con su manual de una página|Prueba de uso autónomo por la persona responsable|Cálculo del ahorro mensual',
 'lenguaje' => 'Python', 'dificultad' => 'avanzado', 'sesiones' => 5, 'horas' => 6.0, 'ia' => 1,
 'codigo_inicial' => "# Antes de programar: cronometra el proceso manual 3 veces\n# Tiempo manual promedio: ___ min   Frecuencia: ___ veces al mes\n# Ahorro potencial mensual: ___ min\n#\n# Regla: el programa debe poder usarlo quien hace la tarea hoy,\n# sin editar codigo y sin que yo este presente.",
 'fases' => [
   ['indagar', 'Encontrar y medir la tarea', 'Recorre la administración y encuentra tres tareas repetitivas. Elige una y cronométrala tres veces mientras la persona la hace.', 'Tres tareas candidatas y el cronometraje de la elegida.', 55],
   ['desarrollar', 'Diseñar para quien no programa', 'Define la interfaz: qué archivos entran, qué sale, qué mensajes ve. Acuerda con la persona cómo lo va a ejecutar.', 'Diseño de la interfaz acordado con la persona responsable.', 45],
   ['crear', 'Automatizar y documentar', 'Programa la automatización con validaciones y mensajes claros. Escribe el manual de una página con capturas.', 'Programa funcionando y manual de una página.', 95],
   ['evaluar', 'Que lo use sola', 'La persona ejecuta el proceso sin tu ayuda mientras observas en silencio. Cronometra, anota los tropiezos y calcula el ahorro real.', 'Prueba de uso autónomo, tropiezos corregidos y ahorro mensual calculado.', 55],
 ],
 'recursos' => [
   ['lectura', 'Procesar archivos por lotes', 'Recorrer carpetas, leer varios formatos y escribir resultados.'],
 ]],

['codigo' => 'VCP-10-19', 'titulo' => 'Accesibilidad digital: probar con quien lo necesita',
 'objeto' => 'la evaluación de accesibilidad participativa',
 'resumen' => 'Evaluar un servicio digital del colegio junto a personas con distintas capacidades y proponer mejoras priorizadas.',
 'descripcion' => '<p>El estudiante evalúa un servicio digital que el colegio usa de verdad —la plataforma de notas, el sitio, un formulario— no solo con una lista de comprobación, sino con personas: alguien que navegue con teclado, alguien con baja visión, alguien mayor poco familiarizado con la tecnología.</p><p>La diferencia entre lo que dice la lista y lo que ocurre en la prueba real es el hallazgo principal de casi todos los proyectos. Las mejoras se priorizan por impacto sobre las personas, no por facilidad de implementación.</p>',
 'pregunta' => '¿A quién deja fuera, sin querer, el servicio que usamos todos los días?',
 'contexto' => 'Equidad y desarrollo', 'concepto' => 'Comunicación',
 'perfil' => 'Solidario|De mentalidad abierta|Íntegro', 'atl' => 'Colaboración|Pensamiento crítico|Comunicación',
 'objetivos' => 'Aplicar criterios de accesibilidad comprobables|Diseñar y conducir pruebas con personas diversas|Priorizar hallazgos por impacto humano|Comunicar mejoras a quien puede aplicarlas',
 'entregables' => 'Auditoría con doce criterios|Registro de tres pruebas con personas distintas|Comparación entre auditoría y pruebas reales|Informe priorizado entregado al colegio',
 'lenguaje' => 'Investigación', 'dificultad' => 'avanzado', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "// Comparacion auditoria vs. realidad\n// | Criterio | Cumple segun la lista | Que paso en la prueba real | Impacto |\n//\n// Priorizar por: cuantas personas afecta x que tan grave es el bloqueo,\n// nunca por lo facil que sea de arreglar.",
 'fases' => [
   ['indagar', 'La lista y sus límites', 'Aplica doce criterios de accesibilidad al servicio elegido. Anota qué cumple y qué no, solo con la lista.', 'Auditoría de doce criterios completada.', 55],
   ['desarrollar', 'Preparar pruebas con personas', 'Define tres tareas realistas y prepara las sesiones con tres personas de perfiles distintos. Acuerda el consentimiento y el trato.', 'Protocolo de prueba y consentimiento acordado con las tres personas.', 50],
   ['crear', 'Observar sin ayudar', 'Conduce las tres sesiones sin intervenir. Registra cada bloqueo, cuánto duró y cómo lo resolvió o no la persona.', 'Registro de las tres sesiones con los bloqueos cronometrados.', 85],
   ['evaluar', 'Lista contra realidad', 'Compara los hallazgos de la auditoría con los de las pruebas. Prioriza por impacto y entrega el informe a quien administra el servicio.', 'Comparación, informe priorizado y acta de la entrega.', 55],
 ],
 'recursos' => [
   ['plantilla', 'Lista de doce criterios de accesibilidad', 'Comprobables sin herramientas de pago.'],
   ['plantilla', 'Consentimiento para pruebas con personas', 'Qué se registra, para qué y cómo se protege.'],
 ]],
],

];
