<?php
/**
 * Banco de actividades · Nivel N11 (11.º · DP 1 · Informática NM y NS)
 * Rúbrica del Programa del Diploma (criterios A–E de la evaluación interna).
 */

declare(strict_types=1);

return [

['codigo' => 'VCP-11-01', 'titulo' => 'Representación de datos: de la realidad a los bits',
 'objeto' => 'el convertidor de representaciones',
 'resumen' => 'Programar las conversiones entre binario, decimal y hexadecimal, y demostrar los límites de la representación con errores reales.',
 'descripcion' => '<p>El estudiante implementa las conversiones sin usar las funciones del lenguaje, representa enteros con signo en complemento a dos y comprueba con sus propios programas por qué 0.1 + 0.2 no da 0.3. La teoría del tema 2 del programa se vuelve verificable.</p><p>La actividad termina con un caso real: un desbordamiento o un error de precisión que causó un fallo documentado en la industria. El estudiante explica el mecanismo exacto con sus propias conversiones, no con una cita.</p>',
 'pregunta' => '¿Qué información se pierde cuando el mundo se convierte en bits?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Pensador|Informado e instruido', 'atl' => 'Pensamiento crítico|Transferencia',
 'objetivos' => 'Convertir entre sistemas numéricos sin funciones del lenguaje|Representar enteros con signo en complemento a dos|Explicar el error de precisión en coma flotante|Relacionar la representación con fallos reales documentados',
 'entregables' => 'Biblioteca de conversión propia|Demostración del error de coma flotante|Análisis de un fallo real causado por la representación',
 'lenguaje' => 'Java o Python', 'dificultad' => 'intermedio', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "public static String aBinario(int n) {\n    // TODO: sin usar Integer.toBinaryString\n    return \"\";\n}\n\npublic static int deBinario(String b) {\n    // TODO: sin usar parseInt con radix\n    return 0;\n}\n\n// TODO: complemento a dos con 8 bits\n// TODO: demuestra 0.1 + 0.2 != 0.3 y explica por que",
 'fases' => [
   ['indagar', 'Fallos causados por la representación', 'Investiga dos fallos reales atribuidos a desbordamiento o precisión numérica. Determina el tipo de dato implicado y el valor exacto en el que falló.', 'Estudio de dos fallos con el mecanismo técnico identificado.', 45],
   ['desarrollar', 'Diseñar la biblioteca y sus pruebas', 'Define las funciones que implementarás y los casos de prueba de cada una, incluidos los límites: cero, el mayor valor representable y el desbordamiento.', 'Especificación de funciones y quince casos de prueba con sus límites.', 45],
   ['crear', 'Implementar las conversiones', 'Programa las conversiones y el complemento a dos sin usar las funciones incorporadas. Verifica contra las funciones del lenguaje solo al final, para comprobar.', 'Biblioteca completa pasando los quince casos de prueba.', 85],
   ['evaluar', 'Explicar el fallo con tu propio código', 'Reproduce con tu biblioteca el mecanismo del fallo que investigaste. Explica en qué bit exacto se produce el problema y qué habría evitado el error.', 'Reproducción del fallo y explicación técnica con evidencia del código.', 50],
 ],
 'recursos' => [
   ['lectura', 'Complemento a dos y coma flotante IEEE 754', 'Guía con ejemplos de pérdida de precisión.'],
 ]],

['codigo' => 'VCP-11-02', 'titulo' => 'Arquitectura del computador y ciclo de instrucción',
 'objeto' => 'el simulador de la máquina',
 'resumen' => 'Construir un simulador de una máquina mínima que ejecuta un ciclo de búsqueda, decodificación y ejecución.',
 'descripcion' => '<p>El estudiante programa un simulador de una máquina con memoria, contador de programa, registros y un conjunto de ocho instrucciones. Escribe un programa en ese lenguaje ensamblador reducido y lo ejecuta paso a paso viendo el estado de los registros.</p><p>Es la actividad que hace tangible el tema 2 del programa: nadie que haya escrito el ciclo de búsqueda y ejecución vuelve a confundir memoria con procesador. El simulador se usa después como herramienta de estudio para el examen.</p>',
 'pregunta' => '¿Qué ocurre exactamente entre el momento en que ejecuto un programa y el momento en que veo el resultado?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Indagador|Pensador', 'atl' => 'Pensamiento crítico|Organización',
 'objetivos' => 'Describir el ciclo de búsqueda, decodificación y ejecución|Implementar memoria, registros y contador de programa|Definir un conjunto de instrucciones mínimo|Ejecutar y depurar programas en ensamblador propio',
 'entregables' => 'Simulador con ocho instrucciones|Tres programas escritos en el ensamblador propio|Traza paso a paso de la ejecución de uno de ellos',
 'lenguaje' => 'Java o Python', 'dificultad' => 'avanzado', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "memoria = [0] * 64\nacumulador = 0\npc = 0\n\nINSTRUCCIONES = {1: \"CARGA\", 2: \"GUARDA\", 3: \"SUMA\", 4: \"RESTA\",\n                 5: \"SALTA\", 6: \"SALTA_SI_CERO\", 7: \"IMPRIME\", 0: \"ALTO\"}\n\n# TODO: ciclo fetch-decode-execute\n# TODO: muestra el estado de los registros en cada paso",
 'fases' => [
   ['indagar', 'El ciclo en la documentación', 'Consulta dos fuentes sobre el ciclo de instrucción y contrástalas. Anota las diferencias de terminología y elabora tu propia definición con las etapas exactas.', 'Comparación de dos fuentes y definición propia del ciclo.', 45],
   ['desarrollar', 'Diseñar el conjunto de instrucciones', 'Define las ocho instrucciones: código, operando, efecto sobre registros y memoria. Justifica por qué cada una es necesaria y qué programa sería imposible sin ella.', 'Tabla del conjunto de instrucciones con la justificación de cada una.', 50],
   ['crear', 'Programar el simulador', 'Implementa memoria, registros, el ciclo completo y la traza paso a paso. Escribe tres programas: una suma, un conteo y un ciclo con condición.', 'Simulador funcionando y los tres programas ejecutándose.', 100],
   ['evaluar', 'Explicar una ejecución completa', 'Elige uno de tus programas y documenta la traza instrucción por instrucción, indicando qué hace cada etapa del ciclo. Pide a un compañero que prediga el estado final antes de ejecutar.', 'Traza documentada y registro de la predicción del compañero.', 55],
 ],
 'recursos' => [
   ['lectura', 'Ciclo de instrucción y unidad de control', 'Diagrama y descripción de cada etapa.'],
 ]],

['codigo' => 'VCP-11-03', 'titulo' => 'Redes: capas, protocolos y lo que viaja por el cable',
 'objeto' => 'el análisis de tráfico de red',
 'resumen' => 'Observar tráfico real, identificar las capas implicadas y comprobar la diferencia entre una conexión cifrada y una que no lo está.',
 'descripcion' => '<p>El estudiante captura tráfico de su propia navegación en la red del colegio con permiso explícito, identifica los protocolos de cada capa y comprueba de forma empírica qué se ve y qué no se ve en una conexión sin cifrar frente a una cifrada.</p><p>El componente ético es obligatorio y se trata primero: se captura únicamente tráfico propio, con autorización, y se explica por qué hacerlo con el tráfico ajeno es una vulneración. La actividad se realiza sobre un servidor de práctica del propio colegio.</p>',
 'pregunta' => '¿Qué puede ver de mi actividad quien administra la red por la que navego?',
 'contexto' => 'Globalización y sustentabilidad', 'concepto' => 'Sistemas',
 'perfil' => 'Íntegro|Informado e instruido', 'atl' => 'Pensamiento crítico|Alfabetización informacional',
 'objetivos' => 'Identificar protocolos por capa en tráfico real|Comparar tráfico cifrado y sin cifrar|Explicar el papel de cada capa en una petición web|Aplicar criterios éticos y legales a la captura de tráfico',
 'entregables' => 'Captura anotada con las capas identificadas|Comparación de una petición cifrada y una sin cifrar|Documento de consideraciones éticas y legales',
 'lenguaje' => 'Análisis de red', 'dificultad' => 'avanzado', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "# Peticion HTTP minima escrita a mano\nGET /index.html HTTP/1.1\nHost: practica.colegio.local\nUser-Agent: VCodePro-Clase\nConnection: close\n\n# TODO: identifica que capa aporta cada parte de la comunicacion",
 'fases' => [
   ['indagar', 'Marco ético y legal primero', 'Investiga qué dice la normativa sobre la interceptación de comunicaciones y qué política tiene el colegio. Redacta las reglas que seguirás y consigue la autorización escrita.', 'Documento de reglas éticas y autorización del colegio.', 45],
   ['desarrollar', 'Plan de observación', 'Define qué capturarás, en qué servidor de práctica, qué protocolos esperas encontrar y qué campos vas a comparar entre la versión cifrada y la que no lo está.', 'Plan de captura con las hipótesis por capa.', 45],
   ['crear', 'Capturar y anotar', 'Realiza la captura de tu propio tráfico contra el servidor de práctica, en versión cifrada y sin cifrar. Anota en cada paquete la capa y el protocolo correspondiente.', 'Captura anotada con las cuatro capas identificadas.', 85],
   ['evaluar', 'Qué queda expuesto', 'Compara las dos capturas y determina exactamente qué información sigue siendo visible incluso con cifrado. Redacta una recomendación para la comunidad escolar.', 'Comparación documentada y recomendación de una página.', 50],
 ],
 'recursos' => [
   ['lectura', 'Modelo de capas aplicado a una petición web', 'De la resolución de nombres al contenido.'],
   ['plantilla', 'Autorización para prácticas de red', 'Formato para la coordinación del colegio.'],
 ]],

['codigo' => 'VCP-11-04', 'titulo' => 'Estructuras de datos: pilas, colas y listas enlazadas',
 'objeto' => 'la biblioteca de estructuras de datos',
 'resumen' => 'Implementar las tres estructuras desde cero y elegir la adecuada para tres problemas reales distintos.',
 'descripcion' => '<p>El estudiante implementa pila, cola y lista enlazada sin usar las colecciones del lenguaje, con sus operaciones básicas y el manejo de los casos límite: sacar de una estructura vacía, insertar al inicio, recorrer sin perder referencias.</p><p>Después resuelve tres problemas —deshacer acciones, atender turnos, mantener una lista ordenada con inserciones frecuentes— y justifica qué estructura eligió para cada uno con argumentos de complejidad, no de gusto.</p>',
 'pregunta' => '¿Qué estructura elijo cuando la respuesta correcta depende de qué operación se repetirá más?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Pensador|Reflexivo', 'atl' => 'Pensamiento crítico|Transferencia',
 'objetivos' => 'Implementar pila, cola y lista enlazada desde cero|Manejar los casos límite de cada estructura|Analizar la complejidad de cada operación|Justificar la elección de estructura por problema',
 'entregables' => 'Las tres estructuras implementadas y probadas|Tabla de complejidad por operación|Tres problemas resueltos con la estructura justificada',
 'lenguaje' => 'Java', 'dificultad' => 'avanzado', 'sesiones' => 6, 'horas' => 6.0, 'ia' => 1,
 'codigo_inicial' => "class Nodo {\n    int dato;\n    Nodo siguiente;\n    Nodo(int dato) { this.dato = dato; }\n}\n\nclass ListaEnlazada {\n    private Nodo cabeza;\n    private int tamano;\n\n    public void insertarInicio(int dato) {\n        // TODO\n    }\n    // TODO: insertarFinal, eliminar, buscar, recorrer\n}",
 'fases' => [
   ['indagar', 'Dónde aparece cada estructura', 'Encuentra tres usos reales, uno por estructura, en software que utilizas a diario. Explica qué operación es la más frecuente en cada caso.', 'Tres usos reales con la operación dominante identificada.', 45],
   ['desarrollar', 'Especificar operaciones y límites', 'Define para cada estructura sus operaciones, qué hace ante una estructura vacía o llena, y la complejidad esperada de cada operación.', 'Especificación de las tres estructuras con su tabla de complejidad.', 50],
   ['crear', 'Implementar y probar', 'Programa las tres estructuras sin usar las colecciones del lenguaje. Escribe pruebas para los casos límite: vacío, un solo elemento, eliminar el primero y el último.', 'Las tres estructuras con al menos dieciocho pruebas pasando.', 110],
   ['evaluar', 'Elegir con argumentos', 'Resuelve los tres problemas planteados y justifica la estructura elegida en cada uno con la tabla de complejidad. Mide el tiempo real con diez mil elementos y compáralo con lo previsto.', 'Tres soluciones justificadas y medición empírica contrastada con la teoría.', 60],
 ],
 'recursos' => [
   ['lectura', 'Pilas, colas y listas: operaciones y costos', 'Tabla de complejidad de referencia.'],
 ]],

['codigo' => 'VCP-11-05', 'titulo' => 'Árboles binarios y recorridos',
 'objeto' => 'el árbol binario de búsqueda',
 'resumen' => 'Implementar un árbol binario de búsqueda, sus tres recorridos y comprobar el efecto del orden de inserción en el rendimiento.',
 'descripcion' => '<p>Contenido de Nivel Superior. El estudiante implementa el árbol con inserción, búsqueda y los recorridos en orden previo, en orden e in orden posterior, y comprueba que el recorrido in orden devuelve los datos ordenados.</p><p>El descubrimiento clave es el desequilibrio: al insertar datos ya ordenados, el árbol degenera en una lista y la búsqueda pasa de logarítmica a lineal. El estudiante lo mide con datos reales y explica por qué existen los árboles equilibrados, aunque no los implemente.</p>',
 'pregunta' => '¿Por qué la misma estructura puede ser rapidísima o lentísima según cómo se llene?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Relaciones',
 'perfil' => 'Pensador|Indagador', 'atl' => 'Pensamiento crítico|Transferencia',
 'objetivos' => 'Implementar inserción y búsqueda en un árbol binario|Programar los tres recorridos recursivos|Medir la altura del árbol según el orden de inserción|Relacionar altura con complejidad de búsqueda',
 'entregables' => 'Árbol implementado con los tres recorridos|Medición de altura con inserción aleatoria y ordenada|Explicación del caso degenerado con datos propios',
 'lenguaje' => 'Java', 'dificultad' => 'avanzado', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "class NodoArbol {\n    int valor;\n    NodoArbol izquierda, derecha;\n    NodoArbol(int valor) { this.valor = valor; }\n}\n\n// TODO: insertar(valor) manteniendo la propiedad de busqueda\n// TODO: enOrden(), preOrden(), postOrden()\n// TODO: altura() para medir el desequilibrio",
 'fases' => [
   ['indagar', 'Para qué sirve un árbol', 'Investiga dos aplicaciones reales de árboles binarios de búsqueda. Determina en cada caso qué operación se realiza más y por qué el árbol es mejor que una lista.', 'Dos aplicaciones documentadas con la operación dominante.', 40],
   ['desarrollar', 'Diseñar la estructura y las pruebas', 'Define la clase, sus operaciones y los casos de prueba: árbol vacío, un nodo, insertar repetido, buscar inexistente. Predice la altura para veinte valores aleatorios y para veinte ordenados.', 'Especificación, doce casos de prueba y las dos predicciones de altura.', 50],
   ['crear', 'Implementar y recorrer', 'Programa la inserción, la búsqueda, los tres recorridos y el cálculo de altura. Comprueba que el recorrido in orden devuelve la secuencia ordenada.', 'Árbol funcionando con los tres recorridos verificados.', 95],
   ['evaluar', 'Medir el desequilibrio', 'Inserta mil valores aleatorios y mil ordenados en árboles distintos. Mide altura y comparaciones por búsqueda en cada uno. Contrasta con tus predicciones y explica la diferencia.', 'Mediciones de los dos árboles y explicación del caso degenerado.', 55],
 ],
 'recursos' => [
   ['lectura', 'Recorridos de árboles y recursión', 'Los tres recorridos con la traza de un ejemplo.'],
 ]],

['codigo' => 'VCP-11-06', 'titulo' => 'Ordenamiento y búsqueda: medir la eficiencia',
 'objeto' => 'el estudio de eficiencia algorítmica',
 'resumen' => 'Implementar tres algoritmos de ordenamiento, medir su comportamiento real y contrastarlo con la complejidad teórica.',
 'descripcion' => '<p>El estudiante implementa ordenamiento por burbuja, por inserción y por mezcla, y los mide con conjuntos de 100, 1.000 y 10.000 elementos en tres condiciones: aleatorio, ya ordenado y ordenado al revés. Los datos rara vez coinciden con la intuición.</p><p>El análisis final relaciona las mediciones con la notación asintótica: por qué el algoritmo cuadrático gana con cien elementos y pierde estrepitosamente con diez mil, y por qué el mejor caso de la inserción es lineal.</p>',
 'pregunta' => '¿Cuándo importa realmente la eficiencia y cuándo estoy optimizando lo que no debo?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Relaciones',
 'perfil' => 'Pensador|Íntegro', 'atl' => 'Pensamiento crítico|Transferencia',
 'objetivos' => 'Implementar tres algoritmos de ordenamiento|Diseñar un experimento de medición reproducible|Relacionar mediciones con notación asintótica|Distinguir mejor caso, caso medio y peor caso',
 'entregables' => 'Los tres algoritmos implementados|Tabla de mediciones en nueve condiciones|Gráfica y análisis contrastado con la teoría',
 'lenguaje' => 'Java o Python', 'dificultad' => 'avanzado', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "import time, random\n\ndef burbuja(a):\n    comparaciones = 0\n    # TODO: cuenta comparaciones e intercambios\n    return comparaciones\n\n# TODO: insercion(a) y mezcla(a)\n# TODO: mide tiempo y comparaciones para n = 100, 1000, 10000",
 'fases' => [
   ['indagar', 'Predecir antes de medir', 'Estudia la complejidad teórica de los tres algoritmos. Predice por escrito qué pasará en cada una de las nueve condiciones antes de ejecutar nada.', 'Tabla de nueve predicciones justificadas con la teoría.', 45],
   ['desarrollar', 'Diseñar el experimento', 'Define cómo medirás: cuántas repeticiones, qué cuentas (tiempo, comparaciones, intercambios), cómo generas los datos y cómo evitas que el orden de ejecución afecte el resultado.', 'Protocolo experimental reproducible.', 45],
   ['crear', 'Implementar y medir', 'Programa los tres algoritmos con contadores y ejecuta las nueve condiciones. Registra tiempo y comparaciones y genera la gráfica de crecimiento.', 'Tabla de nueve mediciones y gráfica de crecimiento.', 90],
   ['evaluar', 'Teoría contra realidad', 'Contrasta cada predicción con la medición. Explica las discrepancias, incluida la ventaja de los algoritmos cuadráticos en conjuntos pequeños.', 'Análisis de las nueve comparaciones con explicación de las discrepancias.', 55],
 ],
 'recursos' => [
   ['lectura', 'Notación asintótica sin matemáticas pesadas', 'O grande explicada con las mediciones del aula.'],
 ]],

['codigo' => 'VCP-11-07', 'titulo' => 'Programación orientada a objetos en Java',
 'objeto' => 'el sistema orientado a objetos',
 'resumen' => 'Diseñar un sistema con interfaces, clases abstractas y encapsulación estricta, aplicando el estándar del examen.',
 'descripcion' => '<p>El estudiante construye un sistema mediano en Java aplicando lo que el programa exige: encapsulación con acceso controlado, herencia justificada, interfaces para el comportamiento común y sobrescritura correcta de métodos.</p><p>La actividad usa el estándar de escritura del examen —convenciones de nombres, documentación de cada método, manejo explícito de excepciones— porque en 12.º ese estándar deja de ser negociable.</p>',
 'pregunta' => '¿Cuándo uso herencia, cuándo una interfaz y cuándo simplemente composición?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Pensador|Íntegro', 'atl' => 'Organización|Pensamiento crítico',
 'objetivos' => 'Aplicar encapsulación con acceso controlado|Diseñar interfaces y clases abstractas|Justificar herencia frente a composición|Documentar según el estándar del examen',
 'entregables' => 'Diagrama de clases con interfaces|Sistema implementado en Java|Documentación de cada clase pública y justificación de la jerarquía',
 'lenguaje' => 'Java', 'dificultad' => 'avanzado', 'sesiones' => 6, 'horas' => 6.0, 'ia' => 1,
 'codigo_inicial' => "public interface Prestable {\n    int diasPrestamo();\n    boolean disponible();\n}\n\npublic abstract class Material implements Prestable {\n    private final String codigo;\n    private String titulo;\n\n    protected Material(String codigo, String titulo) {\n        this.codigo = codigo;\n        this.titulo = titulo;\n    }\n    // TODO: getters, equals, toString\n}",
 'fases' => [
   ['indagar', 'Jerarquías que envejecen mal', 'Analiza dos jerarquías de clases de un proyecto propio o de ejemplo. Identifica dónde la herencia obligó a soluciones forzadas y qué habría resuelto una interfaz.', 'Análisis de dos jerarquías con los problemas identificados.', 45],
   ['desarrollar', 'Diseñar la jerarquía correcta', 'Diseña el diagrama de clases decidiendo para cada relación si corresponde herencia, interfaz o composición. Justifica cada decisión por escrito.', 'Diagrama de clases con la justificación de cada relación.', 55],
   ['crear', 'Implementar con el estándar del examen', 'Programa el sistema con encapsulación estricta, interfaces implementadas y documentación de cada método público. Maneja las excepciones de forma explícita.', 'Sistema implementado y documentado según el estándar.', 110],
   ['evaluar', 'Prueba de extensión', 'Agrega un tipo nuevo que no estaba previsto y mide cuántas clases existentes tuviste que modificar. Si fueron más de dos, analiza qué decisión de diseño lo causó.', 'Extensión implementada y análisis del impacto en el diseño.', 55],
 ],
 'recursos' => [
   ['lectura', 'Estándar de escritura de código del examen', 'Convenciones exigidas y errores frecuentes.'],
 ]],

['codigo' => 'VCP-11-08', 'titulo' => 'Modelado de datos y SQL avanzado',
 'objeto' => 'el modelo de datos avanzado',
 'resumen' => 'Consultas con agregación, subconsultas y varias tablas, con análisis del efecto de los índices en el rendimiento.',
 'descripcion' => '<p>El estudiante trabaja sobre una base de datos con decenas de miles de filas y responde preguntas que exigen agregación, agrupación, subconsultas y uniones múltiples. Después analiza el plan de ejecución y comprueba con mediciones el efecto de añadir un índice.</p><p>La actividad cubre la opción de bases de datos del programa y establece un hábito profesional: nunca afirmar que una consulta es lenta o rápida sin haberla medido.</p>',
 'pregunta' => '¿Por qué la misma consulta tarda un segundo en una tabla y un minuto en otra?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Relaciones',
 'perfil' => 'Pensador|Indagador', 'atl' => 'Pensamiento crítico|Organización',
 'objetivos' => 'Escribir consultas con agregación y subconsultas|Unir tres o más tablas correctamente|Leer un plan de ejecución|Medir el efecto de un índice con datos reales',
 'entregables' => 'Quince consultas que responden preguntas de negocio|Plan de ejecución antes y después del índice|Informe de mediciones con conclusiones',
 'lenguaje' => 'SQL', 'dificultad' => 'avanzado', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "-- Preguntas de negocio a responder\n-- 1. Cuantos prestamos por mes y por grado\n-- 2. Estudiantes sin ningun prestamo en el semestre\n-- 3. Los cinco titulos mas prestados con su porcentaje sobre el total\n\nEXPLAIN SELECT ...;\n-- TODO: analiza el plan, agrega el indice y vuelve a medir",
 'fases' => [
   ['indagar', 'Preguntas que importan', 'Recoge quince preguntas reales que la coordinación necesita responder sobre los datos. Clasifícalas por el tipo de operación SQL que requerirán.', 'Quince preguntas clasificadas por tipo de consulta.', 45],
   ['desarrollar', 'Diseñar las consultas', 'Escribe el pseudocódigo de cada consulta: qué tablas, qué unión, qué agrupación y qué filtro. Predice cuáles serán lentas y por qué.', 'Diseño de las quince consultas con la predicción de rendimiento.', 50],
   ['crear', 'Escribir, ejecutar y medir', 'Implementa las quince consultas sobre la base con datos masivos. Mide el tiempo de cada una y guarda el plan de ejecución de las tres más lentas.', 'Quince consultas funcionando con sus mediciones y tres planes de ejecución.', 95],
   ['evaluar', 'El efecto del índice', 'Añade un índice a las tres consultas lentas y vuelve a medir. Documenta la mejora, y también el costo del índice en las operaciones de escritura.', 'Comparación antes y después con el análisis del costo del índice.', 55],
 ],
 'recursos' => [
   ['dataset', 'Base de datos de práctica con 50.000 filas', 'Datos generados para medir rendimiento.'],
   ['lectura', 'Cómo leer un plan de ejecución', 'Recorrido completo de tabla frente a uso de índice.'],
 ]],

['codigo' => 'VCP-11-09', 'titulo' => 'Planteamiento y diseño de la evaluación interna',
 'objeto' => 'la propuesta de la evaluación interna',
 'resumen' => 'Proyecto insignia de 11.º: elegir cliente y problema reales, acordar criterios de éxito y producir el diseño completo de la solución.',
 'descripcion' => '<p>El estudiante identifica un cliente real fuera del aula, documenta el problema con una entrevista grabada o registrada, acuerda los criterios de éxito y entrega el diseño completo: diagramas, estructuras de datos, prototipo de la interfaz y registro de desarrollo planificado.</p><p>Es la actividad que determina la calidad de todo el trabajo de 12.º. Un problema demasiado pequeño no permite alcanzar los descriptores altos del criterio C; uno demasiado grande no se termina. La actividad incluye una revisión de viabilidad con el docente antes de aprobar el alcance.</p>',
 'pregunta' => '¿Es este problema lo bastante grande para demostrar lo que sé y lo bastante pequeño para terminarlo?',
 'contexto' => 'Equidad y desarrollo', 'concepto' => 'Sistemas',
 'perfil' => 'Indagador|Audaz|Íntegro', 'atl' => 'Autogestión|Organización|Comunicación',
 'objetivos' => 'Identificar y consultar a un cliente real|Definir criterios de éxito medibles y acordados|Producir el diseño completo de la solución|Evaluar la viabilidad del alcance con evidencia',
 'entregables' => 'Registro de la consulta al cliente|Criterios de éxito acordados|Diseño completo con diagramas y estructuras de datos|Cronograma y evaluación de viabilidad',
 'lenguaje' => 'Documentación', 'dificultad' => 'avanzado', 'sesiones' => 7, 'horas' => 8.0, 'ia' => 1,
 'codigo_inicial' => "// Estructura de la propuesta\n// 1. Escenario y cliente (con evidencia de la consulta)\n// 2. Justificacion de la solucion propuesta\n// 3. Criterios de exito (medibles, acordados con el cliente)\n// 4. Diagramas: flujo, clases, estructura de datos\n// 5. Prototipo de interfaz\n// 6. Cronograma con hitos",
 'fases' => [
   ['indagar', 'Cliente, problema y evidencia', 'Identifica un cliente real y entrevístalo con registro. Documenta el proceso actual, sus tiempos y sus fallos. Descarta al menos una idea inicial y explica por qué.', 'Registro de la consulta, análisis del proceso actual y descarte justificado.', 100],
   ['desarrollar', 'Criterios de éxito y diseño', 'Acuerda con el cliente entre seis y ocho criterios de éxito medibles. Produce los diagramas, las estructuras de datos y el prototipo de interfaz.', 'Criterios acordados con firma del cliente y diseño completo.', 130],
   ['crear', 'Prototipo funcional mínimo', 'Implementa un prototipo que demuestre la parte técnicamente más riesgosa de la solución. El objetivo no es avanzar sino comprobar que lo difícil es posible.', 'Prototipo del componente más riesgoso funcionando.', 100],
   ['evaluar', 'Revisión de viabilidad', 'Presenta el alcance al docente y al cliente. Evalúa si el proyecto permite alcanzar los descriptores altos del criterio C y si cabe en el tiempo disponible. Ajusta el alcance con evidencia.', 'Acta de revisión de viabilidad y alcance ajustado.', 60],
 ],
 'recursos' => [
   ['plantilla', 'Formato de propuesta de evaluación interna', 'Estructura alineada con los criterios A y B.'],
   ['plantilla', 'Acuerdo de criterios de éxito con el cliente', 'Formato de acta con firma.'],
 ]],

['codigo' => 'VCP-11-10', 'titulo' => 'Aprendizaje automático con datos del colegio',
 'objeto' => 'el modelo de clasificación',
 'resumen' => 'Entrenar un clasificador con datos propios, evaluarlo con separación correcta de conjuntos y explicar por qué se equivoca.',
 'descripcion' => '<p>El estudiante prepara un conjunto de datos propio, lo divide en entrenamiento y prueba, entrena un clasificador sencillo y lo evalúa con matriz de confusión. Aparece la lección más importante del área: un modelo evaluado con los datos con los que se entrenó no dice nada.</p><p>El cierre exige interpretabilidad: el estudiante debe explicar tres predicciones concretas, incluidas dos equivocadas, y proponer qué dato adicional habría cambiado el resultado. Conecta con la actividad de sesgo de 10.º.</p>',
 'pregunta' => '¿Qué significa que un modelo aprendió, y cómo lo demuestro?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Relaciones',
 'perfil' => 'Indagador|Pensador|Íntegro', 'atl' => 'Pensamiento crítico|Alfabetización informacional',
 'objetivos' => 'Preparar y dividir un conjunto de datos correctamente|Entrenar un clasificador y evaluarlo con datos no vistos|Interpretar una matriz de confusión|Explicar predicciones concretas y sus errores',
 'entregables' => 'Conjunto de datos preparado y documentado|Modelo entrenado con separación de conjuntos|Matriz de confusión y análisis de tres predicciones',
 'lenguaje' => 'Python', 'dificultad' => 'avanzado', 'sesiones' => 5, 'horas' => 5.0, 'ia' => 1,
 'codigo_inicial' => "# Separacion correcta de conjuntos\ndatos = cargar()\nrandom.shuffle(datos)\ncorte = int(len(datos) * 0.7)\nentrenamiento, prueba = datos[:corte], datos[corte:]\n\n# TODO: entrena solo con entrenamiento\n# TODO: evalua solo con prueba\n# TODO: matriz de confusion con las cuatro celdas",
 'fases' => [
   ['indagar', 'Qué se puede y qué no se puede predecir', 'Formula tres preguntas de predicción con datos del colegio y evalúa para cada una si los datos disponibles pueden responderla y si es ético intentarlo.', 'Tres preguntas evaluadas por viabilidad técnica y ética.', 50],
   ['desarrollar', 'Preparar los datos', 'Documenta el conjunto: origen, número de registros, características, distribución de clases y datos faltantes. Define la estrategia de división y por qué esa proporción.', 'Ficha del conjunto de datos y estrategia de división justificada.', 50],
   ['crear', 'Entrenar y evaluar', 'Entrena el clasificador únicamente con el conjunto de entrenamiento y evalúalo con el de prueba. Construye la matriz de confusión y calcula exactitud, precisión y exhaustividad.', 'Modelo entrenado con la evaluación completa y la matriz de confusión.', 90],
   ['evaluar', 'Explicar tres predicciones', 'Elige una predicción correcta y dos equivocadas. Explica qué características llevaron al modelo a cada resultado y qué dato adicional lo habría corregido.', 'Análisis de tres predicciones con la propuesta de mejora del conjunto.', 55],
 ],
 'recursos' => [
   ['lectura', 'Matriz de confusión y sus métricas', 'Cuándo la exactitud engaña.'],
   ['plantilla', 'Ficha de conjunto de datos', 'Origen, tamaño, características, sesgos conocidos.'],
 ]],

];
