<?php
/**
 * Banco de actividades · Nivel N6 (6.º · PAI 1 · Diseño)
 */

declare(strict_types=1);

return [

['codigo' => 'VCP-6-01', 'titulo' => 'Mi ficha de presentación digital',
 'objeto' => 'la ficha de presentación',
 'resumen' => 'Primer programa en Python: pedir datos al usuario, guardarlos en variables y devolver una ficha ordenada en pantalla.',
 'descripcion' => '<p>El estudiante escribe el primer programa de su vida y descubre las tres piezas que se repetirán durante siete años: <strong>entrada, proceso y salida</strong>. El producto es una ficha de presentación que pregunta el nombre, la edad, el curso y un dato curioso, y devuelve un texto formateado que el estudiante puede pegar en la cartelera del salón.</p><p>La actividad se enfoca deliberadamente en algo personal: el primer programa debe hablar de quien lo escribe. Al final de la sesión cada estudiante ejecuta el programa de un compañero y detecta al menos un caso en el que la ficha se ve mal (un nombre muy largo, una edad escrita con letras). Ese descubrimiento se convierte en la primera lista de mejoras del curso.</p>',
 'pregunta' => 'Como una computadora solo sigue instrucciones, ¿que tan precisas deben ser mis instrucciones para que el resultado sea siempre correcto?',
 'contexto' => 'Identidades y relaciones', 'concepto' => 'Comunicación',
 'perfil' => 'Indagador|Buen comunicador', 'atl' => 'Organización|Comunicación',
 'objetivos' => 'Distinguir entrada, proceso y salida en un programa|Usar variables para guardar datos del usuario|Dar formato a la salida de texto|Ejecutar y corregir un programa propio',
 'entregables' => 'Archivo ficha.py que funciona|Captura de pantalla de la ejecución|Lista de tres mejoras detectadas al probar el programa de un compañero',
 'lenguaje' => 'Python', 'dificultad' => 'inicial', 'sesiones' => 3, 'horas' => 3.0, 'ia' => 1,
 'codigo_inicial' => "# Ficha de presentacion - VCodePro\n# Completa las lineas marcadas con TODO\n\nnombre = input(\"Como te llamas? \")\n# TODO: pide la edad y guardala en una variable\n# TODO: pide el curso\n\nprint(\"----------------------------\")\nprint(\"Ficha de\", nombre)\n# TODO: muestra la edad y el curso\nprint(\"----------------------------\")",
 'fases' => [
   ['indagar', 'Que hace un buen programa de presentación', 'Observa tres fichas de presentación en papel o en la web (carné estudiantil, perfil de red social, credencial de un evento). Anota que datos aparecen siempre y cuales sobran. Escribe con tus palabras que problema resuelve una ficha de presentación.', 'Tabla comparativa de tres fichas y una frase que enuncie el problema.', 50],
   ['desarrollar', 'Diseño de la salida en papel', 'Antes de programar, dibuja en el cuaderno como quieres que se vea la ficha en pantalla: que línea va primero, que separadores usarás, cuantos datos pedirás. Escribe la lista de especificaciones: la ficha debe pedir al menos cuatro datos y mostrarlos alineados.', 'Boceto de la salida y lista de cuatro especificaciones.', 45],
   ['crear', 'Escribir el programa', 'Abre VCodePro y crea ficha.py. Usa input() para pedir cada dato y print() para mostrar la ficha. Ejecuta después de cada línea nueva: no escribas veinte líneas y luego busques el error. Registra en la bitácora cada vez que algo falle y como lo resolviste.', 'Archivo ficha.py que se ejecuta sin errores.', 60],
   ['evaluar', 'Prueba cruzada con un compañero', 'Intercambia el programa con un compañero. Cada uno ejecuta el del otro tres veces con datos distintos, incluyendo un nombre muy largo y una edad escrita con letras. Anota que se rompió y compara el resultado con tus cuatro especificaciones.', 'Registro de pruebas con tres casos y tres mejoras propuestas.', 45],
 ],
 'recursos' => [
   ['plantilla', 'Plantilla de especificaciones de diseño', 'Documento con las cuatro columnas: especificación, como se comprueba, resultado, evidencia.'],
   ['lectura', 'Entrada, proceso y salida', 'Ficha de una página con ejemplos cotidianos del modelo EPS.'],
   ['codigo', 'ficha_base.py', 'Archivo de inicio con los TODO marcados.'],
 ]],

['codigo' => 'VCP-6-02', 'titulo' => 'El robot que sigue instrucciones',
 'objeto' => 'el algoritmo del robot',
 'resumen' => 'Escribir algoritmos en lenguaje natural y comprobarlos haciendo que un compañero los ejecute al pie de la letra.',
 'descripcion' => '<p>Actividad puente entre el pensamiento y el código. Por parejas, un estudiante escribe las instrucciones para que su compañero —que actúa como robot— dibuje una figura en el tablero sin verla. El robot solo puede hacer exactamente lo que dice la instrucción. La primera ronda casi siempre fracasa, y ese fracaso es el contenido de la clase.</p><p>Después se traduce el algoritmo depurado a Python con la tortuga: <code>forward</code>, <code>left</code>, <code>right</code>. El estudiante comprueba que la máquina es igual de literal que su compañero, y entiende por que la precisión no es una manía del profesor sino un requisito del medio.</p>',
 'pregunta' => '¿Por que un algoritmo que yo entiendo perfectamente puede ser imposible de seguir para otro?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Pensador|Buen comunicador', 'atl' => 'Pensamiento crítico|Colaboración',
 'objetivos' => 'Escribir un algoritmo paso a paso sin ambigüedades|Detectar instrucciones ambiguas al ejecutarlas literalmente|Traducir un algoritmo en lenguaje natural a código|Usar el módulo turtle para dibujar figuras',
 'entregables' => 'Algoritmo en lenguaje natural (versión 1 y versión corregida)|Programa robot.py que dibuja la figura|Reflexión de cinco líneas sobre que instrucción falló y por que',
 'lenguaje' => 'Python', 'dificultad' => 'inicial', 'sesiones' => 3, 'horas' => 3.0, 'ia' => 0,
 'codigo_inicial' => "import turtle\n\nt = turtle.Turtle()\nt.speed(3)\n\n# TODO: traduce aqui tu algoritmo corregido\n# t.forward(100)\n# t.left(90)\n\nturtle.done()",
 'fases' => [
   ['indagar', 'Instrucciones que fallan', 'Busca tres ejemplos de instrucciones mal escritas en la vida real (un instructivo de armado, una receta, una señal). Explica en cada caso que información falta y que podría salir mal.', 'Ficha con tres ejemplos y la información faltante de cada uno.', 45],
   ['desarrollar', 'Escribir el algoritmo del robot', 'Elige una figura sencilla (cuadrado, casa, escalera). Escribe las instrucciones numeradas para dibujarla. Solo puedes usar avanzar, girar a la izquierda, girar a la derecha, levantar y bajar el lápiz, indicando siempre cuanto.', 'Algoritmo numerado, versión 1.', 40],
   ['crear', 'Ejecutar con un humano y luego con la tortuga', 'Tu compañero ejecuta tu algoritmo al pie de la letra. Corrige las instrucciones ambiguas y produce la versión 2. Luego traduce esa versión a Python con turtle y ejecútala.', 'Algoritmo versión 2 y archivo robot.py que dibuja la figura.', 70],
   ['evaluar', 'Comparar los dos dibujos', 'Pon lado a lado el dibujo hecho por tu compañero, el de la tortuga y tu boceto original. Explica las diferencias y decide si el problema estaba en el algoritmo o en la traducción a código.', 'Comparación de los tres resultados y conclusión escrita.', 45],
 ],
 'recursos' => [
   ['plantilla', 'Hoja de algoritmo numerado', 'Formato de dos columnas: paso e instrucción exacta.'],
   ['lectura', 'La tortuga de Python en diez comandos', 'Referencia rápida de turtle para el aula.'],
 ]],

['codigo' => 'VCP-6-03', 'titulo' => 'Dibuja tu bandera con ciclos',
 'objeto' => 'el programa de la bandera',
 'resumen' => 'Descubrir el ciclo for repitiendo trazos: de veinte líneas copiadas a cuatro líneas que se repiten.',
 'descripcion' => '<p>El estudiante dibuja primero una figura repetitiva copiando y pegando instrucciones. Cuando el archivo llega a treinta líneas iguales, el docente introduce el ciclo <code>for</code> y el mismo dibujo cabe en cuatro líneas. La comparación entre los dos archivos es la mejor definición de ciclo que un estudiante de once años puede recibir.</p><p>El producto final es la bandera de un país, un departamento o un club inventado, dibujada con la tortuga usando al menos dos ciclos. La actividad conecta con Individuos y Sociedades si el estudiante debe explicar el significado de los colores de la bandera elegida.</p>',
 'pregunta' => '¿Cuando conviene repetir instrucciones y cuando conviene pedirle a la máquina que las repita por mi?',
 'contexto' => 'Expresión personal y cultural', 'concepto' => 'Lógica',
 'perfil' => 'Pensador|Informado e instruido', 'atl' => 'Pensamiento crítico|Transferencia',
 'objetivos' => 'Identificar patrones repetitivos en un dibujo|Escribir ciclos for con rango|Anidar dos ciclos sencillos|Usar colores y relleno en turtle',
 'entregables' => 'Archivo bandera.py con al menos dos ciclos|Imagen del resultado|Comparación entre la versión sin ciclos y la versión con ciclos',
 'lenguaje' => 'Python', 'dificultad' => 'inicial', 'sesiones' => 3, 'horas' => 3.0, 'ia' => 1,
 'codigo_inicial' => "import turtle\n\nt = turtle.Turtle()\nt.speed(0)\n\ndef franja(color, ancho, alto):\n    t.fillcolor(color)\n    t.begin_fill()\n    for lado in range(2):\n        t.forward(ancho)\n        t.right(90)\n        t.forward(alto)\n        t.right(90)\n    t.end_fill()\n\n# TODO: usa un ciclo for para dibujar las franjas de tu bandera\nturtle.done()",
 'fases' => [
   ['indagar', 'Buscar el patrón', 'Elige una bandera y descompónla en figuras repetidas: franjas, estrellas, círculos. Marca en el dibujo cuantas veces se repite cada elemento y que cambia entre una repetición y otra.', 'Bandera anotada con el conteo de repeticiones.', 40],
   ['desarrollar', 'Del patrón al ciclo', 'Escribe en lenguaje natural: repetir 3 veces (dibujar franja, bajar 40 px). Identifica que valor cambia en cada vuelta, porque ese será tu variable de ciclo.', 'Pseudocódigo con los ciclos identificados y la variable que cambia.', 40],
   ['crear', 'Programar la bandera', 'Escribe primero la versión larga sin ciclos y guárdala como bandera_larga.py. Luego reescríbela con ciclos en bandera.py. Cuenta las líneas de cada archivo.', 'Los dos archivos y el conteo de líneas.', 70],
   ['evaluar', 'Que gané y que perdí', 'Compara los dos archivos: cual es más corto, cual es más fácil de modificar si te piden cinco franjas en vez de tres, cual entendería mejor un compañero. Pide a un compañero que cambie el número de franjas en ambos y cronometra.', 'Tabla comparativa y conclusión sobre la utilidad de los ciclos.', 40],
 ],
 'recursos' => [
   ['lectura', 'El ciclo for explicado con dibujos', 'Guía visual de una página.'],
   ['dataset', 'Banderas y su significado', 'Listado de banderas sencillas de dibujar y el significado de sus colores.'],
 ]],

['codigo' => 'VCP-6-04', 'titulo' => 'La calculadora de la tienda escolar',
 'objeto' => 'la calculadora de la tienda',
 'resumen' => 'Programa que suma pedidos, aplica descuento por cantidad y devuelve el cambio exacto.',
 'descripcion' => '<p>La tienda escolar es un problema real, cercano y medible. El estudiante construye una calculadora que recibe cantidades y precios, calcula el total, aplica un descuento cuando la compra supera cierto valor y calcula el cambio. Aparecen los operadores aritméticos, el redondeo y —por primera vez— la necesidad de validar que el usuario no escriba texto donde va un número.</p><p>La actividad exige contrastar el resultado del programa con el de una calculadora de mano en cinco pedidos distintos. Cuando los dos resultados no coinciden, el estudiante debe explicar por que: casi siempre es un problema de redondeo, y esa conversación vale más que la solución.</p>',
 'pregunta' => '¿Puedo confiar en el resultado de un programa que yo mismo escribí?',
 'contexto' => 'Equidad y desarrollo', 'concepto' => 'Sistemas',
 'perfil' => 'Íntegro|Pensador', 'atl' => 'Pensamiento crítico|Organización',
 'objetivos' => 'Usar operadores aritméticos y variables numéricas|Convertir texto a número con int y float|Aplicar una condición para el descuento|Redondear resultados monetarios correctamente',
 'entregables' => 'Archivo tienda.py|Tabla de cinco pedidos con el resultado del programa y el de la calculadora|Explicación de las diferencias encontradas',
 'lenguaje' => 'Python', 'dificultad' => 'inicial', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "# Calculadora de la tienda escolar\nPRECIOS = {\"empanada\": 2500, \"jugo\": 3000, \"galleta\": 1800}\n\nproducto = input(\"Producto: \")\ncantidad = int(input(\"Cantidad: \"))\n\n# TODO: calcula el subtotal\n# TODO: aplica 10% de descuento si el subtotal supera 20000\n# TODO: pide con cuanto paga el cliente y calcula el cambio",
 'fases' => [
   ['indagar', 'Como cobra realmente la tienda', 'Entrevista a quien atiende la tienda escolar o a un adulto que maneje una caja. Averigua que descuentos existen, como redondean los precios y que errores cometen con más frecuencia.', 'Resumen de la entrevista con al menos cinco datos concretos.', 45],
   ['desarrollar', 'Reglas del negocio en papel', 'Escribe las reglas exactas: lista de precios, umbral de descuento, porcentaje, redondeo. Cada regla debe poder comprobarse con un ejemplo numérico.', 'Lista de reglas con un ejemplo numérico por regla.', 45],
   ['crear', 'Programar y probar sobre la marcha', 'Implementa el programa por partes: primero el subtotal, prueba; luego el descuento, prueba; luego el cambio, prueba. Nunca avances a la siguiente parte con la anterior fallando.', 'Archivo tienda.py con las tres partes funcionando.', 80],
   ['evaluar', 'Contraste con la calculadora de mano', 'Toma cinco pedidos reales y calcula el total a mano. Compara con el programa. Donde haya diferencia, explica la causa y corrige.', 'Tabla de cinco casos, diferencias y correcciones aplicadas.', 50],
 ],
 'recursos' => [
   ['plantilla', 'Tabla de casos de prueba', 'Formato: entrada, resultado esperado, resultado obtenido, coincide.'],
   ['lectura', 'Redondeo de dinero en programación', 'Por que 0.1 + 0.2 no siempre da 0.3.'],
 ]],

['codigo' => 'VCP-6-05', 'titulo' => 'Adivina el número: decisiones y repeticiones',
 'objeto' => 'el juego de adivinanza',
 'resumen' => 'Juego clásico que introduce el condicional, el ciclo while y el número aleatorio, con una estrategia ganadora que el estudiante debe descubrir.',
 'descripcion' => '<p>El programa piensa un número entre 1 y 100 y el jugador intenta adivinarlo; el programa responde mayor o menor. Con esta actividad aparecen las tres estructuras que faltaban: la condición, la repetición indefinida y el azar. El estudiante además cuenta los intentos y descubre por experimentación la búsqueda binaria: partir siempre por la mitad.</p><p>El cierre pedagógico es importante: se compara la cantidad de intentos de quien adivina al azar con la de quien parte por la mitad. Esa comparación es la primera intuición de eficiencia algorítmica del plan de estudios, y se retomará literalmente en 11.º.</p>',
 'pregunta' => '¿Existe una forma de adivinar que garantice ganar en pocos intentos, o todo depende de la suerte?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Lógica',
 'perfil' => 'Pensador|Audaz', 'atl' => 'Pensamiento crítico|Reflexión',
 'objetivos' => 'Escribir condicionales if, elif y else|Controlar un ciclo while con una condición de salida|Generar números aleatorios|Contar intentos y comparar estrategias',
 'entregables' => 'Archivo adivina.py con conteo de intentos|Registro de diez partidas con dos estrategias|Conclusión sobre cual estrategia es mejor y por que',
 'lenguaje' => 'Python', 'dificultad' => 'inicial', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "import random\n\nsecreto = random.randint(1, 100)\nintentos = 0\n\nwhile True:\n    intento = int(input(\"Tu numero: \"))\n    intentos = intentos + 1\n    # TODO: si es igual al secreto, felicita y sal del ciclo\n    # TODO: si es menor, di 'mas alto'\n    # TODO: si es mayor, di 'mas bajo'",
 'fases' => [
   ['indagar', 'Reglas de un juego justo', 'Juega tres veces con un compañero adivinando números pensados por el. Anota cuantos intentos necesitaste. Escribe las reglas exactas del juego, incluyendo que pasa si el jugador escribe un número fuera del rango.', 'Reglas escritas y registro de tres partidas humanas.', 40],
   ['desarrollar', 'Diagrama de las decisiones', 'Dibuja el diagrama de flujo del juego: entrada, comparación, tres salidas posibles, vuelta al inicio. Marca donde termina el ciclo.', 'Diagrama de flujo con las tres ramas y la condición de salida.', 45],
   ['crear', 'Programar el juego con contador', 'Implementa el juego con while y condicionales. Agrega un contador de intentos y un mensaje final con el total. Si te sobra tiempo, valida que el número esté entre 1 y 100.', 'Archivo adivina.py funcionando con contador.', 70],
   ['evaluar', 'Al azar contra partir por la mitad', 'Juega cinco partidas adivinando al azar y cinco partiendo siempre por la mitad del rango restante. Registra los intentos de cada una y calcula el promedio. Explica el resultado.', 'Tabla de diez partidas, promedios y conclusión escrita.', 45],
 ],
 'recursos' => [
   ['plantilla', 'Registro de partidas', 'Tabla de estrategia, partida, intentos.'],
   ['lectura', 'El ciclo while y la condición de salida', 'Guía breve con el error del ciclo infinito.'],
 ]],

['codigo' => 'VCP-6-06', 'titulo' => 'Conversor de unidades para la clase de Ciencias',
 'objeto' => 'el conversor de unidades',
 'resumen' => 'Construir funciones reutilizables que conviertan unidades y ponerlas al servicio de otra asignatura.',
 'descripcion' => '<p>El estudiante pregunta a su docente de Ciencias que conversiones necesita el curso (grados, masa, volumen, tiempo) y construye un conversor con una función por cada conversión. Es la primera vez que escribe <code>def</code>, y el motivo es genuino: la misma fórmula se usa muchas veces y copiarla es un error esperando ocurrir.</p><p>El producto se entrega a la clase de Ciencias y se prueba allí. Que otra asignatura use el programa cambia por completo la actitud del estudiante frente a la calidad de su trabajo.</p>',
 'pregunta' => '¿Que gano al empaquetar un cálculo dentro de una función en lugar de repetirlo?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Relaciones',
 'perfil' => 'Informado e instruido|Solidario', 'atl' => 'Transferencia|Colaboración',
 'objetivos' => 'Definir funciones con parámetros y retorno|Reutilizar una función en varios lugares|Construir un menú de opciones|Validar la entrada del usuario',
 'entregables' => 'Archivo conversor.py con al menos cuatro funciones|Menú funcionando|Acta de prueba firmada por un estudiante de la clase de Ciencias',
 'lenguaje' => 'Python', 'dificultad' => 'inicial', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "def celsius_a_fahrenheit(c):\n    return c * 9 / 5 + 32\n\n# TODO: escribe fahrenheit_a_celsius(f)\n# TODO: escribe kilogramos_a_libras(kg)\n# TODO: escribe metros_a_pies(m)\n\nprint(\"1. Celsius a Fahrenheit\")\n# TODO: completa el menu",
 'fases' => [
   ['indagar', 'Que necesita realmente Ciencias', 'Entrevista a tu docente de Ciencias o revisa tu cuaderno: identifica las cuatro conversiones que más usan en el periodo y con cuantos decimales las quieren.', 'Lista de cuatro conversiones con la fórmula y los decimales requeridos.', 40],
   ['desarrollar', 'Diseñar las funciones', 'Para cada conversión escribe el nombre de la función, que recibe y que devuelve. Diseña el menú: como elige el usuario, como sale del programa.', 'Tabla de funciones (nombre, parámetro, retorno) y boceto del menú.', 40],
   ['crear', 'Programar y reutilizar', 'Escribe cada función y pruébala por separado antes de armar el menú. Comprueba que ninguna función imprime: todas devuelven. La impresión ocurre solo en el menú.', 'Archivo conversor.py con funciones y menú.', 80],
   ['evaluar', 'Prueba en la clase de Ciencias', 'Lleva el programa a un compañero de la clase de Ciencias y pídele que convierta tres valores reales de su taller. Anota cada dificultad que tuvo sin ayudarlo.', 'Acta de prueba con tres conversiones y las dificultades observadas.', 50],
 ],
 'recursos' => [
   ['lectura', 'Funciones: definir, llamar y devolver', 'Guía con el error clásico de imprimir en vez de devolver.'],
   ['plantilla', 'Acta de prueba con usuario', 'Formato de observación: tarea, tiempo, dificultad, comentario del usuario.'],
 ]],

['codigo' => 'VCP-6-07', 'titulo' => 'El cuento que decide su final',
 'objeto' => 'el cuento interactivo',
 'resumen' => 'Narrativa ramificada programada con condicionales anidados: cada decisión del lector cambia la historia.',
 'descripcion' => '<p>El estudiante escribe un cuento breve con tres puntos de decisión y al menos cuatro finales distintos, y lo programa con condicionales anidados. La actividad une Lengua y Diseño: la calidad del texto cuenta tanto como la corrección del código.</p><p>Antes de programar es obligatorio dibujar el árbol de la historia. Quien intenta programar sin el árbol se pierde en el tercer nivel de decisiones; ese es exactamente el aprendizaje que la actividad busca provocar.</p>',
 'pregunta' => '¿Como represento en un programa una historia que puede tomar muchos caminos distintos?',
 'contexto' => 'Expresión personal y cultural', 'concepto' => 'Comunicación',
 'perfil' => 'Buen comunicador|Audaz', 'atl' => 'Pensamiento creativo|Organización',
 'objetivos' => 'Representar decisiones con un árbol|Anidar condicionales correctamente|Escribir texto claro para el lector|Comprobar que todos los caminos llevan a un final',
 'entregables' => 'Árbol de la historia dibujado|Archivo cuento.py con cuatro finales|Registro de tres lectores que recorrieron caminos distintos',
 'lenguaje' => 'Python', 'dificultad' => 'inicial', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "print(\"Estas frente a dos puertas.\")\nopcion = input(\"Abres la roja o la azul? \").lower()\n\nif opcion == \"roja\":\n    print(\"La sala esta oscura.\")\n    # TODO: segunda decision dentro de esta rama\nelse:\n    print(\"Escuchas agua correr.\")\n    # TODO: segunda decision dentro de esta rama",
 'fases' => [
   ['indagar', 'Historias que se ramifican', 'Lee o recuerda un libro, videojuego o serie con finales múltiples. Explica que hace que una decisión del lector sea interesante y no arbitraria.', 'Análisis de un ejemplo con dos características de una buena decisión narrativa.', 40],
   ['desarrollar', 'El árbol de la historia', 'Dibuja el árbol completo: nodo inicial, tres decisiones, cuatro finales como mínimo. Cada rama debe tener texto escrito, no solo una flecha.', 'Árbol de decisiones completo con el texto de cada nodo.', 55],
   ['crear', 'Programar las ramas', 'Traduce el árbol a condicionales anidados. Usa .lower() para aceptar mayúsculas y minúsculas. Prueba cada camino recorriéndolo completo al menos una vez.', 'Archivo cuento.py con todos los caminos programados.', 80],
   ['evaluar', 'Tres lectores, tres caminos', 'Pide a tres personas que jueguen tu cuento sin explicarles nada. Anota que camino tomaron, donde dudaron y si algún camino no llegaba a un final.', 'Registro de tres lecturas y correcciones realizadas.', 45],
 ],
 'recursos' => [
   ['plantilla', 'Árbol narrativo', 'Hoja con nodos y ramas para completar a mano.'],
   ['lectura', 'Condicionales anidados sin perderse', 'Guía sobre indentación en Python.'],
 ]],

['codigo' => 'VCP-6-08', 'titulo' => 'Laberinto interactivo: proyecto del año',
 'objeto' => 'el laberinto interactivo',
 'resumen' => 'Proyecto insignia de 6.º: un laberinto jugable con niveles diseñados por el estudiante, que integra todo lo aprendido en el año.',
 'descripcion' => '<p>El proyecto reúne variables, condicionales, ciclos y funciones en un producto que otros pueden jugar. El estudiante diseña el mapa del laberinto en una cuadrícula de papel, lo representa como una lista de listas y programa el movimiento del jugador con las teclas, la detección de muros y la condición de victoria.</p><p>El requisito de tener al menos dos niveles obliga a separar el mapa del motor del juego: es la primera experiencia de diseño donde los datos van por un lado y la lógica por otro. La entrega incluye una prueba con jugadores de otro curso y un registro de las modificaciones hechas a partir de esa prueba.</p>',
 'pregunta' => '¿Como convierto una idea de juego en un producto que otra persona pueda usar sin que yo le explique nada?',
 'contexto' => 'Innovación científica y técnica', 'concepto' => 'Sistemas',
 'perfil' => 'Audaz|Reflexivo|Pensador', 'atl' => 'Organización|Autogestión|Pensamiento creativo',
 'objetivos' => 'Representar un mapa como estructura de datos|Programar movimiento y colisiones|Separar datos del juego de la lógica del juego|Iterar el producto a partir de pruebas con usuarios',
 'entregables' => 'Mapa de dos niveles en papel y en código|Archivo laberinto.py jugable|Registro de prueba con tres jugadores externos|Bitácora completa del ciclo de diseño',
 'lenguaje' => 'Python', 'dificultad' => 'intermedio', 'sesiones' => 6, 'horas' => 6.0, 'ia' => 1,
 'codigo_inicial' => "NIVEL_1 = [\n    \"#########\",\n    \"#J..#...#\",\n    \"#.#.#.#.#\",\n    \"#.#...#S#\",\n    \"#########\",\n]\n\ndef mostrar(mapa):\n    for fila in mapa:\n        print(fila)\n\n# TODO: encuentra la posicion de J\n# TODO: lee la tecla y mueve al jugador si no hay muro\n# TODO: gana cuando el jugador llega a S",
 'fases' => [
   ['indagar', 'Que hace divertido a un laberinto', 'Juega tres laberintos digitales o de papel. Anota cuanto tardaste, que te frustró y que te hizo querer seguir. Redacta el planteamiento del problema: para quien es tu laberinto y que debe lograr.', 'Análisis de tres juegos y planteamiento del problema en un párrafo.', 55],
   ['desarrollar', 'Mapa, reglas y especificaciones', 'Dibuja los dos niveles en cuadrícula. Escribe seis especificaciones medibles (por ejemplo: el jugador no puede atravesar muros, el nivel 2 debe tener al menos 15 muros, se muestra el número de movimientos).', 'Dos mapas en cuadrícula y seis especificaciones medibles.', 60],
   ['crear', 'Construir el motor del juego', 'Programa por etapas: mostrar el mapa, ubicar al jugador, mover, bloquear muros, detectar la salida, pasar de nivel. Registra en la bitácora cada etapa terminada con la fecha y el problema que resolviste.', 'Archivo laberinto.py con dos niveles jugables y bitácora de seis entradas.', 150],
   ['evaluar', 'Prueba con jugadores de otro curso', 'Tres personas ajenas al proyecto juegan sin instrucciones. Cronometra, anota errores y preguntas. Contrasta el resultado con tus seis especificaciones una por una y aplica al menos dos mejoras.', 'Informe de prueba, tabla de especificaciones cumplidas y dos mejoras aplicadas.', 55],
 ],
 'recursos' => [
   ['plantilla', 'Cuadrícula de diseño de niveles', 'Hoja imprimible de 9x5 y 15x9 celdas.'],
   ['plantilla', 'Bitácora del ciclo de diseño', 'Formato de entrada: fecha, fase, que hice, que falló, que decidí.'],
   ['lectura', 'Listas de listas para representar mapas', 'Guía con ejemplos de acceso por fila y columna.'],
 ]],

['codigo' => 'VCP-6-09', 'titulo' => 'Mi primer agente de IA: el ayudante de tareas',
 'objeto' => 'el agente ayudante',
 'resumen' => 'Diseñar un agente con propósito acotado y reglas claras, y comprobar por que un agente sin límites es un mal agente.',
 'descripcion' => '<p>El estudiante no consume inteligencia artificial: la diseña. Define el propósito de un agente que ayuda con las tareas de un compañero de 6.º, escribe sus reglas (que si puede hacer, que nunca debe hacer) y lo prueba con cinco preguntas, incluidas dos preguntas trampa que buscan que el agente resuelva la tarea completa en lugar de guiar.</p><p>Este es el punto donde el curso introduce la probidad académica: el agente debe ayudar a entender, no a entregar. El estudiante registra las conversaciones y las adjunta, tal como pide el IB al declarar el uso de herramientas de inteligencia artificial.</p>',
 'pregunta' => '¿En que se diferencia un ayudante que me hace aprender de uno que me hace dependiente?',
 'contexto' => 'Identidades y relaciones', 'concepto' => 'Comunicación',
 'perfil' => 'Íntegro|Reflexivo', 'atl' => 'Alfabetización mediática|Reflexión',
 'objetivos' => 'Definir el propósito y los límites de un agente|Escribir instrucciones claras para un sistema de IA|Probar el agente con casos difíciles|Declarar el uso de IA de forma trazable',
 'entregables' => 'Ficha del agente (propósito, tres reglas, dos prohibiciones)|Registro de cinco conversaciones de prueba|Reflexión sobre las dos preguntas trampa',
 'lenguaje' => 'Lenguaje natural', 'dificultad' => 'inicial', 'sesiones' => 3, 'horas' => 3.0, 'ia' => 1,
 'codigo_inicial' => "# Ficha del agente (completa en texto, no en codigo)\n# Nombre del agente:\n# Para quien es:\n# Que SI puede hacer (3 reglas):\n# Que NUNCA debe hacer (2 prohibiciones):\n# Como responde cuando le piden la respuesta completa:",
 'fases' => [
   ['indagar', 'Ayudas que enseñan y ayudas que reemplazan', 'Piensa en tres ayudas que recibes: un compañero que te explica, un familiar que te hace la tarea, un video. Clasifícalas y explica en cual aprendes más y por que.', 'Clasificación de tres ayudas con justificación.', 40],
   ['desarrollar', 'La ficha del agente', 'Escribe el propósito del agente en una frase, tres cosas que si puede hacer y dos que nunca debe hacer. Redacta la respuesta exacta que dará cuando le pidan resolver la tarea completa.', 'Ficha del agente completa.', 45],
   ['crear', 'Poner el agente a trabajar', 'Configura el agente en VCodePro con tu ficha. Hazle cinco preguntas: tres normales y dos trampa que busquen la respuesta completa. Guarda las cinco conversaciones.', 'Registro de las cinco conversaciones guardadas.', 55],
   ['evaluar', 'Cumplió sus propias reglas', 'Revisa cada conversación y marca si el agente respetó las reglas. Donde falló, corrige la ficha y vuelve a probar esa pregunta. Escribe que aprendiste sobre dar instrucciones a una máquina.', 'Tabla de cumplimiento por regla y ficha corregida.', 40],
 ],
 'recursos' => [
   ['plantilla', 'Ficha de diseño de agente', 'Formato con propósito, alcance, reglas, prohibiciones y respuesta ante peticiones indebidas.'],
   ['lectura', 'Declarar el uso de IA en el IB', 'Resumen para estudiantes de PAI sobre probidad académica.'],
 ]],

['codigo' => 'VCP-6-10', 'titulo' => 'Cartelera digital del salón',
 'objeto' => 'la cartelera digital',
 'resumen' => 'Programa que guarda avisos en una lista, los ordena por fecha y los muestra en pantalla como cartelera del curso.',
 'descripcion' => '<p>Cierre del año de 6.º: el estudiante construye una cartelera que guarda los avisos del curso en una lista, permite agregar y borrar, y los presenta ordenados. Aparece la lista como estructura para guardar muchos datos del mismo tipo, y el recorrido con <code>for</code> sobre esa lista.</p><p>El producto se usa de verdad: el curso elige la mejor cartelera y la proyecta durante una semana. El criterio de elección no es la belleza sino la utilidad, medida con una encuesta de cinco preguntas al grupo.</p>',
 'pregunta' => '¿Como guardo muchos datos del mismo tipo sin inventar una variable para cada uno?',
 'contexto' => 'Identidades y relaciones', 'concepto' => 'Comunicación',
 'perfil' => 'Solidario|Buen comunicador', 'atl' => 'Organización|Colaboración',
 'objetivos' => 'Crear y recorrer listas|Agregar y eliminar elementos de una lista|Ordenar datos con un criterio|Diseñar una salida legible en pantalla',
 'entregables' => 'Archivo cartelera.py con agregar, borrar y listar|Encuesta de utilidad respondida por cinco compañeros|Versión final corregida tras la encuesta',
 'lenguaje' => 'Python', 'dificultad' => 'inicial', 'sesiones' => 4, 'horas' => 4.0, 'ia' => 1,
 'codigo_inicial' => "avisos = []\n\ndef agregar(texto, fecha):\n    avisos.append({\"texto\": texto, \"fecha\": fecha})\n\n# TODO: funcion listar() que recorra avisos y los imprima\n# TODO: funcion borrar(indice)\n# TODO: menu con las tres opciones",
 'fases' => [
   ['indagar', 'Que avisos necesita el curso', 'Observa la cartelera física del salón durante una semana. Clasifica los avisos por tipo y anota cuales quedaron desactualizados. Pregunta a cinco compañeros que información buscan primero.', 'Inventario de avisos y resultado de la consulta a cinco compañeros.', 45],
   ['desarrollar', 'Estructura de un aviso', 'Decide que campos tendrá cada aviso (texto, fecha, autor, importancia) y como se verán en pantalla. Escribe cinco especificaciones, una de ellas sobre el orden en que aparecen.', 'Estructura del aviso y cinco especificaciones.', 40],
   ['crear', 'Programar la cartelera', 'Implementa agregar, listar y borrar sobre una lista. Ordena los avisos por fecha antes de mostrarlos. Prueba con al menos ocho avisos reales del curso.', 'Archivo cartelera.py con ocho avisos reales cargados.', 75],
   ['evaluar', 'Encuesta de utilidad', 'Cinco compañeros usan tu cartelera y responden: encontré lo que buscaba, en cuanto tiempo, que me sobra, que me falta. Aplica dos cambios a partir de las respuestas.', 'Resultados de la encuesta y dos cambios aplicados con su justificación.', 45],
 ],
 'recursos' => [
   ['plantilla', 'Encuesta de utilidad de cinco preguntas', 'Formato listo para imprimir o compartir.'],
   ['lectura', 'Listas en Python: agregar, recorrer, borrar', 'Referencia rápida con ejemplos.'],
 ]],

];
